<a href="https://colab.research.google.com/github/MiguelFigueroa02/ITAM_Sport_Lucho_FC/blob/main/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import json
import pandas as pd
import numpy as np
from pathlib import Path
import re

## 1. Carga de datos
---
A partir de los archivos json disponibles, procesamos los datos para construir un dataset que contenga todos los partidos del américa disponibles en el periodo 2023 - 2026

In [4]:
DATA_DIR = Path("/content/")
OUTPUT_FILE = Path("/content/america_matches.csv")
AMERICA_ID = 1229

In [5]:
json_files = sorted(DATA_DIR.glob("matches-*.json"))

In [6]:
if not json_files:
    raise FileNotFoundError(
        f"No se encontraron archivos JSON en: {DATA_DIR.resolve()}"
    )

In [7]:
records = []

for file in json_files:

    print(f"\nArchivo: {file.name}")

    with open(file, "r", encoding="utf-8") as f:
        matches = json.load(f)

    print(f"Partidos encontrados en archivo: {len(matches)}")

    for match in matches:

        home = match["home_team"]
        away = match["away_team"]

        home_id = home["home_team_id"]
        away_id = away["away_team_id"]

        if home_id != AMERICA_ID and away_id != AMERICA_ID:
            continue

        is_home = home_id == AMERICA_ID

        opponent = (
            away["away_team_name"]
            if is_home
            else home["home_team_name"]
        )

        america_score = (
            match["home_score"]
            if is_home
            else match["away_score"]
        )

        opponent_score = (
            match["away_score"]
            if is_home
            else match["home_score"]
        )


        managers = home.get("managers", []) if is_home else away.get("managers", [])

        coach = (
            managers[0]["name"]
            if managers
            else None
        )


        records.append({

            "match_id": match["match_id"],

            "match_date": match["match_date"],

            "kick_off": match.get("kick_off"),

            "season": match["season"]["season_name"],

            "competition": match["competition"]["competition_name"],

            "competition_stage": (
                match.get("competition_stage", {}).get("name")
            ),

            "match_week": match.get("match_week"),

            "opponent": opponent,

            "venue": "Home" if is_home else "Away",

            "america_score": america_score,

            "opponent_score": opponent_score,

            "coach": coach,

            "stadium": (
                match.get("stadium", {}).get("name")
            ),

            "match_status": match.get("match_status"),

            "match_status_360": match.get("match_status_360"),

        })



america_matches = pd.DataFrame(records)


if america_matches.empty:
    raise ValueError(
        "No se encontraron partidos del América. "
        "Revisa el AMERICA_ID."
    )


def get_result(row):

    if row["america_score"] > row["opponent_score"]:
        return "W"

    elif row["america_score"] == row["opponent_score"]:
        return "D"

    else:
        return "L"


america_matches["result"] = america_matches.apply(
    get_result,
    axis=1
)


america_matches["match_date"] = pd.to_datetime(
    america_matches["match_date"]
)


america_matches = america_matches.sort_values(
    ["match_date", "match_id"]
).reset_index(drop=True)



OUTPUT_FILE.parent.mkdir(
    parents=True,
    exist_ok=True
)



america_matches.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


print("\n" + "=" * 60)
print("CATÁLOGO DEL AMÉRICA")
print("=" * 60)

print(f"\nTotal de partidos: {len(america_matches)}")

print("\nPartidos por temporada:")
print(
    america_matches
    .groupby("season")
    .size()
    .sort_index()
)

print("\nResultados:")
print(
    america_matches["result"]
    .value_counts()
)

print("\nLocal / Visitante:")
print(
    america_matches["venue"]
    .value_counts()
)

print("\nDisponibilidad de 360:")
print(
    america_matches["match_status_360"]
    .value_counts(dropna=False)
)

print("\nEntrenadores:")
print(
    america_matches["coach"]
    .value_counts(dropna=False)
)

print(f"\nArchivo generado:")
print(OUTPUT_FILE.resolve())

print("\nPrimeros registros:")
print(
    america_matches.head(10).to_string(index=False)
)

Archivo: matches-2023-2024.json
Partidos encontrados en archivo: 340

Archivo: matches-2024-2025.json
Partidos encontrados en archivo: 340

Archivo: matches-2025-2026.json
Partidos encontrados en archivo: 337

============================================================
CATÁLOGO DEL AMÉRICA
============================================================

Total de partidos: 131

Partidos por temporada:
season
2023/2024    46
2024/2025    47
2025/2026    38
dtype: int64

Resultados:
result
W    69
D    37
L    25
Name: count, dtype: int64

Local / Visitante:
venue
Away    66
Home    65
Name: count, dtype: int64

Disponibilidad de 360:
match_status_360
available      130
unscheduled      1
Name: count, dtype: int64

Entrenadores:
coach
André Soares Jardine              129
Diego Alberto Cervantes Chávez      2
Name: count, dtype: int64

Archivo generado:
/content/america_matches.csv

Primeros registros:
 match_id match_date     kick_off    season competition competition_stage  match_week    opponent venue  america_score  opponent_score                coach                stadium match_status match_status_360 result
  3889637 2023-07-01 01:00:00.000 2023/2024     Liga MX          Apertura           1      Juárez  Home              1               2 André Soares Jardine         Estadio Azteca    available        available      L
  3889660 2023-07-16 01:00:00.000 2023/2024     Liga MX          Apertura           3      Puebla  Home              3               0 André Soares Jardine         Estadio Azteca    available        available      W
  3889669 2023-08-21 03:10:00.000 2023/2024     Liga MX          Apertura           4       Atlas  Home              1               1 André Soares Jardine        Estadio Jalisco    available        available      D
  3889681 2023-08-24 01:00:00.000 2023/2024     Liga MX          Apertura           5      Necaxa  Home              3               2 André Soares Jardine         Estadio Azteca    available        available      W
  3889685 2023-08-27 01:00:00.000 2023/2024     Liga MX          Apertura           6        León  Home              1               1 André Soares Jardine         Estadio Azteca    available        available      D
  3889699 2023-09-03 03:10:00.000 2023/2024     Liga MX          Apertura           7   Cruz Azul  Away              3               2 André Soares Jardine         Estadio Azteca    available        available      W
  3889702 2023-09-17 03:10:00.000 2023/2024     Liga MX          Apertura           8 Guadalajara  Home              4               0 André Soares Jardine         Estadio Azteca    available        available      W
  3889653 2023-09-21 02:06:00.000 2023/2024     Liga MX          Apertura           2   Querétaro  Away              2               1 André Soares Jardine Estadio La Corregidora    available        available      W
  3889715 2023-09-24 18:00:00.000 2023/2024     Liga MX          Apertura           9      Toluca  Away              1               1 André Soares Jardine   Estadio Nemesio Díez    available        available      D
  3889725 2023-10-01 00:40:00.000 2023/2024     Liga MX          Apertura          10  Pumas UNAM  Home              1               0 André Soares Jardine         Estadio Azteca    available        available      W

## 2.  Auditoría inicial de los datos de los eventos de partidos.
---

Hacemos en primera instancia una evaluación inicial de los datos.

## 3. Integración y exploración de los datos

In [8]:
def evaluacion(archivo):
  repo = 'https://raw.githubusercontent.com/MiguelFigueroa02/ITAM_Sport_Lucho_FC/refs/heads/main/data/raw/'
  path = repo + archivo
  CHUNK_SIZE = 50_000
  print("### Evaluación de eventos")
  header = pd.read_csv(
      path,
      nrows=0
    )
  columns = header.columns.tolist()
  print(f"\nNúmero de columnas: {len(columns)}")
  print("\nColumnas:")
  for i, col in enumerate(columns, start=1):
      print(f"{i:3}. {col}")

  total_rows = 0
  unique_matches = set()

  sample = None

  for chunk in pd.read_csv(
      path,
      chunksize=CHUNK_SIZE,
      low_memory=False,
      on_bad_lines='skip'
  ):

      total_rows += len(chunk)

      if sample is None:
          sample = chunk.head(5).copy()

      if "match_id" in chunk.columns:
          unique_matches.update(
              chunk["match_id"].dropna().unique()
          )

  print("### RESUMEN")

  print(f"\nFilas totales: {total_rows:,}")

  print(f"Partidos únicos: {len(unique_matches):,}")

  print("### MUESTRA DE EVENTOS")

  print(
    sample.to_csv(index=False)
  )
  print("### TIPOS DE DATOS")

  print(sample.dtypes)

In [9]:
evaluacion('Liga_MX_2023_2024_America_p1.csv')

### Evaluación de eventos

Número de columnas: 251

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 5556_defensive_responsibility_probability
124. 26389_defensive_responsibility_probability
125. 6357_defensive_responsibility_probability
126. 8863_defensive_responsibility_probability
127. 11388_defensive_responsibility_probability
128. 13034_defensive_responsibility_probability
129. 23842_defensive_responsibility_probability
130. 26278_defensive_responsibility_probability
131. 26298_defensive_responsibility_probability
132. 26309_defensive_responsibility_probability
133. 26356_defensive_responsibility_probability
134. 26369_defensive_responsibility_probability
135. 29518_defensive_responsibility_probability
136. 28433_defensive_responsibility_probability
137. 28530_defensive_responsibility_probability
138. 28562_defensive_responsibility_probability
139. 33097_defensive_responsibility_probability
140. 34361_defensive_responsibility_probability
141. 30500_defensive_responsibility_probability
142. 30736_defensive_responsibility_probability
143. 30846_defensive_responsibility_probability
144. 31312_defensive_responsibility_probability
145. 31956_defensive_responsibility_probability
146. 32728_defensive_responsibility_probability
147. 41777_defensive_responsibility_probability
148. 35544_defensive_responsibility_probability
149. 36167_defensive_responsibility_probability
150. 35690_defensive_responsibility_probability
151. 37072_defensive_responsibility_probability
152. 43720_defensive_responsibility_probability
153. 391381_defensive_responsibility_probability
154. 131162_defensive_responsibility_probability
155. 134157_defensive_responsibility_probability
156. 182089_defensive_responsibility_probability
157. 277725_defensive_responsibility_probability
158. 283233_defensive_responsibility_probability
159. 302108_defensive_responsibility_probability
160. 399838_defensive_responsibility_probability
161. 399839_defensive_responsibility_probability
162. 399840_defensive_responsibility_probability
163. 399841_defensive_responsibility_probability
164. 5556_pressure_like_defensive_responsibility_probability
165. 26389_pressure_like_defensive_responsibility_probability
166. 6357_pressure_like_defensive_responsibility_probability
167. 8863_pressure_like_defensive_responsibility_probability
168. 11388_pressure_like_defensive_responsibility_probability
169. 13034_pressure_like_defensive_responsibility_probability
170. 23842_pressure_like_defensive_responsibility_probability
171. 26278_pressure_like_defensive_responsibility_probability
172. 26298_pressure_like_defensive_responsibility_probability
173. 26309_pressure_like_defensive_responsibility_probability
174. 26356_pressure_like_defensive_responsibility_probability
175. 26369_pressure_like_defensive_responsibility_probability
176. 29518_pressure_like_defensive_responsibility_probability
177. 28433_pressure_like_defensive_responsibility_probability
178. 28530_pressure_like_defensive_responsibility_probability
179. 28562_pressure_like_defensive_responsibility_probability
180. 33097_pressure_like_defensive_responsibility_probability
181. 34361_pressure_like_defensive_responsibility_probability
182. 30500_pressure_like_defensive_responsibility_probability
183. 30736_pressure_like_defensive_responsibility_probability
184. 30846_pressure_like_defensive_responsibility_probability
185. 31312_pressure_like_defensive_responsibility_probability
186. 31956_pressure_like_defensive_responsibility_probability
187. 32728_pressure_like_defensive_responsibility_probability
188. 41777_pressure_like_defensive_responsibility_probability
189. 35544_pressure_like_defensive_responsibility_probability
190. 36167_pressure_like_defensive_responsibility_probability
191. 35690_pressure_like_defensive_responsibility_probability
192. 37072_pressure_like_defensive_responsibility_probability
193. 43720_pressure_like_defensive_responsibility_probability
194. 391381_pressure_like_defensive_responsibility_probability
195. 131162_pressure_like_defensive_responsibility_probability
196. 134157_pressure_like_defensive_responsibility_probability
197. 182089_pressure_like_defensive_responsibility_probability
198. 277725_pressure_like_defensive_responsibility_probability
199. 283233_pressure_like_defensive_responsibility_probability
200. 302108_pressure_like_defensive_responsibility_probability
201. 399838_pressure_like_defensive_responsibility_probability
202. 399839_pressure_like_defensive_responsibility_probability
203. 399840_pressure_like_defensive_responsibility_probability
204. 399841_pressure_like_defensive_responsibility_probability
205. 5556_interception_like_defensive_responsibility_probability
206. 26389_interception_like_defensive_responsibility_probability
207. 6357_interception_like_defensive_responsibility_probability
208. 8863_interception_like_defensive_responsibility_probability
209. 11388_interception_like_defensive_responsibility_probability
210. 13034_interception_like_defensive_responsibility_probability
211. 23842_interception_like_defensive_responsibility_probability
212. 26278_interception_like_defensive_responsibility_probability
213. 26298_interception_like_defensive_responsibility_probability
214. 26309_interception_like_defensive_responsibility_probability
215. 26356_interception_like_defensive_responsibility_probability
216. 26369_interception_like_defensive_responsibility_probability
217. 29518_interception_like_defensive_responsibility_probability
218. 28433_interception_like_defensive_responsibility_probability
219. 28530_interception_like_defensive_responsibility_probability
220. 28562_interception_like_defensive_responsibility_probability
221. 33097_interception_like_defensive_responsibility_probability
222. 34361_interception_like_defensive_responsibility_probability
223. 30500_interception_like_defensive_responsibility_probability
224. 30736_interception_like_defensive_responsibility_probability
225. 30846_interception_like_defensive_responsibility_probability
226. 31312_interception_like_defensive_responsibility_probability
227. 31956_interception_like_defensive_responsibility_probability
228. 32728_interception_like_defensive_responsibility_probability
229. 41777_interception_like_defensive_responsibility_probability
230. 35544_interception_like_defensive_responsibility_probability
231. 36167_interception_like_defensive_responsibility_probability
232. 35690_interception_like_defensive_responsibility_probability
233. 37072_interception_like_defensive_responsibility_probability
234. 43720_interception_like_defensive_responsibility_probability
235. 391381_interception_like_defensive_responsibility_probability
236. 131162_interception_like_defensive_responsibility_probability
237. 134157_interception_like_defensive_responsibility_probability
238. 182089_interception_like_defensive_responsibility_probability
239. 277725_interception_like_defensive_responsibility_probability
240. 283233_interception_like_defensive_responsibility_probability
241. 302108_interception_like_defensive_responsibility_probability
242. 399838_interception_like_defensive_responsibility_probability
243. 399839_interception_like_defensive_responsibility_probability
244. 399840_interception_like_defensive_responsibility_probability
245. 399841_interception_like_defensive_responsibility_probability
246. control_degree
247. is_transition
248. is_controlled_possession
249. player_possession_directness
250. possession_directness
251. location_bucket
### RESUMEN

Filas totales: 8,311
Partidos únicos: 2
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,5556_defensive_responsibility_probability,26389_defensive_responsibility_probability,6357_defensive_responsibility_probability,8863_defensive_responsibility_probability,11388_defensive_responsibility_probability,13034_defensive_responsibility_probability,23842_defensive_responsibility_probability,26278_defensive_responsibility_probability,26298_defensive_responsibility_probability,26309_defensive_responsibility_probability,26356_defensive_responsibility_probability,26369_defensive_responsibility_probability,29518_defensive_responsibility_probability,28433_defensive_responsibility_probability,28530_defensive_responsibility_probability,28562_defensive_responsibility_probability,33097_defensive_responsibility_probability,34361_defensive_responsibility_probability,30500_defensive_responsibility_probability,30736_defensive_responsibility_probability,30846_defensive_responsibility_probability,31312_defensive_responsibility_probability,31956_defensive_responsibility_probability,32728_defensive_responsibility_probability,41777_defensive_responsibility_probability,35544_defensive_responsibility_probability,36167_defensive_responsibility_probability,35690_defensive_responsibility_probability,37072_defensive_responsibility_probability,43720_defensive_responsibility_probability,391381_defensive_responsibility_probability,131162_defensive_responsibility_probability,134157_defensive_responsibility_probability,182089_defensive_responsibility_probability,277725_defensive_responsibility_probability,283233_defensive_responsibility_probability,302108_defensive_responsibility_probability,399838_defensive_responsibility_probability,399839_defensive_responsibility_probability,399840_defensive_responsibility_probability,399841_defensive_responsibility_probability,5556_pressure_like_defensive_responsibility_probability,26389_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,8863_pressure_like_defensive_responsibility_probability,11388_pressure_like_defensive_responsibility_probability,13034_pressure_like_defensive_responsibility_probability,23842_pressure_like_defensive_responsibility_probability,26278_pressure_like_defensive_responsibility_probability,26298_pressure_like_defensive_responsibility_probability,26309_pressure_like_defensive_responsibility_probability,26356_pressure_like_defensive_responsibility_probability,26369_pressure_like_defensive_responsibility_probability,29518_pressure_like_defensive_responsibility_probability,28433_pressure_like_defensive_responsibility_probability,28530_pressure_like_defensive_responsibility_probability,28562_pressure_like_defensive_responsibility_probability,33097_pressure_like_defensive_responsibility_probability,34361_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30736_pressure_like_defensive_responsibility_probability,30846_pressure_like_defensive_responsibility_probability,31312_pressure_like_defensive_responsibility_probability,31956_pressure_like_defensive_responsibility_probability,32728_pressure_like_defensive_responsibility_probability,41777_pressure_like_defensive_responsibility_probability,35544_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,35690_pressure_like_defensive_responsibility_probability,37072_pressure_like_defensive_responsibility_probability,43720_pressure_like_defensive_responsibility_probability,391381_pressure_like_defensive_responsibility_probability,131162_pressure_like_defensive_responsibility_probability,134157_pressure_like_defensive_responsibility_probability,182089_pressure_like_defensive_responsibility_probability,277725_pressure_like_defensive_responsibility_probability,283233_pressure_like_defensive_responsibility_probability,302108_pressure_like_defensive_responsibility_probability,399838_pressure_like_defensive_responsibility_probability,399839_pressure_like_defensive_responsibility_probability,399840_pressure_like_defensive_responsibility_probability,399841_pressure_like_defensive_responsibility_probability,5556_interception_like_defensive_responsibility_probability,26389_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,8863_interception_like_defensive_responsibility_probability,11388_interception_like_defensive_responsibility_probability,13034_interception_like_defensive_responsibility_probability,23842_interception_like_defensive_responsibility_probability,26278_interception_like_defensive_responsibility_probability,26298_interception_like_defensive_responsibility_probability,26309_interception_like_defensive_responsibility_probability,26356_interception_like_defensive_responsibility_probability,26369_interception_like_defensive_responsibility_probability,29518_interception_like_defensive_responsibility_probability,28433_interception_like_defensive_responsibility_probability,28530_interception_like_defensive_responsibility_probability,28562_interception_like_defensive_responsibility_probability,33097_interception_like_defensive_responsibility_probability,34361_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30736_interception_like_defensive_responsibility_probability,30846_interception_like_defensive_responsibility_probability,31312_interception_like_defensive_responsibility_probability,31956_interception_like_defensive_responsibility_probability,32728_interception_like_defensive_responsibility_probability,41777_interception_like_defensive_responsibility_probability,35544_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,35690_interception_like_defensive_responsibility_probability,37072_interception_like_defensive_responsibility_probability,43720_interception_like_defensive_responsibility_probability,391381_interception_like_defensive_responsibility_probability,131162_interception_like_defensive_responsibility_probability,134157_interception_like_defensive_responsibility_probability,182089_interception_like_defensive_responsibility_probability,277725_interception_like_defensive_responsibility_probability,283233_interception_like_defensive_responsibility_probability,302108_interception_like_defensive_responsibility_probability,399838_interception_like_defensive_responsibility_probability,399839_interception_like_defensive_responsibility_probability,399840_interception_like_defensive_responsibility_probability,399841_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,,,5,Other,1229,América,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,right_to_left,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
d8fe445f-221e-5f37-8c9e-bf911d060299,2,3889637,1,00:00,0,0,35,Starting XI,1,,,5,Other,1291,Juárez,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [10]:
evaluacion('Liga_MX_2023_2024_America_p2.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 9926_defensive_responsibility_probability
124. 45685_defensive_responsibility_probability
125. 5556_defensive_responsibility_probability
126. 6357_defensive_responsibility_probability
127. 8863_defensive_responsibility_probability
128. 10846_defensive_responsibility_probability
129. 26774_defensive_responsibility_probability
130. 26288_defensive_responsibility_probability
131. 26256_defensive_responsibility_probability
132. 26400_defensive_responsibility_probability
133. 26289_defensive_responsibility_probability
134. 26311_defensive_responsibility_probability
135. 26327_defensive_responsibility_probability
136. 26369_defensive_responsibility_probability
137. 30458_defensive_responsibility_probability
138. 28056_defensive_responsibility_probability
139. 27967_defensive_responsibility_probability
140. 28160_defensive_responsibility_probability
141. 29518_defensive_responsibility_probability
142. 29424_defensive_responsibility_probability
143. 33126_defensive_responsibility_probability
144. 28530_defensive_responsibility_probability
145. 32164_defensive_responsibility_probability
146. 29269_defensive_responsibility_probability
147. 29266_defensive_responsibility_probability
148. 33097_defensive_responsibility_probability
149. 30500_defensive_responsibility_probability
150. 33098_defensive_responsibility_probability
151. 43557_defensive_responsibility_probability
152. 35375_defensive_responsibility_probability
153. 31956_defensive_responsibility_probability
154. 36167_defensive_responsibility_probability
155. 35953_defensive_responsibility_probability
156. 35690_defensive_responsibility_probability
157. 43547_defensive_responsibility_probability
158. 44922_defensive_responsibility_probability
159. 47467_defensive_responsibility_probability
160. 50461_defensive_responsibility_probability
161. 123690_defensive_responsibility_probability
162. 131123_defensive_responsibility_probability
163. 226626_defensive_responsibility_probability
164. 401174_defensive_responsibility_probability
165. 9926_pressure_like_defensive_responsibility_probability
166. 45685_pressure_like_defensive_responsibility_probability
167. 5556_pressure_like_defensive_responsibility_probability
168. 6357_pressure_like_defensive_responsibility_probability
169. 8863_pressure_like_defensive_responsibility_probability
170. 10846_pressure_like_defensive_responsibility_probability
171. 26774_pressure_like_defensive_responsibility_probability
172. 26288_pressure_like_defensive_responsibility_probability
173. 26256_pressure_like_defensive_responsibility_probability
174. 26400_pressure_like_defensive_responsibility_probability
175. 26289_pressure_like_defensive_responsibility_probability
176. 26311_pressure_like_defensive_responsibility_probability
177. 26327_pressure_like_defensive_responsibility_probability
178. 26369_pressure_like_defensive_responsibility_probability
179. 30458_pressure_like_defensive_responsibility_probability
180. 28056_pressure_like_defensive_responsibility_probability
181. 27967_pressure_like_defensive_responsibility_probability
182. 28160_pressure_like_defensive_responsibility_probability
183. 29518_pressure_like_defensive_responsibility_probability
184. 29424_pressure_like_defensive_responsibility_probability
185. 33126_pressure_like_defensive_responsibility_probability
186. 28530_pressure_like_defensive_responsibility_probability
187. 32164_pressure_like_defensive_responsibility_probability
188. 29269_pressure_like_defensive_responsibility_probability
189. 29266_pressure_like_defensive_responsibility_probability
190. 33097_pressure_like_defensive_responsibility_probability
191. 30500_pressure_like_defensive_responsibility_probability
192. 33098_pressure_like_defensive_responsibility_probability
193. 43557_pressure_like_defensive_responsibility_probability
194. 35375_pressure_like_defensive_responsibility_probability
195. 31956_pressure_like_defensive_responsibility_probability
196. 36167_pressure_like_defensive_responsibility_probability
197. 35953_pressure_like_defensive_responsibility_probability
198. 35690_pressure_like_defensive_responsibility_probability
199. 43547_pressure_like_defensive_responsibility_probability
200. 44922_pressure_like_defensive_responsibility_probability
201. 47467_pressure_like_defensive_responsibility_probability
202. 50461_pressure_like_defensive_responsibility_probability
203. 123690_pressure_like_defensive_responsibility_probability
204. 131123_pressure_like_defensive_responsibility_probability
205. 226626_pressure_like_defensive_responsibility_probability
206. 401174_pressure_like_defensive_responsibility_probability
207. 9926_interception_like_defensive_responsibility_probability
208. 45685_interception_like_defensive_responsibility_probability
209. 5556_interception_like_defensive_responsibility_probability
210. 6357_interception_like_defensive_responsibility_probability
211. 8863_interception_like_defensive_responsibility_probability
212. 10846_interception_like_defensive_responsibility_probability
213. 26774_interception_like_defensive_responsibility_probability
214. 26288_interception_like_defensive_responsibility_probability
215. 26256_interception_like_defensive_responsibility_probability
216. 26400_interception_like_defensive_responsibility_probability
217. 26289_interception_like_defensive_responsibility_probability
218. 26311_interception_like_defensive_responsibility_probability
219. 26327_interception_like_defensive_responsibility_probability
220. 26369_interception_like_defensive_responsibility_probability
221. 30458_interception_like_defensive_responsibility_probability
222. 28056_interception_like_defensive_responsibility_probability
223. 27967_interception_like_defensive_responsibility_probability
224. 28160_interception_like_defensive_responsibility_probability
225. 29518_interception_like_defensive_responsibility_probability
226. 29424_interception_like_defensive_responsibility_probability
227. 33126_interception_like_defensive_responsibility_probability
228. 28530_interception_like_defensive_responsibility_probability
229. 32164_interception_like_defensive_responsibility_probability
230. 29269_interception_like_defensive_responsibility_probability
231. 29266_interception_like_defensive_responsibility_probability
232. 33097_interception_like_defensive_responsibility_probability
233. 30500_interception_like_defensive_responsibility_probability
234. 33098_interception_like_defensive_responsibility_probability
235. 43557_interception_like_defensive_responsibility_probability
236. 35375_interception_like_defensive_responsibility_probability
237. 31956_interception_like_defensive_responsibility_probability
238. 36167_interception_like_defensive_responsibility_probability
239. 35953_interception_like_defensive_responsibility_probability
240. 35690_interception_like_defensive_responsibility_probability
241. 43547_interception_like_defensive_responsibility_probability
242. 44922_interception_like_defensive_responsibility_probability
243. 47467_interception_like_defensive_responsibility_probability
244. 50461_interception_like_defensive_responsibility_probability
245. 123690_interception_like_defensive_responsibility_probability
246. 131123_interception_like_defensive_responsibility_probability
247. 226626_interception_like_defensive_responsibility_probability
248. 401174_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 79,889
Partidos únicos: 20
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,9926_defensive_responsibility_probability,45685_defensive_responsibility_probability,5556_defensive_responsibility_probability,6357_defensive_responsibility_probability,8863_defensive_responsibility_probability,10846_defensive_responsibility_probability,26774_defensive_responsibility_probability,26288_defensive_responsibility_probability,26256_defensive_responsibility_probability,26400_defensive_responsibility_probability,26289_defensive_responsibility_probability,26311_defensive_responsibility_probability,26327_defensive_responsibility_probability,26369_defensive_responsibility_probability,30458_defensive_responsibility_probability,28056_defensive_responsibility_probability,27967_defensive_responsibility_probability,28160_defensive_responsibility_probability,29518_defensive_responsibility_probability,29424_defensive_responsibility_probability,33126_defensive_responsibility_probability,28530_defensive_responsibility_probability,32164_defensive_responsibility_probability,29269_defensive_responsibility_probability,29266_defensive_responsibility_probability,33097_defensive_responsibility_probability,30500_defensive_responsibility_probability,33098_defensive_responsibility_probability,43557_defensive_responsibility_probability,35375_defensive_responsibility_probability,31956_defensive_responsibility_probability,36167_defensive_responsibility_probability,35953_defensive_responsibility_probability,35690_defensive_responsibility_probability,43547_defensive_responsibility_probability,44922_defensive_responsibility_probability,47467_defensive_responsibility_probability,50461_defensive_responsibility_probability,123690_defensive_responsibility_probability,131123_defensive_responsibility_probability,226626_defensive_responsibility_probability,401174_defensive_responsibility_probability,9926_pressure_like_defensive_responsibility_probability,45685_pressure_like_defensive_responsibility_probability,5556_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,8863_pressure_like_defensive_responsibility_probability,10846_pressure_like_defensive_responsibility_probability,26774_pressure_like_defensive_responsibility_probability,26288_pressure_like_defensive_responsibility_probability,26256_pressure_like_defensive_responsibility_probability,26400_pressure_like_defensive_responsibility_probability,26289_pressure_like_defensive_responsibility_probability,26311_pressure_like_defensive_responsibility_probability,26327_pressure_like_defensive_responsibility_probability,26369_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,28056_pressure_like_defensive_responsibility_probability,27967_pressure_like_defensive_responsibility_probability,28160_pressure_like_defensive_responsibility_probability,29518_pressure_like_defensive_responsibility_probability,29424_pressure_like_defensive_responsibility_probability,33126_pressure_like_defensive_responsibility_probability,28530_pressure_like_defensive_responsibility_probability,32164_pressure_like_defensive_responsibility_probability,29269_pressure_like_defensive_responsibility_probability,29266_pressure_like_defensive_responsibility_probability,33097_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,33098_pressure_like_defensive_responsibility_probability,43557_pressure_like_defensive_responsibility_probability,35375_pressure_like_defensive_responsibility_probability,31956_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,35953_pressure_like_defensive_responsibility_probability,35690_pressure_like_defensive_responsibility_probability,43547_pressure_like_defensive_responsibility_probability,44922_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,50461_pressure_like_defensive_responsibility_probability,123690_pressure_like_defensive_responsibility_probability,131123_pressure_like_defensive_responsibility_probability,226626_pressure_like_defensive_responsibility_probability,401174_pressure_like_defensive_responsibility_probability,9926_interception_like_defensive_responsibility_probability,45685_interception_like_defensive_responsibility_probability,5556_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,8863_interception_like_defensive_responsibility_probability,10846_interception_like_defensive_responsibility_probability,26774_interception_like_defensive_responsibility_probability,26288_interception_like_defensive_responsibility_probability,26256_interception_like_defensive_responsibility_probability,26400_interception_like_defensive_responsibility_probability,26289_interception_like_defensive_responsibility_probability,26311_interception_like_defensive_responsibility_probability,26327_interception_like_defensive_responsibility_probability,26369_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,28056_interception_like_defensive_responsibility_probability,27967_interception_like_defensive_responsibility_probability,28160_interception_like_defensive_responsibility_probability,29518_interception_like_defensive_responsibility_probability,29424_interception_like_defensive_responsibility_probability,33126_interception_like_defensive_responsibility_probability,28530_interception_like_defensive_responsibility_probability,32164_interception_like_defensive_responsibility_probability,29269_interception_like_defensive_responsibility_probability,29266_interception_like_defensive_responsibility_probability,33097_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,33098_interception_like_defensive_responsibility_probability,43557_interception_like_defensive_responsibility_probability,35375_interception_like_defensive_responsibility_probability,31956_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,35953_interception_like_defensive_responsibility_probability,35690_interception_like_defensive_responsibility_probability,43547_interception_like_defensive_responsibility_probability,44922_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,50461_interception_like_defensive_responsibility_probability,123690_interception_like_defensive_responsibility_probability,131123_interception_like_defensive_responsibility_probability,226626_interception_like_defensive_responsibility_probability,401174_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
e7da0069-e56c-5c18-a337-d9810642d97d,1,3917858,1,00:00,0,0,35,Starting XI,1,,,5,Other,1287,Atlético San Luis,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [11]:
evaluacion('Liga_MX_2023_2024_America_p3.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 4041_defensive_responsibility_probability
124. 6357_defensive_responsibility_probability
125. 6794_defensive_responsibility_probability
126. 11388_defensive_responsibility_probability
127. 15822_defensive_responsibility_probability
128. 26256_defensive_responsibility_probability
129. 26400_defensive_responsibility_probability
130. 26312_defensive_responsibility_probability
131. 26369_defensive_responsibility_probability
132. 30458_defensive_responsibility_probability
133. 29518_defensive_responsibility_probability
134. 33126_defensive_responsibility_probability
135. 28530_defensive_responsibility_probability
136. 28562_defensive_responsibility_probability
137. 33097_defensive_responsibility_probability
138. 30943_defensive_responsibility_probability
139. 30500_defensive_responsibility_probability
140. 30736_defensive_responsibility_probability
141. 33098_defensive_responsibility_probability
142. 43557_defensive_responsibility_probability
143. 34581_defensive_responsibility_probability
144. 35375_defensive_responsibility_probability
145. 31956_defensive_responsibility_probability
146. 38338_defensive_responsibility_probability
147. 36167_defensive_responsibility_probability
148. 43555_defensive_responsibility_probability
149. 47467_defensive_responsibility_probability
150. 48924_defensive_responsibility_probability
151. 78280_defensive_responsibility_probability
152. 81047_defensive_responsibility_probability
153. 386286_defensive_responsibility_probability
154. 130953_defensive_responsibility_probability
155. 131189_defensive_responsibility_probability
156. 135200_defensive_responsibility_probability
157. 147337_defensive_responsibility_probability
158. 198802_defensive_responsibility_probability
159. 399870_defensive_responsibility_probability
160. 399872_defensive_responsibility_probability
161. 399874_defensive_responsibility_probability
162. 400659_defensive_responsibility_probability
163. 406131_defensive_responsibility_probability
164. 432033_defensive_responsibility_probability
165. 4041_pressure_like_defensive_responsibility_probability
166. 6357_pressure_like_defensive_responsibility_probability
167. 6794_pressure_like_defensive_responsibility_probability
168. 11388_pressure_like_defensive_responsibility_probability
169. 15822_pressure_like_defensive_responsibility_probability
170. 26256_pressure_like_defensive_responsibility_probability
171. 26400_pressure_like_defensive_responsibility_probability
172. 26312_pressure_like_defensive_responsibility_probability
173. 26369_pressure_like_defensive_responsibility_probability
174. 30458_pressure_like_defensive_responsibility_probability
175. 29518_pressure_like_defensive_responsibility_probability
176. 33126_pressure_like_defensive_responsibility_probability
177. 28530_pressure_like_defensive_responsibility_probability
178. 28562_pressure_like_defensive_responsibility_probability
179. 33097_pressure_like_defensive_responsibility_probability
180. 30943_pressure_like_defensive_responsibility_probability
181. 30500_pressure_like_defensive_responsibility_probability
182. 30736_pressure_like_defensive_responsibility_probability
183. 33098_pressure_like_defensive_responsibility_probability
184. 43557_pressure_like_defensive_responsibility_probability
185. 34581_pressure_like_defensive_responsibility_probability
186. 35375_pressure_like_defensive_responsibility_probability
187. 31956_pressure_like_defensive_responsibility_probability
188. 38338_pressure_like_defensive_responsibility_probability
189. 36167_pressure_like_defensive_responsibility_probability
190. 43555_pressure_like_defensive_responsibility_probability
191. 47467_pressure_like_defensive_responsibility_probability
192. 48924_pressure_like_defensive_responsibility_probability
193. 78280_pressure_like_defensive_responsibility_probability
194. 81047_pressure_like_defensive_responsibility_probability
195. 386286_pressure_like_defensive_responsibility_probability
196. 130953_pressure_like_defensive_responsibility_probability
197. 131189_pressure_like_defensive_responsibility_probability
198. 135200_pressure_like_defensive_responsibility_probability
199. 147337_pressure_like_defensive_responsibility_probability
200. 198802_pressure_like_defensive_responsibility_probability
201. 399870_pressure_like_defensive_responsibility_probability
202. 399872_pressure_like_defensive_responsibility_probability
203. 399874_pressure_like_defensive_responsibility_probability
204. 400659_pressure_like_defensive_responsibility_probability
205. 406131_pressure_like_defensive_responsibility_probability
206. 432033_pressure_like_defensive_responsibility_probability
207. 4041_interception_like_defensive_responsibility_probability
208. 6357_interception_like_defensive_responsibility_probability
209. 6794_interception_like_defensive_responsibility_probability
210. 11388_interception_like_defensive_responsibility_probability
211. 15822_interception_like_defensive_responsibility_probability
212. 26256_interception_like_defensive_responsibility_probability
213. 26400_interception_like_defensive_responsibility_probability
214. 26312_interception_like_defensive_responsibility_probability
215. 26369_interception_like_defensive_responsibility_probability
216. 30458_interception_like_defensive_responsibility_probability
217. 29518_interception_like_defensive_responsibility_probability
218. 33126_interception_like_defensive_responsibility_probability
219. 28530_interception_like_defensive_responsibility_probability
220. 28562_interception_like_defensive_responsibility_probability
221. 33097_interception_like_defensive_responsibility_probability
222. 30943_interception_like_defensive_responsibility_probability
223. 30500_interception_like_defensive_responsibility_probability
224. 30736_interception_like_defensive_responsibility_probability
225. 33098_interception_like_defensive_responsibility_probability
226. 43557_interception_like_defensive_responsibility_probability
227. 34581_interception_like_defensive_responsibility_probability
228. 35375_interception_like_defensive_responsibility_probability
229. 31956_interception_like_defensive_responsibility_probability
230. 38338_interception_like_defensive_responsibility_probability
231. 36167_interception_like_defensive_responsibility_probability
232. 43555_interception_like_defensive_responsibility_probability
233. 47467_interception_like_defensive_responsibility_probability
234. 48924_interception_like_defensive_responsibility_probability
235. 78280_interception_like_defensive_responsibility_probability
236. 81047_interception_like_defensive_responsibility_probability
237. 386286_interception_like_defensive_responsibility_probability
238. 130953_interception_like_defensive_responsibility_probability
239. 131189_interception_like_defensive_responsibility_probability
240. 135200_interception_like_defensive_responsibility_probability
241. 147337_interception_like_defensive_responsibility_probability
242. 198802_interception_like_defensive_responsibility_probability
243. 399870_interception_like_defensive_responsibility_probability
244. 399872_interception_like_defensive_responsibility_probability
245. 399874_interception_like_defensive_responsibility_probability
246. 400659_interception_like_defensive_responsibility_probability
247. 406131_interception_like_defensive_responsibility_probability
248. 432033_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 23,498
Partidos únicos: 6
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,4041_defensive_responsibility_probability,6357_defensive_responsibility_probability,6794_defensive_responsibility_probability,11388_defensive_responsibility_probability,15822_defensive_responsibility_probability,26256_defensive_responsibility_probability,26400_defensive_responsibility_probability,26312_defensive_responsibility_probability,26369_defensive_responsibility_probability,30458_defensive_responsibility_probability,29518_defensive_responsibility_probability,33126_defensive_responsibility_probability,28530_defensive_responsibility_probability,28562_defensive_responsibility_probability,33097_defensive_responsibility_probability,30943_defensive_responsibility_probability,30500_defensive_responsibility_probability,30736_defensive_responsibility_probability,33098_defensive_responsibility_probability,43557_defensive_responsibility_probability,34581_defensive_responsibility_probability,35375_defensive_responsibility_probability,31956_defensive_responsibility_probability,38338_defensive_responsibility_probability,36167_defensive_responsibility_probability,43555_defensive_responsibility_probability,47467_defensive_responsibility_probability,48924_defensive_responsibility_probability,78280_defensive_responsibility_probability,81047_defensive_responsibility_probability,386286_defensive_responsibility_probability,130953_defensive_responsibility_probability,131189_defensive_responsibility_probability,135200_defensive_responsibility_probability,147337_defensive_responsibility_probability,198802_defensive_responsibility_probability,399870_defensive_responsibility_probability,399872_defensive_responsibility_probability,399874_defensive_responsibility_probability,400659_defensive_responsibility_probability,406131_defensive_responsibility_probability,432033_defensive_responsibility_probability,4041_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,6794_pressure_like_defensive_responsibility_probability,11388_pressure_like_defensive_responsibility_probability,15822_pressure_like_defensive_responsibility_probability,26256_pressure_like_defensive_responsibility_probability,26400_pressure_like_defensive_responsibility_probability,26312_pressure_like_defensive_responsibility_probability,26369_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,29518_pressure_like_defensive_responsibility_probability,33126_pressure_like_defensive_responsibility_probability,28530_pressure_like_defensive_responsibility_probability,28562_pressure_like_defensive_responsibility_probability,33097_pressure_like_defensive_responsibility_probability,30943_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30736_pressure_like_defensive_responsibility_probability,33098_pressure_like_defensive_responsibility_probability,43557_pressure_like_defensive_responsibility_probability,34581_pressure_like_defensive_responsibility_probability,35375_pressure_like_defensive_responsibility_probability,31956_pressure_like_defensive_responsibility_probability,38338_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,43555_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,48924_pressure_like_defensive_responsibility_probability,78280_pressure_like_defensive_responsibility_probability,81047_pressure_like_defensive_responsibility_probability,386286_pressure_like_defensive_responsibility_probability,130953_pressure_like_defensive_responsibility_probability,131189_pressure_like_defensive_responsibility_probability,135200_pressure_like_defensive_responsibility_probability,147337_pressure_like_defensive_responsibility_probability,198802_pressure_like_defensive_responsibility_probability,399870_pressure_like_defensive_responsibility_probability,399872_pressure_like_defensive_responsibility_probability,399874_pressure_like_defensive_responsibility_probability,400659_pressure_like_defensive_responsibility_probability,406131_pressure_like_defensive_responsibility_probability,432033_pressure_like_defensive_responsibility_probability,4041_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,6794_interception_like_defensive_responsibility_probability,11388_interception_like_defensive_responsibility_probability,15822_interception_like_defensive_responsibility_probability,26256_interception_like_defensive_responsibility_probability,26400_interception_like_defensive_responsibility_probability,26312_interception_like_defensive_responsibility_probability,26369_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,29518_interception_like_defensive_responsibility_probability,33126_interception_like_defensive_responsibility_probability,28530_interception_like_defensive_responsibility_probability,28562_interception_like_defensive_responsibility_probability,33097_interception_like_defensive_responsibility_probability,30943_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30736_interception_like_defensive_responsibility_probability,33098_interception_like_defensive_responsibility_probability,43557_interception_like_defensive_responsibility_probability,34581_interception_like_defensive_responsibility_probability,35375_interception_like_defensive_responsibility_probability,31956_interception_like_defensive_responsibility_probability,38338_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,43555_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,48924_interception_like_defensive_responsibility_probability,78280_interception_like_defensive_responsibility_probability,81047_interception_like_defensive_responsibility_probability,386286_interception_like_defensive_responsibility_probability,130953_interception_like_defensive_responsibility_probability,131189_interception_like_defensive_responsibility_probability,135200_interception_like_defensive_responsibility_probability,147337_interception_like_defensive_responsibility_probability,198802_interception_like_defensive_responsibility_probability,399870_interception_like_defensive_responsibility_probability,399872_interception_like_defensive_responsibility_probability,399874_interception_like_defensive_responsibility_probability,400659_interception_like_defensive_responsibility_probability,406131_interception_like_defensive_responsibility_probability,432033_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
f3a62185-199f-54ac-ab75-e6f6dc5f9d63,1,3936617,1,00:00,0,0,35,Starting XI,1,,,5,Other,1229,América,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,right_to_left,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [12]:
evaluacion('Liga_MX_2024_2025_America_p1.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 9926_defensive_responsibility_probability
124. 45685_defensive_responsibility_probability
125. 6357_defensive_responsibility_probability
126. 11388_defensive_responsibility_probability
127. 15822_defensive_responsibility_probability
128. 26774_defensive_responsibility_probability
129. 26400_defensive_responsibility_probability
130. 26312_defensive_responsibility_probability
131. 26327_defensive_responsibility_probability
132. 30458_defensive_responsibility_probability
133. 28522_defensive_responsibility_probability
134. 28160_defensive_responsibility_probability
135. 29424_defensive_responsibility_probability
136. 29269_defensive_responsibility_probability
137. 29702_defensive_responsibility_probability
138. 31050_defensive_responsibility_probability
139. 43557_defensive_responsibility_probability
140. 31312_defensive_responsibility_probability
141. 31462_defensive_responsibility_probability
142. 31956_defensive_responsibility_probability
143. 41777_defensive_responsibility_probability
144. 36167_defensive_responsibility_probability
145. 35953_defensive_responsibility_probability
146. 43555_defensive_responsibility_probability
147. 107179_defensive_responsibility_probability
148. 46322_defensive_responsibility_probability
149. 47467_defensive_responsibility_probability
150. 47892_defensive_responsibility_probability
151. 50461_defensive_responsibility_probability
152. 131123_defensive_responsibility_probability
153. 131320_defensive_responsibility_probability
154. 187178_defensive_responsibility_probability
155. 226626_defensive_responsibility_probability
156. 271974_defensive_responsibility_probability
157. 275827_defensive_responsibility_probability
158. 281091_defensive_responsibility_probability
159. 359504_defensive_responsibility_probability
160. 399871_defensive_responsibility_probability
161. 415002_defensive_responsibility_probability
162. 436700_defensive_responsibility_probability
163. 436701_defensive_responsibility_probability
164. 436702_defensive_responsibility_probability
165. 9926_pressure_like_defensive_responsibility_probability
166. 45685_pressure_like_defensive_responsibility_probability
167. 6357_pressure_like_defensive_responsibility_probability
168. 11388_pressure_like_defensive_responsibility_probability
169. 15822_pressure_like_defensive_responsibility_probability
170. 26774_pressure_like_defensive_responsibility_probability
171. 26400_pressure_like_defensive_responsibility_probability
172. 26312_pressure_like_defensive_responsibility_probability
173. 26327_pressure_like_defensive_responsibility_probability
174. 30458_pressure_like_defensive_responsibility_probability
175. 28522_pressure_like_defensive_responsibility_probability
176. 28160_pressure_like_defensive_responsibility_probability
177. 29424_pressure_like_defensive_responsibility_probability
178. 29269_pressure_like_defensive_responsibility_probability
179. 29702_pressure_like_defensive_responsibility_probability
180. 31050_pressure_like_defensive_responsibility_probability
181. 43557_pressure_like_defensive_responsibility_probability
182. 31312_pressure_like_defensive_responsibility_probability
183. 31462_pressure_like_defensive_responsibility_probability
184. 31956_pressure_like_defensive_responsibility_probability
185. 41777_pressure_like_defensive_responsibility_probability
186. 36167_pressure_like_defensive_responsibility_probability
187. 35953_pressure_like_defensive_responsibility_probability
188. 43555_pressure_like_defensive_responsibility_probability
189. 107179_pressure_like_defensive_responsibility_probability
190. 46322_pressure_like_defensive_responsibility_probability
191. 47467_pressure_like_defensive_responsibility_probability
192. 47892_pressure_like_defensive_responsibility_probability
193. 50461_pressure_like_defensive_responsibility_probability
194. 131123_pressure_like_defensive_responsibility_probability
195. 131320_pressure_like_defensive_responsibility_probability
196. 187178_pressure_like_defensive_responsibility_probability
197. 226626_pressure_like_defensive_responsibility_probability
198. 271974_pressure_like_defensive_responsibility_probability
199. 275827_pressure_like_defensive_responsibility_probability
200. 281091_pressure_like_defensive_responsibility_probability
201. 359504_pressure_like_defensive_responsibility_probability
202. 399871_pressure_like_defensive_responsibility_probability
203. 415002_pressure_like_defensive_responsibility_probability
204. 436700_pressure_like_defensive_responsibility_probability
205. 436701_pressure_like_defensive_responsibility_probability
206. 436702_pressure_like_defensive_responsibility_probability
207. 9926_interception_like_defensive_responsibility_probability
208. 45685_interception_like_defensive_responsibility_probability
209. 6357_interception_like_defensive_responsibility_probability
210. 11388_interception_like_defensive_responsibility_probability
211. 15822_interception_like_defensive_responsibility_probability
212. 26774_interception_like_defensive_responsibility_probability
213. 26400_interception_like_defensive_responsibility_probability
214. 26312_interception_like_defensive_responsibility_probability
215. 26327_interception_like_defensive_responsibility_probability
216. 30458_interception_like_defensive_responsibility_probability
217. 28522_interception_like_defensive_responsibility_probability
218. 28160_interception_like_defensive_responsibility_probability
219. 29424_interception_like_defensive_responsibility_probability
220. 29269_interception_like_defensive_responsibility_probability
221. 29702_interception_like_defensive_responsibility_probability
222. 31050_interception_like_defensive_responsibility_probability
223. 43557_interception_like_defensive_responsibility_probability
224. 31312_interception_like_defensive_responsibility_probability
225. 31462_interception_like_defensive_responsibility_probability
226. 31956_interception_like_defensive_responsibility_probability
227. 41777_interception_like_defensive_responsibility_probability
228. 36167_interception_like_defensive_responsibility_probability
229. 35953_interception_like_defensive_responsibility_probability
230. 43555_interception_like_defensive_responsibility_probability
231. 107179_interception_like_defensive_responsibility_probability
232. 46322_interception_like_defensive_responsibility_probability
233. 47467_interception_like_defensive_responsibility_probability
234. 47892_interception_like_defensive_responsibility_probability
235. 50461_interception_like_defensive_responsibility_probability
236. 131123_interception_like_defensive_responsibility_probability
237. 131320_interception_like_defensive_responsibility_probability
238. 187178_interception_like_defensive_responsibility_probability
239. 226626_interception_like_defensive_responsibility_probability
240. 271974_interception_like_defensive_responsibility_probability
241. 275827_interception_like_defensive_responsibility_probability
242. 281091_interception_like_defensive_responsibility_probability
243. 359504_interception_like_defensive_responsibility_probability
244. 399871_interception_like_defensive_responsibility_probability
245. 415002_interception_like_defensive_responsibility_probability
246. 436700_interception_like_defensive_responsibility_probability
247. 436701_interception_like_defensive_responsibility_probability
248. 436702_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 75,700
Partidos únicos: 20
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,9926_defensive_responsibility_probability,45685_defensive_responsibility_probability,6357_defensive_responsibility_probability,11388_defensive_responsibility_probability,15822_defensive_responsibility_probability,26774_defensive_responsibility_probability,26400_defensive_responsibility_probability,26312_defensive_responsibility_probability,26327_defensive_responsibility_probability,30458_defensive_responsibility_probability,28522_defensive_responsibility_probability,28160_defensive_responsibility_probability,29424_defensive_responsibility_probability,29269_defensive_responsibility_probability,29702_defensive_responsibility_probability,31050_defensive_responsibility_probability,43557_defensive_responsibility_probability,31312_defensive_responsibility_probability,31462_defensive_responsibility_probability,31956_defensive_responsibility_probability,41777_defensive_responsibility_probability,36167_defensive_responsibility_probability,35953_defensive_responsibility_probability,43555_defensive_responsibility_probability,107179_defensive_responsibility_probability,46322_defensive_responsibility_probability,47467_defensive_responsibility_probability,47892_defensive_responsibility_probability,50461_defensive_responsibility_probability,131123_defensive_responsibility_probability,131320_defensive_responsibility_probability,187178_defensive_responsibility_probability,226626_defensive_responsibility_probability,271974_defensive_responsibility_probability,275827_defensive_responsibility_probability,281091_defensive_responsibility_probability,359504_defensive_responsibility_probability,399871_defensive_responsibility_probability,415002_defensive_responsibility_probability,436700_defensive_responsibility_probability,436701_defensive_responsibility_probability,436702_defensive_responsibility_probability,9926_pressure_like_defensive_responsibility_probability,45685_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,11388_pressure_like_defensive_responsibility_probability,15822_pressure_like_defensive_responsibility_probability,26774_pressure_like_defensive_responsibility_probability,26400_pressure_like_defensive_responsibility_probability,26312_pressure_like_defensive_responsibility_probability,26327_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,28522_pressure_like_defensive_responsibility_probability,28160_pressure_like_defensive_responsibility_probability,29424_pressure_like_defensive_responsibility_probability,29269_pressure_like_defensive_responsibility_probability,29702_pressure_like_defensive_responsibility_probability,31050_pressure_like_defensive_responsibility_probability,43557_pressure_like_defensive_responsibility_probability,31312_pressure_like_defensive_responsibility_probability,31462_pressure_like_defensive_responsibility_probability,31956_pressure_like_defensive_responsibility_probability,41777_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,35953_pressure_like_defensive_responsibility_probability,43555_pressure_like_defensive_responsibility_probability,107179_pressure_like_defensive_responsibility_probability,46322_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,47892_pressure_like_defensive_responsibility_probability,50461_pressure_like_defensive_responsibility_probability,131123_pressure_like_defensive_responsibility_probability,131320_pressure_like_defensive_responsibility_probability,187178_pressure_like_defensive_responsibility_probability,226626_pressure_like_defensive_responsibility_probability,271974_pressure_like_defensive_responsibility_probability,275827_pressure_like_defensive_responsibility_probability,281091_pressure_like_defensive_responsibility_probability,359504_pressure_like_defensive_responsibility_probability,399871_pressure_like_defensive_responsibility_probability,415002_pressure_like_defensive_responsibility_probability,436700_pressure_like_defensive_responsibility_probability,436701_pressure_like_defensive_responsibility_probability,436702_pressure_like_defensive_responsibility_probability,9926_interception_like_defensive_responsibility_probability,45685_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,11388_interception_like_defensive_responsibility_probability,15822_interception_like_defensive_responsibility_probability,26774_interception_like_defensive_responsibility_probability,26400_interception_like_defensive_responsibility_probability,26312_interception_like_defensive_responsibility_probability,26327_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,28522_interception_like_defensive_responsibility_probability,28160_interception_like_defensive_responsibility_probability,29424_interception_like_defensive_responsibility_probability,29269_interception_like_defensive_responsibility_probability,29702_interception_like_defensive_responsibility_probability,31050_interception_like_defensive_responsibility_probability,43557_interception_like_defensive_responsibility_probability,31312_interception_like_defensive_responsibility_probability,31462_interception_like_defensive_responsibility_probability,31956_interception_like_defensive_responsibility_probability,41777_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,35953_interception_like_defensive_responsibility_probability,43555_interception_like_defensive_responsibility_probability,107179_interception_like_defensive_responsibility_probability,46322_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,47892_interception_like_defensive_responsibility_probability,50461_interception_like_defensive_responsibility_probability,131123_interception_like_defensive_responsibility_probability,131320_interception_like_defensive_responsibility_probability,187178_interception_like_defensive_responsibility_probability,226626_interception_like_defensive_responsibility_probability,271974_interception_like_defensive_responsibility_probability,275827_interception_like_defensive_responsibility_probability,281091_interception_like_defensive_responsibility_probability,359504_interception_like_defensive_responsibility_probability,399871_interception_like_defensive_responsibility_probability,415002_interception_like_defensive_responsibility_probability,436700_interception_like_defensive_responsibility_probability,436701_interception_like_defensive_responsibility_probability,436702_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
a4caf686-994f-5a0f-855e-16354a26cb05,1,3939819,1,00:00,0,0,35,Starting XI,1,,,5,Other,1229,América,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [13]:
evaluacion('Liga_MX_2024_2025_America_p2.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 6357_defensive_responsibility_probability
124. 11388_defensive_responsibility_probability
125. 15822_defensive_responsibility_probability
126. 16050_defensive_responsibility_probability
127. 23428_defensive_responsibility_probability
128. 26406_defensive_responsibility_probability
129. 26400_defensive_responsibility_probability
130. 26297_defensive_responsibility_probability
131. 26403_defensive_responsibility_probability
132. 26312_defensive_responsibility_probability
133. 26353_defensive_responsibility_probability
134. 26386_defensive_responsibility_probability
135. 27174_defensive_responsibility_probability
136. 78134_defensive_responsibility_probability
137. 30458_defensive_responsibility_probability
138. 28522_defensive_responsibility_probability
139. 33126_defensive_responsibility_probability
140. 28538_defensive_responsibility_probability
141. 28873_defensive_responsibility_probability
142. 28894_defensive_responsibility_probability
143. 29265_defensive_responsibility_probability
144. 36935_defensive_responsibility_probability
145. 30294_defensive_responsibility_probability
146. 30500_defensive_responsibility_probability
147. 30736_defensive_responsibility_probability
148. 30944_defensive_responsibility_probability
149. 33098_defensive_responsibility_probability
150. 43319_defensive_responsibility_probability
151. 35856_defensive_responsibility_probability
152. 34349_defensive_responsibility_probability
153. 31956_defensive_responsibility_probability
154. 37722_defensive_responsibility_probability
155. 36167_defensive_responsibility_probability
156. 37362_defensive_responsibility_probability
157. 37999_defensive_responsibility_probability
158. 43555_defensive_responsibility_probability
159. 43622_defensive_responsibility_probability
160. 47467_defensive_responsibility_probability
161. 131189_defensive_responsibility_probability
162. 208278_defensive_responsibility_probability
163. 337757_defensive_responsibility_probability
164. 403897_defensive_responsibility_probability
165. 6357_pressure_like_defensive_responsibility_probability
166. 11388_pressure_like_defensive_responsibility_probability
167. 15822_pressure_like_defensive_responsibility_probability
168. 16050_pressure_like_defensive_responsibility_probability
169. 23428_pressure_like_defensive_responsibility_probability
170. 26406_pressure_like_defensive_responsibility_probability
171. 26400_pressure_like_defensive_responsibility_probability
172. 26297_pressure_like_defensive_responsibility_probability
173. 26403_pressure_like_defensive_responsibility_probability
174. 26312_pressure_like_defensive_responsibility_probability
175. 26353_pressure_like_defensive_responsibility_probability
176. 26386_pressure_like_defensive_responsibility_probability
177. 27174_pressure_like_defensive_responsibility_probability
178. 78134_pressure_like_defensive_responsibility_probability
179. 30458_pressure_like_defensive_responsibility_probability
180. 28522_pressure_like_defensive_responsibility_probability
181. 33126_pressure_like_defensive_responsibility_probability
182. 28538_pressure_like_defensive_responsibility_probability
183. 28873_pressure_like_defensive_responsibility_probability
184. 28894_pressure_like_defensive_responsibility_probability
185. 29265_pressure_like_defensive_responsibility_probability
186. 36935_pressure_like_defensive_responsibility_probability
187. 30294_pressure_like_defensive_responsibility_probability
188. 30500_pressure_like_defensive_responsibility_probability
189. 30736_pressure_like_defensive_responsibility_probability
190. 30944_pressure_like_defensive_responsibility_probability
191. 33098_pressure_like_defensive_responsibility_probability
192. 43319_pressure_like_defensive_responsibility_probability
193. 35856_pressure_like_defensive_responsibility_probability
194. 34349_pressure_like_defensive_responsibility_probability
195. 31956_pressure_like_defensive_responsibility_probability
196. 37722_pressure_like_defensive_responsibility_probability
197. 36167_pressure_like_defensive_responsibility_probability
198. 37362_pressure_like_defensive_responsibility_probability
199. 37999_pressure_like_defensive_responsibility_probability
200. 43555_pressure_like_defensive_responsibility_probability
201. 43622_pressure_like_defensive_responsibility_probability
202. 47467_pressure_like_defensive_responsibility_probability
203. 131189_pressure_like_defensive_responsibility_probability
204. 208278_pressure_like_defensive_responsibility_probability
205. 337757_pressure_like_defensive_responsibility_probability
206. 403897_pressure_like_defensive_responsibility_probability
207. 6357_interception_like_defensive_responsibility_probability
208. 11388_interception_like_defensive_responsibility_probability
209. 15822_interception_like_defensive_responsibility_probability
210. 16050_interception_like_defensive_responsibility_probability
211. 23428_interception_like_defensive_responsibility_probability
212. 26406_interception_like_defensive_responsibility_probability
213. 26400_interception_like_defensive_responsibility_probability
214. 26297_interception_like_defensive_responsibility_probability
215. 26403_interception_like_defensive_responsibility_probability
216. 26312_interception_like_defensive_responsibility_probability
217. 26353_interception_like_defensive_responsibility_probability
218. 26386_interception_like_defensive_responsibility_probability
219. 27174_interception_like_defensive_responsibility_probability
220. 78134_interception_like_defensive_responsibility_probability
221. 30458_interception_like_defensive_responsibility_probability
222. 28522_interception_like_defensive_responsibility_probability
223. 33126_interception_like_defensive_responsibility_probability
224. 28538_interception_like_defensive_responsibility_probability
225. 28873_interception_like_defensive_responsibility_probability
226. 28894_interception_like_defensive_responsibility_probability
227. 29265_interception_like_defensive_responsibility_probability
228. 36935_interception_like_defensive_responsibility_probability
229. 30294_interception_like_defensive_responsibility_probability
230. 30500_interception_like_defensive_responsibility_probability
231. 30736_interception_like_defensive_responsibility_probability
232. 30944_interception_like_defensive_responsibility_probability
233. 33098_interception_like_defensive_responsibility_probability
234. 43319_interception_like_defensive_responsibility_probability
235. 35856_interception_like_defensive_responsibility_probability
236. 34349_interception_like_defensive_responsibility_probability
237. 31956_interception_like_defensive_responsibility_probability
238. 37722_interception_like_defensive_responsibility_probability
239. 36167_interception_like_defensive_responsibility_probability
240. 37362_interception_like_defensive_responsibility_probability
241. 37999_interception_like_defensive_responsibility_probability
242. 43555_interception_like_defensive_responsibility_probability
243. 43622_interception_like_defensive_responsibility_probability
244. 47467_interception_like_defensive_responsibility_probability
245. 131189_interception_like_defensive_responsibility_probability
246. 208278_interception_like_defensive_responsibility_probability
247. 337757_interception_like_defensive_responsibility_probability
248. 403897_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 76,708
Partidos únicos: 20
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,6357_defensive_responsibility_probability,11388_defensive_responsibility_probability,15822_defensive_responsibility_probability,16050_defensive_responsibility_probability,23428_defensive_responsibility_probability,26406_defensive_responsibility_probability,26400_defensive_responsibility_probability,26297_defensive_responsibility_probability,26403_defensive_responsibility_probability,26312_defensive_responsibility_probability,26353_defensive_responsibility_probability,26386_defensive_responsibility_probability,27174_defensive_responsibility_probability,78134_defensive_responsibility_probability,30458_defensive_responsibility_probability,28522_defensive_responsibility_probability,33126_defensive_responsibility_probability,28538_defensive_responsibility_probability,28873_defensive_responsibility_probability,28894_defensive_responsibility_probability,29265_defensive_responsibility_probability,36935_defensive_responsibility_probability,30294_defensive_responsibility_probability,30500_defensive_responsibility_probability,30736_defensive_responsibility_probability,30944_defensive_responsibility_probability,33098_defensive_responsibility_probability,43319_defensive_responsibility_probability,35856_defensive_responsibility_probability,34349_defensive_responsibility_probability,31956_defensive_responsibility_probability,37722_defensive_responsibility_probability,36167_defensive_responsibility_probability,37362_defensive_responsibility_probability,37999_defensive_responsibility_probability,43555_defensive_responsibility_probability,43622_defensive_responsibility_probability,47467_defensive_responsibility_probability,131189_defensive_responsibility_probability,208278_defensive_responsibility_probability,337757_defensive_responsibility_probability,403897_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,11388_pressure_like_defensive_responsibility_probability,15822_pressure_like_defensive_responsibility_probability,16050_pressure_like_defensive_responsibility_probability,23428_pressure_like_defensive_responsibility_probability,26406_pressure_like_defensive_responsibility_probability,26400_pressure_like_defensive_responsibility_probability,26297_pressure_like_defensive_responsibility_probability,26403_pressure_like_defensive_responsibility_probability,26312_pressure_like_defensive_responsibility_probability,26353_pressure_like_defensive_responsibility_probability,26386_pressure_like_defensive_responsibility_probability,27174_pressure_like_defensive_responsibility_probability,78134_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,28522_pressure_like_defensive_responsibility_probability,33126_pressure_like_defensive_responsibility_probability,28538_pressure_like_defensive_responsibility_probability,28873_pressure_like_defensive_responsibility_probability,28894_pressure_like_defensive_responsibility_probability,29265_pressure_like_defensive_responsibility_probability,36935_pressure_like_defensive_responsibility_probability,30294_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30736_pressure_like_defensive_responsibility_probability,30944_pressure_like_defensive_responsibility_probability,33098_pressure_like_defensive_responsibility_probability,43319_pressure_like_defensive_responsibility_probability,35856_pressure_like_defensive_responsibility_probability,34349_pressure_like_defensive_responsibility_probability,31956_pressure_like_defensive_responsibility_probability,37722_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,37362_pressure_like_defensive_responsibility_probability,37999_pressure_like_defensive_responsibility_probability,43555_pressure_like_defensive_responsibility_probability,43622_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,131189_pressure_like_defensive_responsibility_probability,208278_pressure_like_defensive_responsibility_probability,337757_pressure_like_defensive_responsibility_probability,403897_pressure_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,11388_interception_like_defensive_responsibility_probability,15822_interception_like_defensive_responsibility_probability,16050_interception_like_defensive_responsibility_probability,23428_interception_like_defensive_responsibility_probability,26406_interception_like_defensive_responsibility_probability,26400_interception_like_defensive_responsibility_probability,26297_interception_like_defensive_responsibility_probability,26403_interception_like_defensive_responsibility_probability,26312_interception_like_defensive_responsibility_probability,26353_interception_like_defensive_responsibility_probability,26386_interception_like_defensive_responsibility_probability,27174_interception_like_defensive_responsibility_probability,78134_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,28522_interception_like_defensive_responsibility_probability,33126_interception_like_defensive_responsibility_probability,28538_interception_like_defensive_responsibility_probability,28873_interception_like_defensive_responsibility_probability,28894_interception_like_defensive_responsibility_probability,29265_interception_like_defensive_responsibility_probability,36935_interception_like_defensive_responsibility_probability,30294_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30736_interception_like_defensive_responsibility_probability,30944_interception_like_defensive_responsibility_probability,33098_interception_like_defensive_responsibility_probability,43319_interception_like_defensive_responsibility_probability,35856_interception_like_defensive_responsibility_probability,34349_interception_like_defensive_responsibility_probability,31956_interception_like_defensive_responsibility_probability,37722_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,37362_interception_like_defensive_responsibility_probability,37999_interception_like_defensive_responsibility_probability,43555_interception_like_defensive_responsibility_probability,43622_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,131189_interception_like_defensive_responsibility_probability,208278_interception_like_defensive_responsibility_probability,337757_interception_like_defensive_responsibility_probability,403897_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
5a0977ff-0a65-5634-a449-a666379b855d,1,3970307,1,00:00,0,0,35,Starting XI,1,,,5,Other,1224,Cruz Azul,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [14]:
evaluacion('Liga_MX_2024_2025_America_p3.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 15822_defensive_responsibility_probability
124. 23428_defensive_responsibility_probability
125. 49982_defensive_responsibility_probability
126. 26273_defensive_responsibility_probability
127. 26303_defensive_responsibility_probability
128. 26312_defensive_responsibility_probability
129. 37359_defensive_responsibility_probability
130. 26361_defensive_responsibility_probability
131. 27356_defensive_responsibility_probability
132. 30458_defensive_responsibility_probability
133. 28522_defensive_responsibility_probability
134. 33126_defensive_responsibility_probability
135. 28560_defensive_responsibility_probability
136. 31975_defensive_responsibility_probability
137. 30500_defensive_responsibility_probability
138. 30846_defensive_responsibility_probability
139. 30944_defensive_responsibility_probability
140. 33098_defensive_responsibility_probability
141. 31044_defensive_responsibility_probability
142. 36134_defensive_responsibility_probability
143. 33113_defensive_responsibility_probability
144. 36167_defensive_responsibility_probability
145. 43477_defensive_responsibility_probability
146. 35690_defensive_responsibility_probability
147. 37999_defensive_responsibility_probability
148. 43330_defensive_responsibility_probability
149. 43555_defensive_responsibility_probability
150. 46322_defensive_responsibility_probability
151. 47467_defensive_responsibility_probability
152. 50551_defensive_responsibility_probability
153. 92574_defensive_responsibility_probability
154. 391381_defensive_responsibility_probability
155. 337757_defensive_responsibility_probability
156. 360975_defensive_responsibility_probability
157. 370171_defensive_responsibility_probability
158. 392141_defensive_responsibility_probability
159. 415002_defensive_responsibility_probability
160. 423845_defensive_responsibility_probability
161. 436702_defensive_responsibility_probability
162. 458387_defensive_responsibility_probability
163. 458388_defensive_responsibility_probability
164. 459663_defensive_responsibility_probability
165. 15822_pressure_like_defensive_responsibility_probability
166. 23428_pressure_like_defensive_responsibility_probability
167. 49982_pressure_like_defensive_responsibility_probability
168. 26273_pressure_like_defensive_responsibility_probability
169. 26303_pressure_like_defensive_responsibility_probability
170. 26312_pressure_like_defensive_responsibility_probability
171. 37359_pressure_like_defensive_responsibility_probability
172. 26361_pressure_like_defensive_responsibility_probability
173. 27356_pressure_like_defensive_responsibility_probability
174. 30458_pressure_like_defensive_responsibility_probability
175. 28522_pressure_like_defensive_responsibility_probability
176. 33126_pressure_like_defensive_responsibility_probability
177. 28560_pressure_like_defensive_responsibility_probability
178. 31975_pressure_like_defensive_responsibility_probability
179. 30500_pressure_like_defensive_responsibility_probability
180. 30846_pressure_like_defensive_responsibility_probability
181. 30944_pressure_like_defensive_responsibility_probability
182. 33098_pressure_like_defensive_responsibility_probability
183. 31044_pressure_like_defensive_responsibility_probability
184. 36134_pressure_like_defensive_responsibility_probability
185. 33113_pressure_like_defensive_responsibility_probability
186. 36167_pressure_like_defensive_responsibility_probability
187. 43477_pressure_like_defensive_responsibility_probability
188. 35690_pressure_like_defensive_responsibility_probability
189. 37999_pressure_like_defensive_responsibility_probability
190. 43330_pressure_like_defensive_responsibility_probability
191. 43555_pressure_like_defensive_responsibility_probability
192. 46322_pressure_like_defensive_responsibility_probability
193. 47467_pressure_like_defensive_responsibility_probability
194. 50551_pressure_like_defensive_responsibility_probability
195. 92574_pressure_like_defensive_responsibility_probability
196. 391381_pressure_like_defensive_responsibility_probability
197. 337757_pressure_like_defensive_responsibility_probability
198. 360975_pressure_like_defensive_responsibility_probability
199. 370171_pressure_like_defensive_responsibility_probability
200. 392141_pressure_like_defensive_responsibility_probability
201. 415002_pressure_like_defensive_responsibility_probability
202. 423845_pressure_like_defensive_responsibility_probability
203. 436702_pressure_like_defensive_responsibility_probability
204. 458387_pressure_like_defensive_responsibility_probability
205. 458388_pressure_like_defensive_responsibility_probability
206. 459663_pressure_like_defensive_responsibility_probability
207. 15822_interception_like_defensive_responsibility_probability
208. 23428_interception_like_defensive_responsibility_probability
209. 49982_interception_like_defensive_responsibility_probability
210. 26273_interception_like_defensive_responsibility_probability
211. 26303_interception_like_defensive_responsibility_probability
212. 26312_interception_like_defensive_responsibility_probability
213. 37359_interception_like_defensive_responsibility_probability
214. 26361_interception_like_defensive_responsibility_probability
215. 27356_interception_like_defensive_responsibility_probability
216. 30458_interception_like_defensive_responsibility_probability
217. 28522_interception_like_defensive_responsibility_probability
218. 33126_interception_like_defensive_responsibility_probability
219. 28560_interception_like_defensive_responsibility_probability
220. 31975_interception_like_defensive_responsibility_probability
221. 30500_interception_like_defensive_responsibility_probability
222. 30846_interception_like_defensive_responsibility_probability
223. 30944_interception_like_defensive_responsibility_probability
224. 33098_interception_like_defensive_responsibility_probability
225. 31044_interception_like_defensive_responsibility_probability
226. 36134_interception_like_defensive_responsibility_probability
227. 33113_interception_like_defensive_responsibility_probability
228. 36167_interception_like_defensive_responsibility_probability
229. 43477_interception_like_defensive_responsibility_probability
230. 35690_interception_like_defensive_responsibility_probability
231. 37999_interception_like_defensive_responsibility_probability
232. 43330_interception_like_defensive_responsibility_probability
233. 43555_interception_like_defensive_responsibility_probability
234. 46322_interception_like_defensive_responsibility_probability
235. 47467_interception_like_defensive_responsibility_probability
236. 50551_interception_like_defensive_responsibility_probability
237. 92574_interception_like_defensive_responsibility_probability
238. 391381_interception_like_defensive_responsibility_probability
239. 337757_interception_like_defensive_responsibility_probability
240. 360975_interception_like_defensive_responsibility_probability
241. 370171_interception_like_defensive_responsibility_probability
242. 392141_interception_like_defensive_responsibility_probability
243. 415002_interception_like_defensive_responsibility_probability
244. 423845_interception_like_defensive_responsibility_probability
245. 436702_interception_like_defensive_responsibility_probability
246. 458387_interception_like_defensive_responsibility_probability
247. 458388_interception_like_defensive_responsibility_probability
248. 459663_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 24,582
Partidos únicos: 7
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,15822_defensive_responsibility_probability,23428_defensive_responsibility_probability,49982_defensive_responsibility_probability,26273_defensive_responsibility_probability,26303_defensive_responsibility_probability,26312_defensive_responsibility_probability,37359_defensive_responsibility_probability,26361_defensive_responsibility_probability,27356_defensive_responsibility_probability,30458_defensive_responsibility_probability,28522_defensive_responsibility_probability,33126_defensive_responsibility_probability,28560_defensive_responsibility_probability,31975_defensive_responsibility_probability,30500_defensive_responsibility_probability,30846_defensive_responsibility_probability,30944_defensive_responsibility_probability,33098_defensive_responsibility_probability,31044_defensive_responsibility_probability,36134_defensive_responsibility_probability,33113_defensive_responsibility_probability,36167_defensive_responsibility_probability,43477_defensive_responsibility_probability,35690_defensive_responsibility_probability,37999_defensive_responsibility_probability,43330_defensive_responsibility_probability,43555_defensive_responsibility_probability,46322_defensive_responsibility_probability,47467_defensive_responsibility_probability,50551_defensive_responsibility_probability,92574_defensive_responsibility_probability,391381_defensive_responsibility_probability,337757_defensive_responsibility_probability,360975_defensive_responsibility_probability,370171_defensive_responsibility_probability,392141_defensive_responsibility_probability,415002_defensive_responsibility_probability,423845_defensive_responsibility_probability,436702_defensive_responsibility_probability,458387_defensive_responsibility_probability,458388_defensive_responsibility_probability,459663_defensive_responsibility_probability,15822_pressure_like_defensive_responsibility_probability,23428_pressure_like_defensive_responsibility_probability,49982_pressure_like_defensive_responsibility_probability,26273_pressure_like_defensive_responsibility_probability,26303_pressure_like_defensive_responsibility_probability,26312_pressure_like_defensive_responsibility_probability,37359_pressure_like_defensive_responsibility_probability,26361_pressure_like_defensive_responsibility_probability,27356_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,28522_pressure_like_defensive_responsibility_probability,33126_pressure_like_defensive_responsibility_probability,28560_pressure_like_defensive_responsibility_probability,31975_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30846_pressure_like_defensive_responsibility_probability,30944_pressure_like_defensive_responsibility_probability,33098_pressure_like_defensive_responsibility_probability,31044_pressure_like_defensive_responsibility_probability,36134_pressure_like_defensive_responsibility_probability,33113_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,43477_pressure_like_defensive_responsibility_probability,35690_pressure_like_defensive_responsibility_probability,37999_pressure_like_defensive_responsibility_probability,43330_pressure_like_defensive_responsibility_probability,43555_pressure_like_defensive_responsibility_probability,46322_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,50551_pressure_like_defensive_responsibility_probability,92574_pressure_like_defensive_responsibility_probability,391381_pressure_like_defensive_responsibility_probability,337757_pressure_like_defensive_responsibility_probability,360975_pressure_like_defensive_responsibility_probability,370171_pressure_like_defensive_responsibility_probability,392141_pressure_like_defensive_responsibility_probability,415002_pressure_like_defensive_responsibility_probability,423845_pressure_like_defensive_responsibility_probability,436702_pressure_like_defensive_responsibility_probability,458387_pressure_like_defensive_responsibility_probability,458388_pressure_like_defensive_responsibility_probability,459663_pressure_like_defensive_responsibility_probability,15822_interception_like_defensive_responsibility_probability,23428_interception_like_defensive_responsibility_probability,49982_interception_like_defensive_responsibility_probability,26273_interception_like_defensive_responsibility_probability,26303_interception_like_defensive_responsibility_probability,26312_interception_like_defensive_responsibility_probability,37359_interception_like_defensive_responsibility_probability,26361_interception_like_defensive_responsibility_probability,27356_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,28522_interception_like_defensive_responsibility_probability,33126_interception_like_defensive_responsibility_probability,28560_interception_like_defensive_responsibility_probability,31975_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30846_interception_like_defensive_responsibility_probability,30944_interception_like_defensive_responsibility_probability,33098_interception_like_defensive_responsibility_probability,31044_interception_like_defensive_responsibility_probability,36134_interception_like_defensive_responsibility_probability,33113_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,43477_interception_like_defensive_responsibility_probability,35690_interception_like_defensive_responsibility_probability,37999_interception_like_defensive_responsibility_probability,43330_interception_like_defensive_responsibility_probability,43555_interception_like_defensive_responsibility_probability,46322_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,50551_interception_like_defensive_responsibility_probability,92574_interception_like_defensive_responsibility_probability,391381_interception_like_defensive_responsibility_probability,337757_interception_like_defensive_responsibility_probability,360975_interception_like_defensive_responsibility_probability,370171_interception_like_defensive_responsibility_probability,392141_interception_like_defensive_responsibility_probability,415002_interception_like_defensive_responsibility_probability,423845_interception_like_defensive_responsibility_probability,436702_interception_like_defensive_responsibility_probability,458387_interception_like_defensive_responsibility_probability,458388_interception_like_defensive_responsibility_probability,459663_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
e152cb6e-28cd-565c-8900-4ef217c98392,1,3972162,1,00:00,0,0,35,Starting XI,1,,,5,Other,2773,Mazatlán,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,right_to_left,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [15]:
evaluacion('Liga_MX_2025_2026_America_p1.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 5628_defensive_responsibility_probability
124. 6357_defensive_responsibility_probability
125. 23428_defensive_responsibility_probability
126. 26256_defensive_responsibility_probability
127. 26267_defensive_responsibility_probability
128. 26273_defensive_responsibility_probability
129. 26278_defensive_responsibility_probability
130. 26311_defensive_responsibility_probability
131. 30458_defensive_responsibility_probability
132. 27902_defensive_responsibility_probability
133. 28522_defensive_responsibility_probability
134. 29265_defensive_responsibility_probability
135. 30500_defensive_responsibility_probability
136. 30736_defensive_responsibility_probability
137. 30944_defensive_responsibility_probability
138. 34349_defensive_responsibility_probability
139. 32728_defensive_responsibility_probability
140. 42479_defensive_responsibility_probability
141. 42481_defensive_responsibility_probability
142. 36167_defensive_responsibility_probability
143. 35690_defensive_responsibility_probability
144. 37999_defensive_responsibility_probability
145. 43555_defensive_responsibility_probability
146. 47172_defensive_responsibility_probability
147. 47467_defensive_responsibility_probability
148. 48870_defensive_responsibility_probability
149. 50763_defensive_responsibility_probability
150. 132471_defensive_responsibility_probability
151. 220794_defensive_responsibility_probability
152. 330534_defensive_responsibility_probability
153. 337757_defensive_responsibility_probability
154. 365523_defensive_responsibility_probability
155. 367155_defensive_responsibility_probability
156. 368582_defensive_responsibility_probability
157. 399838_defensive_responsibility_probability
158. 401174_defensive_responsibility_probability
159. 415002_defensive_responsibility_probability
160. 416843_defensive_responsibility_probability
161. 422652_defensive_responsibility_probability
162. 436669_defensive_responsibility_probability
163. 474814_defensive_responsibility_probability
164. 482768_defensive_responsibility_probability
165. 5628_pressure_like_defensive_responsibility_probability
166. 6357_pressure_like_defensive_responsibility_probability
167. 23428_pressure_like_defensive_responsibility_probability
168. 26256_pressure_like_defensive_responsibility_probability
169. 26267_pressure_like_defensive_responsibility_probability
170. 26273_pressure_like_defensive_responsibility_probability
171. 26278_pressure_like_defensive_responsibility_probability
172. 26311_pressure_like_defensive_responsibility_probability
173. 30458_pressure_like_defensive_responsibility_probability
174. 27902_pressure_like_defensive_responsibility_probability
175. 28522_pressure_like_defensive_responsibility_probability
176. 29265_pressure_like_defensive_responsibility_probability
177. 30500_pressure_like_defensive_responsibility_probability
178. 30736_pressure_like_defensive_responsibility_probability
179. 30944_pressure_like_defensive_responsibility_probability
180. 34349_pressure_like_defensive_responsibility_probability
181. 32728_pressure_like_defensive_responsibility_probability
182. 42479_pressure_like_defensive_responsibility_probability
183. 42481_pressure_like_defensive_responsibility_probability
184. 36167_pressure_like_defensive_responsibility_probability
185. 35690_pressure_like_defensive_responsibility_probability
186. 37999_pressure_like_defensive_responsibility_probability
187. 43555_pressure_like_defensive_responsibility_probability
188. 47172_pressure_like_defensive_responsibility_probability
189. 47467_pressure_like_defensive_responsibility_probability
190. 48870_pressure_like_defensive_responsibility_probability
191. 50763_pressure_like_defensive_responsibility_probability
192. 132471_pressure_like_defensive_responsibility_probability
193. 220794_pressure_like_defensive_responsibility_probability
194. 330534_pressure_like_defensive_responsibility_probability
195. 337757_pressure_like_defensive_responsibility_probability
196. 365523_pressure_like_defensive_responsibility_probability
197. 367155_pressure_like_defensive_responsibility_probability
198. 368582_pressure_like_defensive_responsibility_probability
199. 399838_pressure_like_defensive_responsibility_probability
200. 401174_pressure_like_defensive_responsibility_probability
201. 415002_pressure_like_defensive_responsibility_probability
202. 416843_pressure_like_defensive_responsibility_probability
203. 422652_pressure_like_defensive_responsibility_probability
204. 436669_pressure_like_defensive_responsibility_probability
205. 474814_pressure_like_defensive_responsibility_probability
206. 482768_pressure_like_defensive_responsibility_probability
207. 5628_interception_like_defensive_responsibility_probability
208. 6357_interception_like_defensive_responsibility_probability
209. 23428_interception_like_defensive_responsibility_probability
210. 26256_interception_like_defensive_responsibility_probability
211. 26267_interception_like_defensive_responsibility_probability
212. 26273_interception_like_defensive_responsibility_probability
213. 26278_interception_like_defensive_responsibility_probability
214. 26311_interception_like_defensive_responsibility_probability
215. 30458_interception_like_defensive_responsibility_probability
216. 27902_interception_like_defensive_responsibility_probability
217. 28522_interception_like_defensive_responsibility_probability
218. 29265_interception_like_defensive_responsibility_probability
219. 30500_interception_like_defensive_responsibility_probability
220. 30736_interception_like_defensive_responsibility_probability
221. 30944_interception_like_defensive_responsibility_probability
222. 34349_interception_like_defensive_responsibility_probability
223. 32728_interception_like_defensive_responsibility_probability
224. 42479_interception_like_defensive_responsibility_probability
225. 42481_interception_like_defensive_responsibility_probability
226. 36167_interception_like_defensive_responsibility_probability
227. 35690_interception_like_defensive_responsibility_probability
228. 37999_interception_like_defensive_responsibility_probability
229. 43555_interception_like_defensive_responsibility_probability
230. 47172_interception_like_defensive_responsibility_probability
231. 47467_interception_like_defensive_responsibility_probability
232. 48870_interception_like_defensive_responsibility_probability
233. 50763_interception_like_defensive_responsibility_probability
234. 132471_interception_like_defensive_responsibility_probability
235. 220794_interception_like_defensive_responsibility_probability
236. 330534_interception_like_defensive_responsibility_probability
237. 337757_interception_like_defensive_responsibility_probability
238. 365523_interception_like_defensive_responsibility_probability
239. 367155_interception_like_defensive_responsibility_probability
240. 368582_interception_like_defensive_responsibility_probability
241. 399838_interception_like_defensive_responsibility_probability
242. 401174_interception_like_defensive_responsibility_probability
243. 415002_interception_like_defensive_responsibility_probability
244. 416843_interception_like_defensive_responsibility_probability
245. 422652_interception_like_defensive_responsibility_probability
246. 436669_interception_like_defensive_responsibility_probability
247. 474814_interception_like_defensive_responsibility_probability
248. 482768_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 72,592
Partidos únicos: 20
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,5628_defensive_responsibility_probability,6357_defensive_responsibility_probability,23428_defensive_responsibility_probability,26256_defensive_responsibility_probability,26267_defensive_responsibility_probability,26273_defensive_responsibility_probability,26278_defensive_responsibility_probability,26311_defensive_responsibility_probability,30458_defensive_responsibility_probability,27902_defensive_responsibility_probability,28522_defensive_responsibility_probability,29265_defensive_responsibility_probability,30500_defensive_responsibility_probability,30736_defensive_responsibility_probability,30944_defensive_responsibility_probability,34349_defensive_responsibility_probability,32728_defensive_responsibility_probability,42479_defensive_responsibility_probability,42481_defensive_responsibility_probability,36167_defensive_responsibility_probability,35690_defensive_responsibility_probability,37999_defensive_responsibility_probability,43555_defensive_responsibility_probability,47172_defensive_responsibility_probability,47467_defensive_responsibility_probability,48870_defensive_responsibility_probability,50763_defensive_responsibility_probability,132471_defensive_responsibility_probability,220794_defensive_responsibility_probability,330534_defensive_responsibility_probability,337757_defensive_responsibility_probability,365523_defensive_responsibility_probability,367155_defensive_responsibility_probability,368582_defensive_responsibility_probability,399838_defensive_responsibility_probability,401174_defensive_responsibility_probability,415002_defensive_responsibility_probability,416843_defensive_responsibility_probability,422652_defensive_responsibility_probability,436669_defensive_responsibility_probability,474814_defensive_responsibility_probability,482768_defensive_responsibility_probability,5628_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,23428_pressure_like_defensive_responsibility_probability,26256_pressure_like_defensive_responsibility_probability,26267_pressure_like_defensive_responsibility_probability,26273_pressure_like_defensive_responsibility_probability,26278_pressure_like_defensive_responsibility_probability,26311_pressure_like_defensive_responsibility_probability,30458_pressure_like_defensive_responsibility_probability,27902_pressure_like_defensive_responsibility_probability,28522_pressure_like_defensive_responsibility_probability,29265_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30736_pressure_like_defensive_responsibility_probability,30944_pressure_like_defensive_responsibility_probability,34349_pressure_like_defensive_responsibility_probability,32728_pressure_like_defensive_responsibility_probability,42479_pressure_like_defensive_responsibility_probability,42481_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,35690_pressure_like_defensive_responsibility_probability,37999_pressure_like_defensive_responsibility_probability,43555_pressure_like_defensive_responsibility_probability,47172_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,48870_pressure_like_defensive_responsibility_probability,50763_pressure_like_defensive_responsibility_probability,132471_pressure_like_defensive_responsibility_probability,220794_pressure_like_defensive_responsibility_probability,330534_pressure_like_defensive_responsibility_probability,337757_pressure_like_defensive_responsibility_probability,365523_pressure_like_defensive_responsibility_probability,367155_pressure_like_defensive_responsibility_probability,368582_pressure_like_defensive_responsibility_probability,399838_pressure_like_defensive_responsibility_probability,401174_pressure_like_defensive_responsibility_probability,415002_pressure_like_defensive_responsibility_probability,416843_pressure_like_defensive_responsibility_probability,422652_pressure_like_defensive_responsibility_probability,436669_pressure_like_defensive_responsibility_probability,474814_pressure_like_defensive_responsibility_probability,482768_pressure_like_defensive_responsibility_probability,5628_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,23428_interception_like_defensive_responsibility_probability,26256_interception_like_defensive_responsibility_probability,26267_interception_like_defensive_responsibility_probability,26273_interception_like_defensive_responsibility_probability,26278_interception_like_defensive_responsibility_probability,26311_interception_like_defensive_responsibility_probability,30458_interception_like_defensive_responsibility_probability,27902_interception_like_defensive_responsibility_probability,28522_interception_like_defensive_responsibility_probability,29265_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30736_interception_like_defensive_responsibility_probability,30944_interception_like_defensive_responsibility_probability,34349_interception_like_defensive_responsibility_probability,32728_interception_like_defensive_responsibility_probability,42479_interception_like_defensive_responsibility_probability,42481_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,35690_interception_like_defensive_responsibility_probability,37999_interception_like_defensive_responsibility_probability,43555_interception_like_defensive_responsibility_probability,47172_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,48870_interception_like_defensive_responsibility_probability,50763_interception_like_defensive_responsibility_probability,132471_interception_like_defensive_responsibility_probability,220794_interception_like_defensive_responsibility_probability,330534_interception_like_defensive_responsibility_probability,337757_interception_like_defensive_responsibility_probability,365523_interception_like_defensive_responsibility_probability,367155_interception_like_defensive_responsibility_probability,368582_interception_like_defensive_responsibility_probability,399838_interception_like_defensive_responsibility_probability,401174_interception_like_defensive_responsibility_probability,415002_interception_like_defensive_responsibility_probability,416843_interception_like_defensive_responsibility_probability,422652_interception_like_defensive_responsibility_probability,436669_interception_like_defensive_responsibility_probability,474814_interception_like_defensive_responsibility_probability,482768_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
033fb27f-84b6-5321-9c43-23e0945eac86,1,4004042,1,00:00,0,0,35,Starting XI,1,,,5,Other,1229,América,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [16]:
evaluacion('Liga_MX_2025_2026_America_p2.csv')

### Evaluación de eventos

Número de columnas: 254

Columnas:
  1. id
  2. index
  3. match_id
  4. period
  5. timestamp
  6. minute
  7. second
  8. event_type_id
  9. event_type_name
 10. possession
 11. possession_team_id
 12. possession_team_name
 13. play_pattern_id
 14. play_pattern_name
 15. team_id
 16. team_name
 17. player_id
 18. player_name
 19. player_position_id
 20. player_position_name
 21. location_x
 22. location_y
 23. end_location_x
 24. end_location_y
 25. end_location_z
 26. impact_height
 27. duration
 28. under_pressure
 29. counterpress
 30. substituted_player_id
 31. substituted_player_name
 32. pass_recipient_id
 33. pass_recipient_name
 34. pass_length
 35. pass_angle
 36. pass_height_id
 37. pass_height_name
 38. pass_cross
 39. pass_cut_back
 40. pass_switch
 41. assisted_shot_id
 42. key_pass_id
 43. follows_dribble
 44. one_on_one
 45. open_goal
 46. statsbomb_xg
 47. off_camera
 48. out
 49. obv_for_after
 50. obv_for_before
 51. obv_for_net
 52. obv_against_after
 53. obv_against_before
 54. obv_against_net
 55. obv_total_net
 56. outcome_id
 57. outcome_name
 58. type_id
 59. type_name
 60. card_id
 61. card_name
 62. body_part_id
 63. body_part_name
 64. technique_id
 65. technique_name
 66. position_id
 67. position_name
 68. advantage
 69. aerial_won
 70. backheel
 71. defensive
 72. deflected
 73. deflection
 74. first_time
 75. in_chain
 76. miscommunication
 77. nutmeg
 78. offensive
 79. overrun
 80. penalty
 81. recovery_failure
 82. redirect
 83. save_block
 84. through_ball
 85. throw_in
 86. early_video_end
 87. late_video_start
 88. match_suspended
 89. related_events
 90. freeze_frame_player_id
 91. freeze_frame_player_name
 92. freeze_frame_player_position_id
 93. freeze_frame_player_position_name
 94. freeze_frame_teammate
 95. freeze_frame_x
 96. freeze_frame_y
 97. formation_player_id
 98. formation_player_name
 99. formation_position_id
100. formation_position_name
101. formation_jersey_number
102. shot_shot_assist
103. shot_goal_assist
104. pass_cluster_id
105. pass_cluster_label
106. pass_cluster_probability
107. pass_success_probability
108. shot_execution_xg
109. shot_execution_xg_uplift
110. gk_save_difficulty_xg
111. gk_positioning_xg_suppression
112. gk_shot_stopping_xg_suppression
113. set_piece_phase
114. attacking_direction
115. duel_win_probability
116. hops_rating
117. hops_raw_rating
118. hops_opponent_rating
119. hops_opponent_raw_rating
120. defensive_responsibility_pressure_like
121. defensive_responsibility_interception_like
122. defensive_responsibility_probability_sum
123. 3016_defensive_responsibility_probability
124. 45685_defensive_responsibility_probability
125. 6357_defensive_responsibility_probability
126. 6572_defensive_responsibility_probability
127. 8283_defensive_responsibility_probability
128. 23428_defensive_responsibility_probability
129. 29237_defensive_responsibility_probability
130. 26774_defensive_responsibility_probability
131. 26327_defensive_responsibility_probability
132. 37359_defensive_responsibility_probability
133. 28522_defensive_responsibility_probability
134. 33126_defensive_responsibility_probability
135. 28536_defensive_responsibility_probability
136. 29265_defensive_responsibility_probability
137. 35399_defensive_responsibility_probability
138. 30500_defensive_responsibility_probability
139. 30736_defensive_responsibility_probability
140. 30944_defensive_responsibility_probability
141. 31050_defensive_responsibility_probability
142. 33098_defensive_responsibility_probability
143. 31312_defensive_responsibility_probability
144. 34349_defensive_responsibility_probability
145. 36167_defensive_responsibility_probability
146. 35953_defensive_responsibility_probability
147. 35690_defensive_responsibility_probability
148. 37999_defensive_responsibility_probability
149. 107179_defensive_responsibility_probability
150. 47467_defensive_responsibility_probability
151. 50461_defensive_responsibility_probability
152. 50763_defensive_responsibility_probability
153. 131123_defensive_responsibility_probability
154. 182089_defensive_responsibility_probability
155. 213974_defensive_responsibility_probability
156. 236946_defensive_responsibility_probability
157. 239906_defensive_responsibility_probability
158. 275842_defensive_responsibility_probability
159. 275585_defensive_responsibility_probability
160. 276020_defensive_responsibility_probability
161. 337757_defensive_responsibility_probability
162. 359504_defensive_responsibility_probability
163. 367199_defensive_responsibility_probability
164. 401174_defensive_responsibility_probability
165. 3016_pressure_like_defensive_responsibility_probability
166. 45685_pressure_like_defensive_responsibility_probability
167. 6357_pressure_like_defensive_responsibility_probability
168. 6572_pressure_like_defensive_responsibility_probability
169. 8283_pressure_like_defensive_responsibility_probability
170. 23428_pressure_like_defensive_responsibility_probability
171. 29237_pressure_like_defensive_responsibility_probability
172. 26774_pressure_like_defensive_responsibility_probability
173. 26327_pressure_like_defensive_responsibility_probability
174. 37359_pressure_like_defensive_responsibility_probability
175. 28522_pressure_like_defensive_responsibility_probability
176. 33126_pressure_like_defensive_responsibility_probability
177. 28536_pressure_like_defensive_responsibility_probability
178. 29265_pressure_like_defensive_responsibility_probability
179. 35399_pressure_like_defensive_responsibility_probability
180. 30500_pressure_like_defensive_responsibility_probability
181. 30736_pressure_like_defensive_responsibility_probability
182. 30944_pressure_like_defensive_responsibility_probability
183. 31050_pressure_like_defensive_responsibility_probability
184. 33098_pressure_like_defensive_responsibility_probability
185. 31312_pressure_like_defensive_responsibility_probability
186. 34349_pressure_like_defensive_responsibility_probability
187. 36167_pressure_like_defensive_responsibility_probability
188. 35953_pressure_like_defensive_responsibility_probability
189. 35690_pressure_like_defensive_responsibility_probability
190. 37999_pressure_like_defensive_responsibility_probability
191. 107179_pressure_like_defensive_responsibility_probability
192. 47467_pressure_like_defensive_responsibility_probability
193. 50461_pressure_like_defensive_responsibility_probability
194. 50763_pressure_like_defensive_responsibility_probability
195. 131123_pressure_like_defensive_responsibility_probability
196. 182089_pressure_like_defensive_responsibility_probability
197. 213974_pressure_like_defensive_responsibility_probability
198. 236946_pressure_like_defensive_responsibility_probability
199. 239906_pressure_like_defensive_responsibility_probability
200. 275842_pressure_like_defensive_responsibility_probability
201. 275585_pressure_like_defensive_responsibility_probability
202. 276020_pressure_like_defensive_responsibility_probability
203. 337757_pressure_like_defensive_responsibility_probability
204. 359504_pressure_like_defensive_responsibility_probability
205. 367199_pressure_like_defensive_responsibility_probability
206. 401174_pressure_like_defensive_responsibility_probability
207. 3016_interception_like_defensive_responsibility_probability
208. 45685_interception_like_defensive_responsibility_probability
209. 6357_interception_like_defensive_responsibility_probability
210. 6572_interception_like_defensive_responsibility_probability
211. 8283_interception_like_defensive_responsibility_probability
212. 23428_interception_like_defensive_responsibility_probability
213. 29237_interception_like_defensive_responsibility_probability
214. 26774_interception_like_defensive_responsibility_probability
215. 26327_interception_like_defensive_responsibility_probability
216. 37359_interception_like_defensive_responsibility_probability
217. 28522_interception_like_defensive_responsibility_probability
218. 33126_interception_like_defensive_responsibility_probability
219. 28536_interception_like_defensive_responsibility_probability
220. 29265_interception_like_defensive_responsibility_probability
221. 35399_interception_like_defensive_responsibility_probability
222. 30500_interception_like_defensive_responsibility_probability
223. 30736_interception_like_defensive_responsibility_probability
224. 30944_interception_like_defensive_responsibility_probability
225. 31050_interception_like_defensive_responsibility_probability
226. 33098_interception_like_defensive_responsibility_probability
227. 31312_interception_like_defensive_responsibility_probability
228. 34349_interception_like_defensive_responsibility_probability
229. 36167_interception_like_defensive_responsibility_probability
230. 35953_interception_like_defensive_responsibility_probability
231. 35690_interception_like_defensive_responsibility_probability
232. 37999_interception_like_defensive_responsibility_probability
233. 107179_interception_like_defensive_responsibility_probability
234. 47467_interception_like_defensive_responsibility_probability
235. 50461_interception_like_defensive_responsibility_probability
236. 50763_interception_like_defensive_responsibility_probability
237. 131123_interception_like_defensive_responsibility_probability
238. 182089_interception_like_defensive_responsibility_probability
239. 213974_interception_like_defensive_responsibility_probability
240. 236946_interception_like_defensive_responsibility_probability
241. 239906_interception_like_defensive_responsibility_probability
242. 275842_interception_like_defensive_responsibility_probability
243. 275585_interception_like_defensive_responsibility_probability
244. 276020_interception_like_defensive_responsibility_probability
245. 337757_interception_like_defensive_responsibility_probability
246. 359504_interception_like_defensive_responsibility_probability
247. 367199_interception_like_defensive_responsibility_probability
248. 401174_interception_like_defensive_responsibility_probability
249. control_degree
250. is_transition
251. is_controlled_possession
252. player_possession_directness
253. possession_directness
254. location_bucket
### RESUMEN

Filas totales: 67,822
Partidos únicos: 18
### MUESTRA DE EVENTOS
id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,possession_team_id,possession_team_name,play_pattern_id,play_pattern_name,team_id,team_name,player_id,player_name,player_position_id,player_position_name,location_x,location_y,end_location_x,end_location_y,end_location_z,impact_height,duration,under_pressure,counterpress,substituted_player_id,substituted_player_name,pass_recipient_id,pass_recipient_name,pass_length,pass_angle,pass_height_id,pass_height_name,pass_cross,pass_cut_back,pass_switch,assisted_shot_id,key_pass_id,follows_dribble,one_on_one,open_goal,statsbomb_xg,off_camera,out,obv_for_after,obv_for_before,obv_for_net,obv_against_after,obv_against_before,obv_against_net,obv_total_net,outcome_id,outcome_name,type_id,type_name,card_id,card_name,body_part_id,body_part_name,technique_id,technique_name,position_id,position_name,advantage,aerial_won,backheel,defensive,deflected,deflection,first_time,in_chain,miscommunication,nutmeg,offensive,overrun,penalty,recovery_failure,redirect,save_block,through_ball,throw_in,early_video_end,late_video_start,match_suspended,related_events,freeze_frame_player_id,freeze_frame_player_name,freeze_frame_player_position_id,freeze_frame_player_position_name,freeze_frame_teammate,freeze_frame_x,freeze_frame_y,formation_player_id,formation_player_name,formation_position_id,formation_position_name,formation_jersey_number,shot_shot_assist,shot_goal_assist,pass_cluster_id,pass_cluster_label,pass_cluster_probability,pass_success_probability,shot_execution_xg,shot_execution_xg_uplift,gk_save_difficulty_xg,gk_positioning_xg_suppression,gk_shot_stopping_xg_suppression,set_piece_phase,attacking_direction,duel_win_probability,hops_rating,hops_raw_rating,hops_opponent_rating,hops_opponent_raw_rating,defensive_responsibility_pressure_like,defensive_responsibility_interception_like,defensive_responsibility_probability_sum,3016_defensive_responsibility_probability,45685_defensive_responsibility_probability,6357_defensive_responsibility_probability,6572_defensive_responsibility_probability,8283_defensive_responsibility_probability,23428_defensive_responsibility_probability,29237_defensive_responsibility_probability,26774_defensive_responsibility_probability,26327_defensive_responsibility_probability,37359_defensive_responsibility_probability,28522_defensive_responsibility_probability,33126_defensive_responsibility_probability,28536_defensive_responsibility_probability,29265_defensive_responsibility_probability,35399_defensive_responsibility_probability,30500_defensive_responsibility_probability,30736_defensive_responsibility_probability,30944_defensive_responsibility_probability,31050_defensive_responsibility_probability,33098_defensive_responsibility_probability,31312_defensive_responsibility_probability,34349_defensive_responsibility_probability,36167_defensive_responsibility_probability,35953_defensive_responsibility_probability,35690_defensive_responsibility_probability,37999_defensive_responsibility_probability,107179_defensive_responsibility_probability,47467_defensive_responsibility_probability,50461_defensive_responsibility_probability,50763_defensive_responsibility_probability,131123_defensive_responsibility_probability,182089_defensive_responsibility_probability,213974_defensive_responsibility_probability,236946_defensive_responsibility_probability,239906_defensive_responsibility_probability,275842_defensive_responsibility_probability,275585_defensive_responsibility_probability,276020_defensive_responsibility_probability,337757_defensive_responsibility_probability,359504_defensive_responsibility_probability,367199_defensive_responsibility_probability,401174_defensive_responsibility_probability,3016_pressure_like_defensive_responsibility_probability,45685_pressure_like_defensive_responsibility_probability,6357_pressure_like_defensive_responsibility_probability,6572_pressure_like_defensive_responsibility_probability,8283_pressure_like_defensive_responsibility_probability,23428_pressure_like_defensive_responsibility_probability,29237_pressure_like_defensive_responsibility_probability,26774_pressure_like_defensive_responsibility_probability,26327_pressure_like_defensive_responsibility_probability,37359_pressure_like_defensive_responsibility_probability,28522_pressure_like_defensive_responsibility_probability,33126_pressure_like_defensive_responsibility_probability,28536_pressure_like_defensive_responsibility_probability,29265_pressure_like_defensive_responsibility_probability,35399_pressure_like_defensive_responsibility_probability,30500_pressure_like_defensive_responsibility_probability,30736_pressure_like_defensive_responsibility_probability,30944_pressure_like_defensive_responsibility_probability,31050_pressure_like_defensive_responsibility_probability,33098_pressure_like_defensive_responsibility_probability,31312_pressure_like_defensive_responsibility_probability,34349_pressure_like_defensive_responsibility_probability,36167_pressure_like_defensive_responsibility_probability,35953_pressure_like_defensive_responsibility_probability,35690_pressure_like_defensive_responsibility_probability,37999_pressure_like_defensive_responsibility_probability,107179_pressure_like_defensive_responsibility_probability,47467_pressure_like_defensive_responsibility_probability,50461_pressure_like_defensive_responsibility_probability,50763_pressure_like_defensive_responsibility_probability,131123_pressure_like_defensive_responsibility_probability,182089_pressure_like_defensive_responsibility_probability,213974_pressure_like_defensive_responsibility_probability,236946_pressure_like_defensive_responsibility_probability,239906_pressure_like_defensive_responsibility_probability,275842_pressure_like_defensive_responsibility_probability,275585_pressure_like_defensive_responsibility_probability,276020_pressure_like_defensive_responsibility_probability,337757_pressure_like_defensive_responsibility_probability,359504_pressure_like_defensive_responsibility_probability,367199_pressure_like_defensive_responsibility_probability,401174_pressure_like_defensive_responsibility_probability,3016_interception_like_defensive_responsibility_probability,45685_interception_like_defensive_responsibility_probability,6357_interception_like_defensive_responsibility_probability,6572_interception_like_defensive_responsibility_probability,8283_interception_like_defensive_responsibility_probability,23428_interception_like_defensive_responsibility_probability,29237_interception_like_defensive_responsibility_probability,26774_interception_like_defensive_responsibility_probability,26327_interception_like_defensive_responsibility_probability,37359_interception_like_defensive_responsibility_probability,28522_interception_like_defensive_responsibility_probability,33126_interception_like_defensive_responsibility_probability,28536_interception_like_defensive_responsibility_probability,29265_interception_like_defensive_responsibility_probability,35399_interception_like_defensive_responsibility_probability,30500_interception_like_defensive_responsibility_probability,30736_interception_like_defensive_responsibility_probability,30944_interception_like_defensive_responsibility_probability,31050_interception_like_defensive_responsibility_probability,33098_interception_like_defensive_responsibility_probability,31312_interception_like_defensive_responsibility_probability,34349_interception_like_defensive_responsibility_probability,36167_interception_like_defensive_responsibility_probability,35953_interception_like_defensive_responsibility_probability,35690_interception_like_defensive_responsibility_probability,37999_interception_like_defensive_responsibility_probability,107179_interception_like_defensive_responsibility_probability,47467_interception_like_defensive_responsibility_probability,50461_interception_like_defensive_responsibility_probability,50763_interception_like_defensive_responsibility_probability,131123_interception_like_defensive_responsibility_probability,182089_interception_like_defensive_responsibility_probability,213974_interception_like_defensive_responsibility_probability,236946_interception_like_defensive_responsibility_probability,239906_interception_like_defensive_responsibility_probability,275842_interception_like_defensive_responsibility_probability,275585_interception_like_defensive_responsibility_probability,276020_interception_like_defensive_responsibility_probability,337757_interception_like_defensive_responsibility_probability,359504_interception_like_defensive_responsibility_probability,367199_interception_like_defensive_responsibility_probability,401174_interception_like_defensive_responsibility_probability,control_degree,is_transition,is_controlled_possession,player_possession_directness,possession_directness,location_bucket
641a0891-1e0a-5c89-8dff-bf302ba4a61e,1,4038818,1,00:00,0,0,35,Starting XI,1,,,5,Other,1229,América,,,,,,,,,,,0.0,False,False,,,,,,,,,,,,,,False,,,,False,False,,,,,,,,,,,,,,,,,,,,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,,,,,,,,,,,,,,,,,,,,,,,,,,left_to_right,,,,,,False,False,0.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

### Construcción de archivo RAW

In [17]:
repo = 'https://raw.githubusercontent.com/MiguelFigueroa02/ITAM_Sport_Lucho_FC/refs/heads/main/data/raw/'

In [18]:
datasets = [
    "Liga_MX_2023_2024_America_p1.csv",
    "Liga_MX_2023_2024_America_p2.csv",
    "Liga_MX_2023_2024_America_p3.csv",
    "Liga_MX_2024_2025_America_p1.csv",
    "Liga_MX_2024_2025_America_p2.csv",
    "Liga_MX_2024_2025_America_p3.csv",
    "Liga_MX_2025_2026_America_p1.csv",
    "Liga_MX_2025_2026_America_p2.csv"
]

In [19]:
for dataset in datasets:
    file = repo + dataset
    df = pd.read_csv(file, nrows=5)

    print(f"{dataset}")
    print(f"  Filas inspeccionadas: {len(df)}")
    print(f"  Columnas: {len(df.columns)}")
    # print(f"  Tamaño: {file.stat().st_size / 1024**2:.2f} MB")
    print()

Liga_MX_2023_2024_America_p1.csv
  Filas inspeccionadas: 5
  Columnas: 251

Liga_MX_2023_2024_America_p2.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2023_2024_America_p3.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2024_2025_America_p1.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2024_2025_America_p2.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2024_2025_America_p3.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2025_2026_America_p1.csv
  Filas inspeccionadas: 5
  Columnas: 254

Liga_MX_2025_2026_America_p2.csv
  Filas inspeccionadas: 5
  Columnas: 254

In [20]:
schemas = {}

for dataset in datasets:
    file = repo + dataset
    df = pd.read_csv(file, nrows=0)
    schemas[dataset] = set(df.columns)

all_columns = set().union(*schemas.values())

print(f"Columnas totales distintas: {len(all_columns)}\n")

for filename, columns in schemas.items():
    missing = all_columns - columns
    extra = columns - min(schemas.values(), key=len)

    print(f"=== {filename} ===")
    print(f"Columnas: {len(columns)}")
    print(f"Faltantes respecto al universo: {len(missing)}")

    if missing:
        print("Faltantes:", sorted(missing))

    print()

Columnas totales distintas: 707

=== Liga_MX_2023_2024_America_p1.csv ===
Columnas: 251
Faltantes respecto al universo: 456

In [21]:
# Tomamos como referencia uno de los archivos de 254 columnas
reference = datasets[0]
reference_file = repo + reference

reference_columns = set(
    pd.read_csv(reference_file, nrows=0).columns
)

for dataset in datasets[1:]:
    file = repo + dataset
    columns = set(pd.read_csv(file, nrows=0).columns)

    missing = reference_columns - columns
    extra = columns - reference_columns

    print(f'## {dataset}')
    print(f"Columnas: {len(columns)}")

    print(f"\nFaltantes respecto a {reference}: {len(missing)}")
    if missing:
        print(sorted(missing))

    print(f"\nExtra respecto a {reference}: {len(extra)}")
    if extra:
        print(sorted(extra))

## Liga_MX_2023_2024_America_p2.csv
Columnas: 254

Faltantes respecto a Liga_MX_2023_2024_America_p1.csv: 90
['11388_defensive_responsibility_probability', '11388_interception_like_defensive_responsibility_probability', '11388_pressure_like_defensive_responsibility_probability', '13034_defensive_responsibility_probability', '13034_interception_like_defensive_responsibility_probability', '13034_pressure_like_defensive_responsibility_probability', '131162_defensive_responsibility_probability', '131162_interception_like_defensive_responsibility_probability', '131162_pressure_like_defensive_responsibility_probability', '134157_defensive_responsibility_probability', '134157_interception_like_defensive_responsibility_probability', '134157_pressure_like_defensive_responsibility_probability', '182089_defensive_responsibility_probability', '182089_interception_like_defensive_responsibility_probability', '182089_pressure_like_defensive_responsibility_probability', '23842_defensive_responsibility_probability', '23842_interception_like_defensive_responsibility_probability', '23842_pressure_like_defensive_responsibility_probability', '26278_defensive_responsibility_probability', '26278_interception_like_defensive_responsibility_probability', '26278_pressure_like_defensive_responsibility_probability', '26298_defensive_responsibility_probability', '26298_interception_like_defensive_responsibility_probability', '26298_pressure_like_defensive_responsibility_probability', '26309_defensive_responsibility_probability', '26309_interception_like_defensive_responsibility_probability', '26309_pressure_like_defensive_responsibility_probability', '26356_defensive_responsibility_probability', '26356_interception_like_defensive_responsibility_probability', '26356_pressure_like_defensive_responsibility_probability', '26389_defensive_responsibility_probability', '26389_interception_like_defensive_responsibility_probability', '26389_pressure_like_defensive_responsibility_probability', '277725_defensive_responsibility_probability', '277725_interception_like_defensive_responsibility_probability', '277725_pressure_like_defensive_responsibility_probability', '283233_defensive_responsibility_probability', '283233_interception_like_defensive_responsibility_probability', '283233_pressure_like_defensive_responsibility_probability', '28433_defensive_responsibility_probability', '28433_interception_like_defensive_responsibility_probability', '28433_pressure_like_defensive_responsibility_probability', '28562_defensive_responsibility_probability', '28562_interception_like_defensive_responsibility_probability', '28562_pressure_like_defensive_responsibility_probability', '302108_defensive_responsibility_probability', '302108_interception_like_defensive_responsibility_probability', '302108_pressure_like_defensive_responsibility_probability', '30736_defensive_responsibility_probability', '30736_interception_like_defensive_responsibility_probability', '30736_pressure_like_defensive_responsibility_probability', '30846_defensive_responsibility_probability', '30846_interception_like_defensive_responsibility_probability', '30846_pressure_like_defensive_responsibility_probability', '31312_defensive_responsibility_probability', '31312_interception_like_defensive_responsibility_probability', '31312_pressure_like_defensive_responsibility_probability', '32728_defensive_responsibility_probability', '32728_interception_like_defensive_responsibility_probability', '32728_pressure_like_defensive_responsibility_probability', '34361_defensive_responsibility_probability', '34361_interception_like_defensive_responsibility_probability', '34361_pressure_like_defensive_responsibility_probability', '35544_defensive_responsibility_probability', '35544_interception_like_defensive_responsibility_probability', '35544_pressure_like_defensive_responsibility_probability', '37072_defensive_responsibility_probability', '37072_interception_like_defensive_responsibility_probability', '37072_pressure_like_defensive_responsibility_probability', '391381_defensive_responsibility_probability', '391381_interception_like_defensive_responsibility_probability', '391381_pressure_like_defensive_responsibility_probability', '399838_defensive_responsibility_probability', '399838_interception_like_defensive_responsibility_probability', '399838_pressure_like_defensive_responsibility_probability', '399839_defensive_responsibility_probability', '399839_interception_like_defensive_responsibility_probability', '399839_pressure_like_defensive_responsibility_probability', '399840_defensive_responsibility_probability', '399840_interception_like_defensive_responsibility_probability', '399840_pressure_like_defensive_responsibility_probability', '399841_defensive_responsibility_probability', '399841_interception_like_defensive_responsibility_probability', '399841_pressure_like_defensive_responsibility_probability', '41777_defensive_responsibility_probability', '41777_interception_like_defensive_responsibility_probability', '41777_pressure_like_defensive_responsibility_probability', '43720_defensive_responsibility_probability', '43720_interception_like_defensive_responsibility_probability', '43720_pressure_like_defensive_responsibility_probability']

Extra respecto a Liga_MX_2023_2024_America_p1.csv: 93
['10846_defensive_responsibility_probability', '10846_interception_like_defensive_responsibility_probability', '10846_pressure_like_defensive_responsibility_probability', '123690_defensive_responsibility_probability', '123690_interception_like_defensive_responsibility_probability', '123690_pressure_like_defensive_responsibility_probability', '131123_defensive_responsibility_probability', '131123_interception_like_defensive_responsibility_probability', '131123_pressure_like_defensive_responsibility_probability', '226626_defensive_responsibility_probability', '226626_interception_like_defensive_responsibility_probability', '226626_pressure_like_defensive_responsibility_probability', '26256_defensive_responsibility_probability', '26256_interception_like_defensive_responsibility_probability', '26256_pressure_like_defensive_responsibility_probability', '26288_defensive_responsibility_probability', '26288_interception_like_defensive_responsibility_probability', '26288_pressure_like_defensive_responsibility_probability', '26289_defensive_responsibility_probability', '26289_interception_like_defensive_responsibility_probability', '26289_pressure_like_defensive_responsibility_probability', '26311_defensive_responsibility_probability', '26311_interception_like_defensive_responsibility_probability', '26311_pressure_like_defensive_responsibility_probability', '26327_defensive_responsibility_probability', '26327_interception_like_defensive_responsibility_probability', '26327_pressure_like_defensive_responsibility_probability', '26400_defensive_responsibility_probability', '26400_interception_like_defensive_responsibility_probability', '26400_pressure_like_defensive_responsibility_probability', '26774_defensive_responsibility_probability', '26774_interception_like_defensive_responsibility_probability', '26774_pressure_like_defensive_responsibility_probability', '27967_defensive_responsibility_probability', '27967_interception_like_defensive_responsibility_probability', '27967_pressure_like_defensive_responsibility_probability', '28056_defensive_responsibility_probability', '28056_interception_like_defensive_responsibility_probability', '28056_pressure_like_defensive_responsibility_probability', '28160_defensive_responsibility_probability', '28160_interception_like_defensive_responsibility_probability', '28160_pressure_like_defensive_responsibility_probability', '29266_defensive_responsibility_probability', '29266_interception_like_defensive_responsibility_probability', '29266_pressure_like_defensive_responsibility_probability', '29269_defensive_responsibility_probability', '29269_interception_like_defensive_responsibility_probability', '29269_pressure_like_defensive_responsibility_probability', '29424_defensive_responsibility_probability', '29424_interception_like_defensive_responsibility_probability', '29424_pressure_like_defensive_responsibility_probability', '30458_defensive_responsibility_probability', '30458_interception_like_defensive_responsibility_probability', '30458_pressure_like_defensive_responsibility_probability', '32164_defensive_responsibility_probability', '32164_interception_like_defensive_responsibility_probability', '32164_pressure_like_defensive_responsibility_probability', '33098_defensive_responsibility_probability', '33098_interception_like_defensive_responsibility_probability', '33098_pressure_like_defensive_responsibility_probability', '33126_defensive_responsibility_probability', '33126_interception_like_defensive_responsibility_probability', '33126_pressure_like_defensive_responsibility_probability', '35375_defensive_responsibility_probability', '35375_interception_like_defensive_responsibility_probability', '35375_pressure_like_defensive_responsibility_probability', '35953_defensive_responsibility_probability', '35953_interception_like_defensive_responsibility_probability', '35953_pressure_like_defensive_responsibility_probability', '401174_defensive_responsibility_probability', '401174_interception_like_defensive_responsibility_probability', '401174_pressure_like_defensive_responsibility_probability', '43547_defensive_responsibility_probability', '43547_interception_like_defensive_responsibility_probability', '43547_pressure_like_defensive_responsibility_probability', '43557_defensive_responsibility_probability', '43557_interception_like_defensive_responsibility_probability', '43557_pressure_like_defensive_responsibility_probability', '44922_defensive_responsibility_probability', '44922_interception_like_defensive_responsibility_probability', '44922_pressure_like_defensive_responsibility_probability', '45685_defensive_responsibility_probability', '45685_interception_like_defensive_responsibility_probability', '45685_pressure_like_defensive_responsibility_probability', '47467_defensive_responsibility_probability', '47467_interception_like_defensive_responsibility_probability', '47467_pressure_like_defensive_responsibility_probability', '50461_defensive_responsibility_probability', '50461_interception_like_defensive_responsibility_probability', '50461_pressure_like_defensive_responsibility_probability', '9926_defensive_responsibility_probability', '9926_interception_like_defensive_responsibility_probability', '9926_pressure_like_defensive_responsibility_probability']
## Liga_MX_2023_2024_America_p3.csv
Columnas: 254

Faltantes respecto a Liga_MX_2023_2024_America_p1.csv: 90
['13034_defensive_responsibility_probability', '13034_interception_like_defensive_responsibility_probability', '13034_pressure_like_defensive_responsibility_probability', '131162_defensive_responsibility_probability', '131162_interception_like_defensive_responsibility_probability', '131162_pressure_like_defensive_responsibility_probability', '134157_defensive_responsibility_probability', '134157_interception_like_defensive_responsibility_probability', '134157_pressure_like_defensive_responsibility_probability', '182089_defensive_responsibility_probability', '182089_interception_like_defensive_responsibility_probability', '182089_pressure_like_defensive_responsibility_probability', '23842_defensive_responsibility_probability', '23842_interception_like_defensive_responsibility_probability', '23842_pressure_like_defensive_responsibility_probability', '26278_defensive_responsibility_probability', '26278_interception_like_defensive_responsibility_probability', '26278_pressure_like_defensive_responsibility_probability', '26298_defensive_responsibility_probability', '26298_interception_like_defensive_responsibility_probability', '26298_pressure_like_defensive_responsibility_probability', '26309_defensive_responsibility_probability', '26309_interception_like_defensive_responsibility_probability', '26309_pressure_like_defensive_responsibility_probability', '26356_defensive_responsibility_probability', '26356_interception_like_defensive_responsibility_probability', '26356_pressure_like_defensive_responsibility_probability', '26389_defensive_responsibility_probability', '26389_interception_like_defensive_responsibility_probability', '26389_pressure_like_defensive_responsibility_probability', '277725_defensive_responsibility_probability', '277725_interception_like_defensive_responsibility_probability', '277725_pressure_like_defensive_responsibility_probability', '283233_defensive_responsibility_probability', '283233_interception_like_defensive_responsibility_probability', '283233_pressure_like_defensive_responsibility_probability', '28433_defensive_responsibility_probability', '28433_interception_like_defensive_responsibility_probability', '28433_pressure_like_defensive_responsibility_probability', '302108_defensive_responsibility_probability', '302108_interception_like_defensive_responsibility_probability', '302108_pressure_like_defensive_responsibility_probability', '30846_defensive_responsibility_probability', '30846_interception_like_defensive_responsibility_probability', '30846_pressure_like_defensive_responsibility_probability', '31312_defensive_responsibility_probability', '31312_interception_like_defensive_responsibility_probability', '31312_pressure_like_defensive_responsibility_probability', '32728_defensive_responsibility_probability', '32728_interception_like_defensive_responsibility_probability', '32728_pressure_like_defensive_responsibility_probability', '34361_defensive_responsibility_probability', '34361_interception_like_defensive_responsibility_probability', '34361_pressure_like_defensive_responsibility_probability', '35544_defensive_responsibility_probability', '35544_interception_like_defensive_responsibility_probability', '35544_pressure_like_defensive_responsibility_probability', '35690_defensive_responsibility_probability', '35690_interception_like_defensive_responsibility_probability', '35690_pressure_like_defensive_responsibility_probability', '37072_defensive_responsibility_probability', '37072_interception_like_defensive_responsibility_probability', '37072_pressure_like_defensive_responsibility_probability', '391381_defensive_responsibility_probability', '391381_interception_like_defensive_responsibility_probability', '391381_pressure_like_defensive_responsibility_probability', '399838_defensive_responsibility_probability', '399838_interception_like_defensive_responsibility_probability', '399838_pressure_like_defensive_responsibility_probability', '399839_defensive_responsibility_probability', '399839_interception_like_defensive_responsibility_probability', '399839_pressure_like_defensive_responsibility_probability', '399840_defensive_responsibility_probability', '399840_interception_like_defensive_responsibility_probability', '399840_pressure_like_defensive_responsibility_probability', '399841_defensive_responsibility_probability', '399841_interception_like_defensive_responsibility_probability', '399841_pressure_like_defensive_responsibility_probability', '41777_defensive_responsibility_probability', '41777_interception_like_defensive_responsibility_probability', '41777_pressure_like_defensive_responsibility_probability', '43720_defensive_responsibility_probability', '43720_interception_like_defensive_responsibility_probability', '43720_pressure_like_defensive_responsibility_probability', '5556_defensive_responsibility_probability', '5556_interception_like_defensive_responsibility_probability', '5556_pressure_like_defensive_responsibility_probability', '8863_defensive_responsibility_probability', '8863_interception_like_defensive_responsibility_probability', '8863_pressure_like_defensive_responsibility_probability']

Extra respecto a Liga_MX_2023_2024_America_p1.csv: 93

#### Interpretación
---
- Estamos encontrando que cada uno de los datasets presenta columnas dinámicas asociadas al ID de los jugadores de cada partido.
- Para continuar con nuestro proceso, procederemos a definir cuáles columnas son estables y cuáles son asociados a resultados dinámicos. A partir de las columnas estables son de las que en primera instancia procederemos a establecer métricas básicas asociadas al rendimiento para interpretación del estilo táctico.

In [22]:
columns = pd.read_csv(reference_file, nrows=0).columns

dynamic_columns = [
    col for col in columns
    if re.match(r"^\d+_", col)
]

stable_columns = [
    col for col in columns
    if col not in dynamic_columns
]

print(f"Columnas totales: {len(columns)}")
print(f"Columnas dinámicas de jugador: {len(dynamic_columns)}")
print(f"Columnas estables: {len(stable_columns)}")

print("\nPrimeras columnas estables:")
print(stable_columns[:50])

Columnas totales: 251
Columnas dinámicas de jugador: 123
Columnas estables: 128

Primeras columnas estables:
['id', 'index', 'match_id', 'period', 'timestamp', 'minute', 'second', 'event_type_id', 'event_type_name', 'possession', 'possession_team_id', 'possession_team_name', 'play_pattern_id', 'play_pattern_name', 'team_id', 'team_name', 'player_id', 'player_name', 'player_position_id', 'player_position_name', 'location_x', 'location_y', 'end_location_x', 'end_location_y', 'end_location_z', 'impact_height', 'duration', 'under_pressure', 'counterpress', 'substituted_player_id', 'substituted_player_name', 'pass_recipient_id', 'pass_recipient_name', 'pass_length', 'pass_angle', 'pass_height_id', 'pass_height_name', 'pass_cross', 'pass_cut_back', 'pass_switch', 'assisted_shot_id', 'key_pass_id', 'follows_dribble', 'one_on_one', 'open_goal', 'statsbomb_xg', 'off_camera', 'out', 'obv_for_after', 'obv_for_before']

In [23]:
# Comparar las columnas estables entre todos los archivos

reference_columns = set(stable_columns)

for dataset in datasets:
    file = repo + dataset
    columns = set(pd.read_csv(file, nrows=0).columns)

    dynamic = {
        col for col in columns
        if re.match(r"^\d+_", col)
    }

    stable = columns - dynamic

    missing = reference_columns - stable
    extra = stable - reference_columns

    print(f"\n{'='*70}")
    print(dataset)
    print(f"Columnas estables: {len(stable)}")
    print(f"Faltantes: {len(missing)}")
    print(f"Extras: {len(extra)}")

    if missing:
        print("Faltantes:", sorted(missing))

    if extra:
        print("Extras:", sorted(extra))

======================================================================
Liga_MX_2023_2024_America_p1.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2023_2024_America_p2.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2023_2024_America_p3.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2024_2025_America_p1.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2024_2025_America_p2.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2024_2025_America_p3.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2025_2026_America_p1.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

======================================================================
Liga_MX_2025_2026_America_p2.csv
Columnas estables: 128
Faltantes: 0
Extras: 0

#### Concatenación
---
A partir de las columnas estables detectadas, procederemos a hacer la configuración de un dataset maestro

In [24]:
stable_columns = list(stable_columns)

dfs = []

for dataset in datasets:
    file = repo + dataset
    print(f"Cargando: {dataset}")

    df = pd.read_csv(file, usecols=stable_columns)

    # Trazabilidad
    df["source_file"] = dataset

    dfs.append(df)


# Concatenar los 8 archivos
events_raw = pd.concat(
    dfs,
    ignore_index=True
)

print("## DATASET CONSOLIDADO")

print(f"Filas: {len(events_raw):,}")
print(f"Columnas: {len(events_raw.columns)}")
print(f"Partidos únicos: {events_raw['match_id'].nunique()}")

print("\nPartidos por archivo:")
print(
    events_raw.groupby("source_file")["match_id"]
    .nunique()
)

print("\nMemoria utilizada:")
print(f"{events_raw.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Cargando: Liga_MX_2023_2024_America_p1.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (60,97,99,246,247,249) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2023_2024_America_p2.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (60,90,92,93,97,99) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2023_2024_America_p3.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2024_2025_America_p1.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2024_2025_America_p2.csv
Cargando: Liga_MX_2024_2025_America_p3.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (17,19,30,32,36,37,38,39,40,41,43,44,56,58,60,62,64,66,88,90,92,93,101,102,104,249,250,253) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2025_2026_America_p1.csv

/tmp/ipykernel_28079/898783433.py:9: DtypeWarning: Columns (249,253) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, usecols=stable_columns)

Cargando: Liga_MX_2025_2026_America_p2.csv
## DATASET CONSOLIDADO
Filas: 501,944
Columnas: 129
Partidos únicos: 131

Partidos por archivo:
source_file
Liga_MX_2023_2024_America_p1.csv    20
Liga_MX_2023_2024_America_p2.csv    20
Liga_MX_2023_2024_America_p3.csv     6
Liga_MX_2024_2025_America_p1.csv    20
Liga_MX_2024_2025_America_p2.csv    20
Liga_MX_2024_2025_America_p3.csv     7
Liga_MX_2025_2026_America_p1.csv    20
Liga_MX_2025_2026_America_p2.csv    18
Name: match_id, dtype: int64

Memoria utilizada:
1119.55 MB

Comparación de datos generados a partir del dataset procesado de partidos

In [25]:
partidos = 'https://raw.githubusercontent.com/MiguelFigueroa02/ITAM_Sport_Lucho_FC/refs/heads/main/data/processed/america_matches.csv'
matches = pd.read_csv(partidos)

print("Dimensiones:", matches.shape)

print("\nColumnas:")
print(matches.columns.tolist())

print("\nPrimeras filas:")
display(matches.head().to_markdown())

print("\nPartidos únicos:")
print(matches["match_id"].nunique())

print("\nDuplicados de match_id:")
print(matches["match_id"].duplicated().sum())

print("\nTipos de datos:")
print(matches.dtypes)

Dimensiones: (131, 16)

Columnas:
['match_id', 'match_date', 'kick_off', 'season', 'competition', 'competition_stage', 'match_week', 'opponent', 'venue', 'america_score', 'opponent_score', 'coach', 'stadium', 'match_status', 'match_status_360', 'result']

Primeras filas:

'|    |   match_id | match_date   | kick_off     | season    | competition   | competition_stage   |   match_week | opponent   | venue   |   america_score |   opponent_score | coach                | stadium         | match_status   | match_status_360   | result   |\n|---:|-----------:|:-------------|:-------------|:----------|:--------------|:--------------------|-------------:|:-----------|:--------|----------------:|-----------------:|:---------------------|:----------------|:---------------|:-------------------|:---------|\n|  0 |    3889637 | 2023-07-01   | 01:00:00.000 | 2023/2024 | Liga MX       | Apertura            |            1 | Juárez     | Home    |               1 |                2 | André Soares Jardine | Estadio Azteca  | available      | available          | L        |\n|  1 |    3889660 | 2023-07-16   | 01:00:00.000 | 2023/2024 | Liga MX       | Apertura            |            3 | Puebla     | Home    |               3 |                0 | André Soares Jardine | Estadio Azteca  | available      | available          | W        |\n|  2 |    3889669 | 2023-08-21   | 03:10:00.000 | 2023/2024 | Liga MX       | Apertura            |            4 | Atlas      | Home    |               1 |                1 | André Soares Jardine | Estadio Jalisco | available      | available          | D        |\n|  3 |    3889681 | 2023-08-24   | 01:00:00.000 | 2023/2024 | Liga MX       | Apertura            |            5 | Necaxa     | Home    |               3 |                2 | André Soares Jardine | Estadio Azteca  | available      | available          | W        |\n|  4 |    3889685 | 2023-08-27   | 01:00:00.000 | 2023/2024 | Liga MX       | Apertura            |            6 | León       | Home    |               1 |                1 | André Soares Jardine | Estadio Azteca  | available      | available          | D        |'

Partidos únicos:
131

Duplicados de match_id:
0

Tipos de datos:
match_id              int64
match_date           object
kick_off             object
season               object
competition          object
competition_stage    object
match_week            int64
opponent             object
venue                object
america_score         int64
opponent_score        int64
coach                object
stadium              object
match_status         object
match_status_360     object
result               object
dtype: object

In [26]:
event_match_ids = set(events_raw["match_id"].unique())
match_match_ids = set(matches["match_id"].unique())

print("Partidos en eventos:", len(event_match_ids))
print("Partidos en catálogo:", len(match_match_ids))

print("\nEventos sin metadata:")
print(event_match_ids - match_match_ids)

print("\nPartidos del catálogo sin eventos:")
print(match_match_ids - event_match_ids)

Partidos en eventos: 131
Partidos en catálogo: 131

Eventos sin metadata:
set()

Partidos del catálogo sin eventos:
set()

Una vez que comprobamos que los partidos de ambos datasets coinciden, procederemos a hacer un join para generar nuestro dataset maestro

In [27]:
events = events_raw.merge(
    matches,
    on="match_id",
    how="left",
    validate="many_to_one"
)

print("Dimensiones:", events.shape)

print("\nPartidos únicos:", events["match_id"].nunique())

print("\nColumnas de contexto agregadas:")
print([
    "season",
    "match_date",
    "opponent",
    "venue",
    "america_score",
    "opponent_score",
    "coach",
    "result"
])

print("\nValores nulos en contexto:")
print(
    events[
        [
            "season",
            "match_date",
            "opponent",
            "venue",
            "america_score",
            "opponent_score",
            "coach",
            "result"
        ]
    ].isna().sum()
)

Dimensiones: (501944, 144)

Partidos únicos: 131

Columnas de contexto agregadas:
['season', 'match_date', 'opponent', 'venue', 'america_score', 'opponent_score', 'coach', 'result']

Valores nulos en contexto:
season            0
match_date        0
opponent          0
venue             0
america_score     0
opponent_score    0
coach             0
result            0
dtype: int64

Queremos conocer el tipo de eventos asociados a nuestro dataset generado

In [28]:
print("EVENT TYPES")
print(events["event_type_name"].value_counts())

print("\n" + "="*70)
print("PLAY PATTERNS")
print(events["play_pattern_name"].value_counts())

print("\n" + "="*70)
print("POSSESSION TEAM")
print(events["possession_team_name"].value_counts().head(10))

print("\n" + "="*70)
print("RESULTADOS")
print(events["result"].value_counts())

print("\n" + "="*70)
print("LOCALÍA")
print(events["venue"].value_counts())

EVENT TYPES
event_type_name
Pass                 126618
Ball Receipt*        116392
Carries              103365
Shot                  47888
Pressure              41287
Ball Recovery         11619
Duel                   7793
Tactical Shift         5734
Clearance              4611
Block                  4542
Goal Keeper            3974
Miscontrol             3475
Dribble                3321
Foul Committed         3269
Starting XI            3144
Foul Won               3084
Dispossessed           3078
Dribbled Past          1901
Interception           1878
Substitution           1177
Injury Stoppage         824
50/50                   665
Half Start              530
Half End                530
Referee Ball-Drop       455
Player Off              186
Player On               185
Shield                  170
Bad Behaviour           134
Error                    62
Offside                  43
Own Goal For              5
Own Goal Against          5
Name: count, dtype: int64

======================================================================
PLAY PATTERNS
play_pattern_name
Regular Play      253806
From Throw In      89811
From Free Kick     63818
From Goal Kick     33607
From Corner        24125
From Keeper        14501
From Kick Off      13891
Other               5031
From Counter        3354
Name: count, dtype: int64

======================================================================
POSSESSION TEAM
possession_team_name
América              272145
Cruz Azul             23250
Monterrey             19368
Toluca                19186
Pachuca               17008
Tigres UANL           16786
Atlético San Luis     15870
Tijuana               14865
Guadalajara           14308
León                  13949
Name: count, dtype: int64

======================================================================
RESULTADOS
result
W    265080
D    142065
L     94799
Name: count, dtype: int64

======================================================================
LOCALÍA
venue
Away    253663
Home    248281
Name: count, dtype: int64

## 4. Construcción

### Pases por posesión

Vamos a evaluar la cantidad de pases que suelen tener por posesión de manera general. El objetivo de su análisis es caracterizar como primera métrica para la construcción ofensiva del equipo.

In [29]:
TEAM_ID = 1229

In [30]:
def possesions(team_id):
  team_events = events[
      events["possession_team_id"] == team_id
  ].copy()
  team_name = team_events.possession_team_name.unique()[0]

  print(f"Eventos de {team_name}:", len(team_events))
  print("Posesiones:", team_events["possession"].nunique())

  print("\nPrimeras posesiones:")
  print(
      team_events[
          ["match_id", "possession", "event_type_name",
          "player_name", "minute"]
      ].head(20).to_markdown()
  )

  print("\nEvento por posesiones:")
  possession_size = (
      team_events.groupby(["match_id", "possession"]).size().reset_index(name="events_in_possession")
  )

  print(possession_size.head().to_markdown())

  print("\nEstadísticas:")
  print(
      possession_size["events_in_possession"].describe().to_markdown()
  )

  passes = team_events[
      team_events["event_type_name"] == "Pass"
  ].copy()

  print('\n## Pases por posesión\n')
  print(f"Pases de {team_name}:", len(passes))

  passes_per_possession = (
      passes
      .groupby(["match_id", "possession"])
      .size()
      .reset_index(name="passes")
  )

  print("\nPrimeras posesiones:")
  print(passes_per_possession.head(10).to_markdown())

  print("\nEstadísticas de pases por posesión:")
  print(passes_per_possession["passes"].describe().to_markdown())

  print('## VALIDACIÓN: POSESIONES CON Y SIN PASES')

  all_possessions = (
      team_events[["match_id", "possession"]]
      .drop_duplicates()
  )

  possession_check = all_possessions.merge(
     passes_per_possession,
     on=["match_id", "possession"],
     how="left"
  )

  possession_check["passes"] = possession_check["passes"].fillna(0)

  print(
      "Total posesiones:",
      len(possession_check)
  )

  print(
      "Posesiones sin pases:",
      (possession_check["passes"] == 0).sum()
  )

  print(
     "Posesiones con al menos un pase:",
     (possession_check["passes"] > 0).sum()
  )

  print("\nDistribución:")
  print(
     possession_check["passes"].describe().to_markdown()
  )

  print('# Pases por posesión')

  passes_match = (
      possession_check
      .groupby("match_id")
      .agg(
          passes_per_possession=("passes", "mean"),
          possessions=("possession", "count")
      )
      .reset_index()
  )

  # Incorporamos contexto del partido
  passes_match = passes_match.merge(
      matches[
          [
              "match_id",
              "opponent",
              "venue",
              "america_score",
              "opponent_score",
              "result",
              "season",
              "coach"
          ]
      ],
      on="match_id",
      how="left",
      validate="one_to_one"
  )

  print(passes_match.head())

  print("\nDimensiones:")
  print(passes_match.shape)

  print("\nEstadísticas:")
  print(
      passes_match["passes_per_possession"].describe().to_markdown()
  )

  print('\n## Pases por posesión ligados al resultado\n')

  result_summary = (
      passes_match
      .groupby("result")
      ["passes_per_possession"]
      .agg(["count", "mean", "median", "std"])
      .round(2)
  )

  print(result_summary.to_markdown())
  print('\n Pases por posesión relacionados con la localía del equipo\n')

  venue_summary = (
      passes_match
      .groupby("venue")
      ["passes_per_possession"]
      .agg(["count", "mean", "median", "std"])
      .round(2)
  )

  print(venue_summary.to_markdown())

  print('\nAnálisis de temporal de los pases por posesión')

  season_summary = (
      passes_match
      .groupby("season")
      ["passes_per_possession"]
      .agg(["count", "mean", "median", "std"])
      .round(2)
  )

  print(season_summary.to_markdown())

In [31]:
possesions(TEAM_ID)

Eventos de América: 272145
Posesiones: 249

Primeras posesiones:
|    |   match_id |   possession | event_type_name   | player_name                     |   minute |
|---:|-----------:|-------------:|:------------------|:--------------------------------|---------:|
|  4 |    3889637 |            2 | Pass              | Román Martínez                  |        0 |
|  5 |    3889637 |            2 | Ball Receipt*     | Jonathan dos Santos Ramírez     |        0 |
|  6 |    3889637 |            2 | Pass              | Jonathan dos Santos Ramírez     |        0 |
|  7 |    3889637 |            2 | Ball Receipt*     | Richard Rafael Sánchez Guerrero |        0 |
|  8 |    3889637 |            2 | Pass              | Richard Rafael Sánchez Guerrero |        0 |
|  9 |    3889637 |            2 | Ball Receipt*     | Kevin Nahin Álvarez Campos      |        0 |
| 10 |    3889637 |            2 | Carries           | Kevin Nahin Álvarez Campos      |        0 |
| 11 |    3889637 |            2 | Pass              | Kevin Nahin Álvarez Campos      |        0 |
| 12 |    3889637 |            2 | Ball Receipt*     | Sebastián Enzo Cáceres Ramos    |        0 |
| 13 |    3889637 |            2 | Carries           | Sebastián Enzo Cáceres Ramos    |        0 |
| 14 |    3889637 |            2 | Pass              | Sebastián Enzo Cáceres Ramos    |        0 |
| 15 |    3889637 |            2 | Ball Receipt*     | Jonathan dos Santos Ramírez     |        0 |
| 16 |    3889637 |            2 | Carries           | Jonathan dos Santos Ramírez     |        0 |
| 17 |    3889637 |            2 | Pass              | Jonathan dos Santos Ramírez     |        0 |
| 18 |    3889637 |            2 | Ball Receipt*     | Miguel Arturo Layún Prado       |        0 |
| 19 |    3889637 |            2 | Carries           | Miguel Arturo Layún Prado       |        0 |
| 20 |    3889637 |            2 | Pressure          | Diego Chávez Collins            |        0 |
| 21 |    3889637 |            2 | Pass              | Miguel Arturo Layún Prado       |        0 |
| 22 |    3889637 |            2 | Ball Receipt*     | Jonathan dos Santos Ramírez     |        0 |
| 23 |    3889637 |            2 | Carries           | Jonathan dos Santos Ramírez     |        0 |

Evento por posesiones:
|    |    match_id |   possession |   events_in_possession |
|---:|------------:|-------------:|-----------------------:|
|  0 | 3.88964e+06 |            2 |                     83 |
|  1 | 3.88964e+06 |            4 |                     37 |
|  2 | 3.88964e+06 |            5 |                    118 |
|  3 | 3.88964e+06 |            7 |                     79 |
|  4 | 3.88964e+06 |            8 |                      8 |

Estadísticas:
|       |   events_in_possession |
|:------|-----------------------:|
| count |             13741      |
| mean  |                19.8053 |
| std   |                19.0167 |
| min   |                 1      |
| 25%   |                 6      |
| 50%   |                14      |
| 75%   |                27      |
| max   |               220      |

## Pases por posesión

Pases de América: 69255

Primeras posesiones:
|    |    match_id |   possession |   passes |
|---:|------------:|-------------:|---------:|
|  0 | 3.88964e+06 |            2 |       22 |
|  1 | 3.88964e+06 |            4 |       12 |
|  2 | 3.88964e+06 |            5 |       41 |
|  3 | 3.88964e+06 |            7 |       18 |
|  4 | 3.88964e+06 |            8 |        3 |
|  5 | 3.88964e+06 |           10 |       12 |
|  6 | 3.88964e+06 |           12 |        3 |
|  7 | 3.88964e+06 |           14 |        9 |
|  8 | 3.88964e+06 |           16 |        8 |
|  9 | 3.88964e+06 |           20 |        2 |

Estadísticas de pases por posesión:
|       |      passes |
|:------|------------:|
| count | 12836       |
| mean  |     5.39537 |
| std   |     5.45128 |
| min   |     1       |
| 25%   |     2       |
| 50%   |     4       |
| 75%   |     7       |
| max   |    64       |
## VALIDACIÓN: POSESIONES CON Y SIN PASES
Total posesiones: 13741
Posesiones sin pases: 905
Posesiones con al menos un pase: 12836

Distribución:
|       |      passes |
|:------|------------:|
| count | 13741       |
| mean  |     5.04003 |
| std   |     5.43601 |
| min   |     0       |
| 25%   |     1       |
| 50%   |     3       |
| 75%   |     7       |
| max   |    64       |
# Pases por posesión
   match_id  passes_per_possession  possessions   opponent venue  \
0   3889637               6.109091          110     Juárez  Home
1   3889653               5.701923          104  Querétaro  Away
2   3889660               7.619565           92     Puebla  Home
3   3889669               5.546296          108      Atlas  Home
4   3889681               6.059322          118     Necaxa  Home

   america_score  opponent_score result     season                 coach
0              1               2      L  2023/2024  André Soares Jardine
1              2               1      W  2023/2024  André Soares Jardine
2              3               0      W  2023/2024  André Soares Jardine
3              1               1      D  2023/2024  André Soares Jardine
4              3               2      W  2023/2024  André Soares Jardine

Dimensiones:
(131, 10)

Estadísticas:
|       |   passes_per_possession |
|:------|------------------------:|
| count |              131        |
| mean  |                5.06637  |
| std   |                0.987674 |
| min   |                2.54867  |
| 25%   |                4.47419  |
| 50%   |                5.08654  |
| 75%   |                5.77105  |
| max   |                7.61957  |

## Pases por posesión ligados al resultado

| result   |   count |   mean |   median |   std |
|:---------|--------:|-------:|---------:|------:|
| D        |      37 |   4.98 |     5.09 |  0.94 |
| L        |      25 |   5.26 |     5.19 |  0.75 |
| W        |      69 |   5.04 |     5.01 |  1.08 |

 Pases por posesión relacionados con la localía del equipo

| venue   |   count |   mean |   median |   std |
|:--------|--------:|-------:|---------:|------:|
| Away    |      66 |   4.99 |     5.02 |  0.98 |
| Home    |      65 |   5.15 |     5.1  |  1    |

Análisis de temporal de los pases por posesión
| season    |   count |   mean |   median |   std |
|:----------|--------:|-------:|---------:|------:|
| 2023/2024 |      46 |   5.32 |     5.24 |  1    |
| 2024/2025 |      47 |   4.79 |     4.88 |  1    |
| 2025/2026 |      38 |   5.1  |     5.08 |  0.89 |

#### Interpretación
---
- Al comparar la progresión de pases bajos distintos escenarios, no encontramos alguna diferencia significativa que nos indique que los pases en cada posesión sean determinantes para el resultado.
- Dado los resultados obtenidos, la métrica no muestra evidencia para sustentar que sea un parámetro táctico a tomar en cuenta al estilo de juego del América

### Progresión mediante pases
---
Estamos intentando analizar la siguiente pregunta:
- ¿Este equipo consigue avanzar el balón y cambiar de progresión según el contexto?

In [32]:
team_events = events[
      events["possession_team_id"] == TEAM_ID
  ].copy()

In [33]:
passes = team_events[team_events["event_type_name"] == "Pass"].copy()

In [34]:
passes_per_possession = (
    passes.groupby(["match_id", "possession"])
    .size()
    .reset_index(name="passes")
)

In [35]:
all_possessions = (
    team_events[["match_id", "possession"]]
    .drop_duplicates()
)

In [36]:
possession_check = all_possessions.merge(
    passes_per_possession,
    on=["match_id", "possession"],
    how="left"
)

In [37]:
passes_match = (
    possession_check
    .groupby("match_id")
    .agg(
        passes_per_possession=("passes", "mean"),
        possessions=("possession", "count")
    )
    .reset_index()
)

In [38]:
match_id_test = passes_match.iloc[0]["match_id"]

In [39]:
match_test = team_events[
    team_events["match_id"] == match_id_test
].copy()

In [40]:
test = match_test[[
    "period",
    "minute",
    "event_type_name",
    "player_name",
    "location_x",
    "location_y",
    "end_location_x",
    "end_location_y"
]]
print(test.head(30).to_markdown(index=False))

|   period |   minute | event_type_name   | player_name                     |   location_x |   location_y |   end_location_x |   end_location_y |
|---------:|---------:|:------------------|:--------------------------------|-------------:|-------------:|-----------------:|-----------------:|
|        1 |        0 | Pass              | Román Martínez                  |         61   |         40.1 |             47.8 |             36.8 |
|        1 |        0 | Ball Receipt*     | Jonathan dos Santos Ramírez     |         47.8 |         36.8 |            nan   |            nan   |
|        1 |        0 | Pass              | Jonathan dos Santos Ramírez     |         47.6 |         37.4 |             46.5 |             49.5 |
|        1 |        0 | Ball Receipt*     | Richard Rafael Sánchez Guerrero |         46.5 |         49.5 |            nan   |            nan   |
|        1 |        0 | Pass              | Richard Rafael Sánchez Guerrero |         45.9 |         49.5 |             39.7 |             68.8 |
|        1 |        0 | Ball Receipt*     | Kevin Nahin Álvarez Campos      |         39.7 |         68.8 |            nan   |            nan   |
|        1 |        0 | Carries           | Kevin Nahin Álvarez Campos      |         39.7 |         68.8 |             39.7 |             68.8 |
|        1 |        0 | Pass              | Kevin Nahin Álvarez Campos      |         39.7 |         68.8 |             27.6 |             24.1 |
|        1 |        0 | Ball Receipt*     | Sebastián Enzo Cáceres Ramos    |         27.6 |         24.1 |            nan   |            nan   |
|        1 |        0 | Carries           | Sebastián Enzo Cáceres Ramos    |         27.6 |         24.1 |             27.6 |             24.1 |
|        1 |        0 | Pass              | Sebastián Enzo Cáceres Ramos    |         27.6 |         24.1 |             37.8 |             27.4 |
|        1 |        0 | Ball Receipt*     | Jonathan dos Santos Ramírez     |         37.8 |         27.4 |            nan   |            nan   |
|        1 |        0 | Carries           | Jonathan dos Santos Ramírez     |         37.8 |         27.4 |             35.7 |             25.3 |
|        1 |        0 | Pass              | Jonathan dos Santos Ramírez     |         35.7 |         25.3 |             41.3 |              2.9 |
|        1 |        0 | Ball Receipt*     | Miguel Arturo Layún Prado       |         41.3 |          2.9 |            nan   |            nan   |
|        1 |        0 | Carries           | Miguel Arturo Layún Prado       |         41.3 |          2.9 |             38.6 |              9.3 |
|        1 |        0 | Pressure          | Diego Chávez Collins            |         77.8 |         73.1 |            nan   |            nan   |
|        1 |        0 | Pass              | Miguel Arturo Layún Prado       |         38.6 |          9.3 |             33.2 |              4.3 |
|        1 |        0 | Ball Receipt*     | Jonathan dos Santos Ramírez     |         33.2 |          4.3 |            nan   |            nan   |
|        1 |        0 | Carries           | Jonathan dos Santos Ramírez     |         33.2 |          4.3 |             32.2 |              3.7 |
|        1 |        0 | Pass              | Jonathan dos Santos Ramírez     |         32.2 |          3.7 |             17   |             16   |
|        1 |        0 | Ball Receipt*     | Sebastián Enzo Cáceres Ramos    |         17   |         16   |            nan   |            nan   |
|        1 |        0 | Carries           | Sebastián Enzo Cáceres Ramos    |         17   |         16   |             15.7 |             20.7 |
|        1 |        0 | Pass              | Sebastián Enzo Cáceres Ramos    |         15.7 |         20.7 |              7   |             46.3 |
|        1 |        0 | Ball Receipt*     | Óscar Francisco Jiménez Fabela  |          7   |         46.3 |            nan   |            nan   |
|        1 |        0 | Carries           | Óscar Francisco Jiménez Fabela  |          7   |         46.3 |              7.2 |             46.3 |
|        1 |        0 | Pass              | Óscar Francisco Jiménez Fabela  |          7.2 |         46.3 |             15   |             59.4 |
|        1 |        0 | Ball Receipt*     | Néstor Alejandro Araújo Razo    |         15   |         59.4 |            nan   |            nan   |
|        1 |        0 | Carries           | Néstor Alejandro Araújo Razo    |         15   |         59.4 |             16.2 |             60.4 |
|        1 |        0 | Pressure          | Aitor García Flores             |        101.2 |         22.1 |            nan   |            nan   |

In [41]:
passes_test = match_test[
    match_test["event_type_name"] == "Pass"
].copy()

print("\nPases por periodo:")
print(
    passes_test
    .groupby("period")
    [["location_x", "end_location_x"]]
    .agg(["min", "mean", "max"]).to_markdown()
)

Pases por periodo:
|   period |   ('location_x', 'min') |   ('location_x', 'mean') |   ('location_x', 'max') |   ('end_location_x', 'min') |   ('end_location_x', 'mean') |   ('end_location_x', 'max') |
|---------:|------------------------:|-------------------------:|------------------------:|----------------------------:|-----------------------------:|----------------------------:|
|        1 |                     6   |                  55.9326 |                     120 |                         6.2 |                      59.3264 |                         120 |
|        2 |                     4.6 |                  57.4817 |                     120 |                         5   |                      61.5598 |                         120 |

In [42]:
[
    col for col in events.columns
    if any(
        term in col.lower()
        for term in ["angle", "direction", "orientation", "rotation"]
    )
]

['pass_angle', 'attacking_direction']

In [43]:
[
    col for col in events.columns
    if col.startswith("pass_")
]

['pass_recipient_id',
 'pass_recipient_name',
 'pass_length',
 'pass_angle',
 'pass_height_id',
 'pass_height_name',
 'pass_cross',
 'pass_cut_back',
 'pass_switch',
 'pass_cluster_id',
 'pass_cluster_label',
 'pass_cluster_probability',
 'pass_success_probability']

Analizamos la variable attacking_directions

In [44]:
print(
    team_events["attacking_direction"]
    .value_counts(dropna=False).to_markdown()
)

| attacking_direction   |   count |
|:----------------------|--------:|
| right_to_left         |  136948 |
| left_to_right         |  134829 |
| nan                   |     368 |

In [45]:
print(
    team_events
    .groupby(["match_id", "period"])["attacking_direction"]
    .first()
    .value_counts(dropna=False).to_markdown()
)

| attacking_direction   |   count |
|:----------------------|--------:|
| left_to_right         |     133 |
| right_to_left         |     132 |

Evaluaremos entonces cuál es la progresión de los pases

In [46]:
passes_progression = passes.copy()

In [47]:
passes_progression = passes_progression.dropna(
    subset=[
        "location_x",
        "end_location_x",
        "attacking_direction"
    ]
)

In [48]:
passes_progression["progression_x"] = np.where(
    passes_progression["attacking_direction"] == "left_to_right",
    passes_progression["end_location_x"] -
        passes_progression["location_x"],
    passes_progression["location_x"] -
        passes_progression["end_location_x"]
)

In [49]:
print(
    passes_progression[
        [
            "match_id",
            "player_name",
            "attacking_direction",
            "location_x",
            "end_location_x",
            "progression_x"
        ]
    ].head(20).to_markdown()
)

|    |   match_id | player_name                     | attacking_direction   |   location_x |   end_location_x |   progression_x |
|---:|-----------:|:--------------------------------|:----------------------|-------------:|-----------------:|----------------:|
|  4 |    3889637 | Román Martínez                  | right_to_left         |         61   |             47.8 |            13.2 |
|  6 |    3889637 | Jonathan dos Santos Ramírez     | right_to_left         |         47.6 |             46.5 |             1.1 |
|  8 |    3889637 | Richard Rafael Sánchez Guerrero | right_to_left         |         45.9 |             39.7 |             6.2 |
| 11 |    3889637 | Kevin Nahin Álvarez Campos      | right_to_left         |         39.7 |             27.6 |            12.1 |
| 14 |    3889637 | Sebastián Enzo Cáceres Ramos    | right_to_left         |         27.6 |             37.8 |           -10.2 |
| 17 |    3889637 | Jonathan dos Santos Ramírez     | right_to_left         |         35.7 |             41.3 |            -5.6 |
| 21 |    3889637 | Miguel Arturo Layún Prado       | right_to_left         |         38.6 |             33.2 |             5.4 |
| 24 |    3889637 | Jonathan dos Santos Ramírez     | right_to_left         |         32.2 |             17   |            15.2 |
| 27 |    3889637 | Sebastián Enzo Cáceres Ramos    | right_to_left         |         15.7 |              7   |             8.7 |
| 30 |    3889637 | Óscar Francisco Jiménez Fabela  | right_to_left         |          7.2 |             15   |            -7.8 |
| 34 |    3889637 | Néstor Alejandro Araújo Razo    | right_to_left         |         16.2 |             46.3 |           -30.1 |
| 37 |    3889637 | Leonardo Gabriel Suárez         | right_to_left         |         44.2 |             36.1 |             8.1 |
| 39 |    3889637 | Jonathan dos Santos Ramírez     | right_to_left         |         36.8 |             41.3 |            -4.5 |
| 42 |    3889637 | Miguel Arturo Layún Prado       | right_to_left         |         42   |             55.1 |           -13.1 |
| 45 |    3889637 | Diego Alfonso Valdés Contreras  | right_to_left         |         55   |             57.5 |            -2.5 |
| 47 |    3889637 | Paul Brian Rodríguez Bravo      | right_to_left         |         57.3 |             43.4 |            13.9 |
| 50 |    3889637 | Miguel Arturo Layún Prado       | right_to_left         |         44   |             83.1 |           -39.1 |
| 54 |    3889637 | Kevin Nahin Álvarez Campos      | right_to_left         |         87.5 |             99.1 |           -11.6 |
| 58 |    3889637 | Román Martínez                  | right_to_left         |         97   |             81.4 |            15.6 |
| 61 |    3889637 | Jonathan dos Santos Ramírez     | right_to_left         |         83.3 |             94.9 |           -11.6 |

In [50]:
print(
    passes_progression["progression_x"].describe(
        percentiles=[.10, .25, .50, .75, .90]
    )
)

count    69255.000000
mean         0.055819
std         17.923124
min       -105.700000
10%        -18.200000
25%         -9.200000
50%          0.000000
75%          9.300000
90%         18.400000
max        106.300000
Name: progression_x, dtype: float64

In [51]:
print(
    "Pases hacia adelante:",
    (passes_progression["progression_x"] > 0).mean()
)

Pases hacia adelante: 0.49561764493538374

In [52]:
print(
    "Pases hacia atrás:",
    (passes_progression["progression_x"] < 0).mean()
)

Pases hacia atrás: 0.4951700238249946

Encontramos una distribución casi simétrica de los resultados.\
Por lo cual, nuestro siguiente paso es filtrar pases que no sean de tipo progresivo.

In [53]:
## Identificamos el largo de la cancha
bins = [-120, -30, -15, -5, 5, 15, 30, 120]

In [54]:
labels = [
    "Muy hacia atrás",
    "Hacia atrás",
    "Casi neutro negativo",
    "Neutro",
    "Casi neutro positivo",
    "Hacia adelante",
    "Muy hacia adelante"
]

In [55]:
passes_progression["progression_zone"] = pd.cut(
    passes_progression["progression_x"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [56]:
progression_distribution = (
    passes_progression["progression_zone"]
    .value_counts(sort=False)
    .to_frame("passes")
)
print(progression_distribution.sort_values(by='passes', ascending=False).to_markdown())

| progression_zone     |   passes |
|:---------------------|---------:|
| Neutro               |    18939 |
| Casi neutro positivo |    15627 |
| Casi neutro negativo |    15588 |
| Hacia adelante       |     7008 |
| Hacia atrás          |     6874 |
| Muy hacia atrás      |     2626 |
| Muy hacia adelante   |     2593 |

In [57]:
progression_distribution["percentage"] = (
    progression_distribution["passes"]
    / len(passes_progression)
    * 100
)
print(progression_distribution.round(2).sort_values(by='passes', ascending=False).to_markdown())

| progression_zone     |   passes |   percentage |
|:---------------------|---------:|-------------:|
| Neutro               |    18939 |        27.35 |
| Casi neutro positivo |    15627 |        22.56 |
| Casi neutro negativo |    15588 |        22.51 |
| Hacia adelante       |     7008 |        10.12 |
| Hacia atrás          |     6874 |         9.93 |
| Muy hacia atrás      |     2626 |         3.79 |
| Muy hacia adelante   |     2593 |         3.74 |

Definimos nuevamente el rango de pases en función del campo de juego del equipo

In [58]:
bins_2 = [0, 30, 60, 90, 120]

In [59]:
labels_2 = [
    "Defensiva",
    "Construcción",
    "Progresión",
    "Último tercio"
]

In [60]:
passes_progression["origin_zone"] = pd.cut(
    passes_progression["location_x"],
    bins=bins_2,
    labels=labels_2,
    include_lowest=True
)

In [61]:
zone_progression = (
    passes_progression
    .groupby("origin_zone", observed=True)
    .agg(
        passes=("progression_x", "count"),
        mean_progression=("progression_x", "mean"),
        median_progression=("progression_x", "median")
    )
    .reset_index()
)

In [62]:
print(zone_progression.round(2).sort_values(by='passes', ascending=False).to_markdown())

|    | origin_zone   |   passes |   mean_progression |   median_progression |
|---:|:--------------|---------:|-------------------:|---------------------:|
|  1 | Construcción  |    23613 |              -0.21 |                -0.2  |
|  2 | Progresión    |    23176 |               0.26 |                 0.17 |
|  0 | Defensiva     |    12161 |               0.3  |                 0.3  |
|  3 | Último tercio |    10305 |              -0.08 |                 0    |

In [63]:
passes_progression["significant_progression"] = (
    passes_progression["progression_x"] >= 15
)

passes_progression["significant_progression"]

4         False
6         False
8         False
11        False
14        False
          ...
501316    False
501320    False
501323    False
501326     True
501329     True
Name: significant_progression, Length: 69255, dtype: bool

In [64]:
significant_by_zone = (
    passes_progression
    .groupby("origin_zone", observed=True)
    .agg(
        total_passes=("progression_x", "count"),
        progressive_passes=("significant_progression", "sum")
    )
    .reset_index()
)

In [65]:
significant_by_zone["progressive_pct"] = (
    significant_by_zone["progressive_passes"]
    / significant_by_zone["total_passes"]
    * 100
)

In [66]:
print(significant_by_zone.round(2).to_markdown())

|    | origin_zone   |   total_passes |   progressive_passes |   progressive_pct |
|---:|:--------------|---------------:|---------------------:|------------------:|
|  0 | Defensiva     |          12161 |                 2685 |             22.08 |
|  1 | Construcción  |          23613 |                 3400 |             14.4  |
|  2 | Progresión    |          23176 |                 2859 |             12.34 |
|  3 | Último tercio |          10305 |                  749 |              7.27 |

 Ahora identificamos los pases de acuerdo a la zona de destino

In [67]:
passes_progression["destination_zone"] = pd.cut(
    passes_progression["end_location_x"],
    bins=bins_2,
    labels=labels_2,
    include_lowest=True
)

In [68]:
progression_zones = (
    passes_progression[
        passes_progression["progression_x"] >= 15
    ]
    .groupby(
        ["origin_zone", "destination_zone"],
        observed=True
    )
    .size()
    .reset_index(name="progressive_passes")
)

print(progression_zones.to_markdown())

|    | origin_zone   | destination_zone   |   progressive_passes |
|---:|:--------------|:-------------------|---------------------:|
|  0 | Defensiva     | Defensiva          |                  475 |
|  1 | Defensiva     | Construcción       |                 1457 |
|  2 | Defensiva     | Progresión         |                  635 |
|  3 | Defensiva     | Último tercio      |                  118 |
|  4 | Construcción  | Defensiva          |                  699 |
|  5 | Construcción  | Construcción       |                  760 |
|  6 | Construcción  | Progresión         |                 1602 |
|  7 | Construcción  | Último tercio      |                  339 |
|  8 | Progresión    | Defensiva          |                   47 |
|  9 | Progresión    | Construcción       |                  797 |
| 10 | Progresión    | Progresión         |                  766 |
| 11 | Progresión    | Último tercio      |                 1249 |
| 12 | Último tercio | Construcción       |                    7 |
| 13 | Último tercio | Progresión         |                  265 |
| 14 | Último tercio | Último tercio      |                  477 |

Sin embargo, es importante definir el destino de los pases progresivos

In [69]:
progression_zones["pct_from_origin"] = (
    progression_zones
    .groupby("origin_zone")["progressive_passes"]
    .transform(lambda x: x / x.sum() * 100)
)

print(
    progression_zones
    .sort_values(
        ["origin_zone", "progressive_passes"],
        ascending=[True, False]
    )
    .round(2).to_markdown()
)

|    | origin_zone   | destination_zone   |   progressive_passes |   pct_from_origin |
|---:|:--------------|:-------------------|---------------------:|------------------:|
|  1 | Defensiva     | Construcción       |                 1457 |             54.26 |
|  2 | Defensiva     | Progresión         |                  635 |             23.65 |
|  0 | Defensiva     | Defensiva          |                  475 |             17.69 |
|  3 | Defensiva     | Último tercio      |                  118 |              4.39 |
|  6 | Construcción  | Progresión         |                 1602 |             47.12 |
|  5 | Construcción  | Construcción       |                  760 |             22.35 |
|  4 | Construcción  | Defensiva          |                  699 |             20.56 |
|  7 | Construcción  | Último tercio      |                  339 |              9.97 |
| 11 | Progresión    | Último tercio      |                 1249 |             43.69 |
|  9 | Progresión    | Construcción       |                  797 |             27.88 |
| 10 | Progresión    | Progresión         |                  766 |             26.79 |
|  8 | Progresión    | Defensiva          |                   47 |              1.64 |
| 14 | Último tercio | Último tercio      |                  477 |             63.68 |
| 13 | Último tercio | Progresión         |                  265 |             35.38 |
| 12 | Último tercio | Construcción       |                    7 |              0.93 |

/tmp/ipykernel_28079/3735276426.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("origin_zone")["progressive_passes"]

In [70]:
check = passes_progression[
    (passes_progression["progression_x"] >= 15) &
    (passes_progression["origin_zone"] == "Construcción") &
    (passes_progression["destination_zone"] == "Defensiva")
]

print(
    check[
        [
            "match_id",
            "period",
            "attacking_direction",
            "location_x",
            "end_location_x",
            "progression_x",
            "origin_zone",
            "destination_zone"
        ]
    ].head(15).to_markdown()
)

print("Total de casos:", len(check))

|      |   match_id |   period | attacking_direction   |   location_x |   end_location_x |   progression_x | origin_zone   | destination_zone   |
|-----:|-----------:|---------:|:----------------------|-------------:|-----------------:|----------------:|:--------------|:-------------------|
|   24 |    3889637 |        1 | right_to_left         |         32.2 |             17   |            15.2 | Construcción  | Defensiva          |
|   93 |    3889637 |        1 | right_to_left         |         38   |             22   |            16   | Construcción  | Defensiva          |
|  129 |    3889637 |        1 | right_to_left         |         36.7 |             11.6 |            25.1 | Construcción  | Defensiva          |
|  674 |    3889637 |        1 | right_to_left         |         52.7 |             26.3 |            26.4 | Construcción  | Defensiva          |
|  723 |    3889637 |        1 | right_to_left         |         56.1 |             28.2 |            27.9 | Construcción  | Defensiva          |
|  976 |    3889637 |        1 | right_to_left         |         51.5 |             26.1 |            25.4 | Construcción  | Defensiva          |
| 1143 |    3889637 |        1 | right_to_left         |         37.8 |             12.8 |            25   | Construcción  | Defensiva          |
| 1263 |    3889637 |        1 | right_to_left         |         44.2 |             28.2 |            16   | Construcción  | Defensiva          |
| 1508 |    3889637 |        1 | right_to_left         |         44.2 |             27.6 |            16.6 | Construcción  | Defensiva          |
| 6280 |    3889660 |        2 | right_to_left         |         39.1 |             14.8 |            24.3 | Construcción  | Defensiva          |
| 6437 |    3889660 |        2 | right_to_left         |         32   |             10.1 |            21.9 | Construcción  | Defensiva          |
| 7120 |    3889660 |        2 | right_to_left         |         43.8 |             26.1 |            17.7 | Construcción  | Defensiva          |
| 7132 |    3889660 |        2 | right_to_left         |         44.9 |             29   |            15.9 | Construcción  | Defensiva          |
| 7310 |    3889660 |        2 | right_to_left         |         41.1 |             25.1 |            16   | Construcción  | Defensiva          |
| 7404 |    3889660 |        2 | right_to_left         |         33.1 |             14.5 |            18.6 | Construcción  | Defensiva          |
Total de casos: 699

Normalizamos coordenadas longitudinales para establecer de manera correcta el avance del equipo en función de su posición en el campo.

In [71]:
passes_progression["start_x_norm"] = np.where(
    passes_progression["attacking_direction"] == "left_to_right",
    passes_progression["location_x"],
    120 - passes_progression["location_x"]
)

In [72]:
passes_progression["end_x_norm"] = np.where(
    passes_progression["attacking_direction"] == "left_to_right",
    passes_progression["end_location_x"],
    120 - passes_progression["end_location_x"]
)

In [73]:
passes_progression["progression_x_check"] = (
    passes_progression["end_x_norm"]
    - passes_progression["start_x_norm"]
)

In [74]:
print(
    passes_progression[
        ["progression_x", "progression_x_check"]
    ].describe().round(2).to_markdown()
)

|       |   progression_x |   progression_x_check |
|:------|----------------:|----------------------:|
| count |        69255    |              69255    |
| mean  |            0.06 |                  0.06 |
| std   |           17.92 |                 17.92 |
| min   |         -105.7  |               -105.7  |
| 25%   |           -9.2  |                 -9.2  |
| 50%   |            0    |                  0    |
| 75%   |            9.3  |                  9.3  |
| max   |          106.3  |                106.3  |

In [75]:
print(
    "Diferencias entre cálculos:",
    (
        passes_progression["progression_x"]
        - passes_progression["progression_x_check"]
    ).abs().gt(0.01).sum()
)

Diferencias entre cálculos: 0

Recalculamos en base a datos normalizaodos

In [76]:
bins_x = [0, 30, 60, 90, 120]

labels_x = [
    "Defensiva",
    "Construcción",
    "Progresión",
    "Último tercio"
]

In [77]:
passes_progression["origin_zone"] = pd.cut(
    passes_progression["start_x_norm"],
    bins=bins_x,
    labels=labels_x,
    include_lowest=True
)

passes_progression["destination_zone"] = pd.cut(
    passes_progression["end_x_norm"],
    bins=bins_x,
    labels=labels_x,
    include_lowest=True
)

In [78]:
# para checar posibles contradicciones que pudiera tener la normalización
check = passes_progression[
    (passes_progression["progression_x"] >= 15) &
    (
        passes_progression["destination_zone"].map(
            {label: i for i, label in enumerate(labels_x)}
        )
        <
        passes_progression["origin_zone"].map(
            {label: i for i, label in enumerate(labels_x)}
        )
    )
]

In [79]:
print("Pases >=15 m que retroceden de zona:", len(check))

Pases >=15 m que retroceden de zona: 0

In [80]:
progression_zones = (
    passes_progression[
        passes_progression["progression_x"] >= 15
    ]
    .groupby(
        ["origin_zone", "destination_zone"],
        observed=True
    )
    .size()
    .reset_index(name="progressive_passes")
)

In [81]:
progression_zones["pct_from_origin"] = (
    progression_zones["progressive_passes"]
    / progression_zones.groupby("origin_zone")[
        "progressive_passes"
    ].transform("sum")
    * 100
)

/tmp/ipykernel_28079/1968090656.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  / progression_zones.groupby("origin_zone")[

In [82]:
print(
    progression_zones
    .sort_values(
        ["origin_zone", "progressive_passes"],
        ascending=[True, False]
    )
    .round(2)
    .to_markdown()
)

|    | origin_zone   | destination_zone   |   progressive_passes |   pct_from_origin |
|---:|:--------------|:-------------------|---------------------:|------------------:|
|  1 | Defensiva     | Construcción       |                 1724 |             60.96 |
|  2 | Defensiva     | Progresión         |                  642 |             22.7  |
|  0 | Defensiva     | Defensiva          |                  344 |             12.16 |
|  3 | Defensiva     | Último tercio      |                  118 |              4.17 |
|  5 | Construcción  | Progresión         |                 2402 |             68.69 |
|  4 | Construcción  | Construcción       |                  709 |             20.27 |
|  6 | Construcción  | Último tercio      |                  386 |             11.04 |
|  8 | Progresión    | Último tercio      |                 1952 |             70.6  |
|  7 | Progresión    | Progresión         |                  813 |             29.4  |
|  9 | Último tercio | Último tercio      |                  603 |            100    |

En base a los resultados podemos señalar:
- La mayoría de los pases mayores a 15 m de la zona defensiva se generan hacia la zona de construcción (60.96%)
- Esa misma tendencia se observa desde la zona de construcción a la de progresión (68.96%)
- La conexión más frecuente de los pases desde la zona de progresión es hacia el último tercio (70.60%)
- Los resultados nos muestran una construcción de juego escalonado
 $$ \text{Zona defensiva} → \text{Construcción} → \text{Progresión} → \text{Último tercio}$$

 Intentaremos entonces validar la recepción del pase por parte del equipo

In [83]:
cols_check = [
    c for c in events.columns
    if any(term in c.lower() for term in [
        "pass_outcome", "receipt", "outcome",
        "recipient", "possession", "index",
        "event_type", "team_name", "player_name"
    ])
]

In [84]:
print("Columnas relevantes:")
print(cols_check)

Columnas relevantes:
['index', 'event_type_id', 'event_type_name', 'possession', 'possession_team_id', 'possession_team_name', 'team_name', 'player_name', 'substituted_player_name', 'pass_recipient_id', 'pass_recipient_name', 'outcome_id', 'outcome_name', 'freeze_frame_player_name', 'formation_player_name', 'is_controlled_possession', 'player_possession_directness', 'possession_directness']

In [85]:
print("\nTipos de evento:")
print(
    events.loc[
        events["possession_team_id"] == TEAM_ID,
        "event_type_name"
    ].value_counts().head(20).to_markdown()
)

Tipos de evento:
| event_type_name   |   count |
|:------------------|--------:|
| Pass              |   69255 |
| Ball Receipt*     |   64377 |
| Carries           |   57144 |
| Shot              |   26258 |
| Pressure          |   22089 |
| Ball Recovery     |    5865 |
| Duel              |    3800 |
| Tactical Shift    |    3077 |
| Clearance         |    2404 |
| Block             |    2265 |
| Goal Keeper       |    2106 |
| Dribble           |    1886 |
| Foul Committed    |    1828 |
| Miscontrol        |    1776 |
| Foul Won          |    1746 |
| Dispossessed      |    1627 |
| Dribbled Past     |    1100 |
| Interception      |     970 |
| Substitution      |     653 |
| Injury Stoppage   |     475 |

In [86]:
cols_sample = [
    c for c in [
        "match_id", "index", "possession", "event_type_name",
        "team_name", "player_name", "pass_recipient_name",
        "pass_outcome_name", "location_x", "end_location_x"
    ]
    if c in events.columns
]

In [87]:
print("\nEjemplo de pases con avance >= 15:")
print(
    passes_progression.loc[
        passes_progression["progression_x"] >= 15,
        [c for c in cols_sample if c in passes_progression.columns]
    ].head(10).to_markdown()
)

Ejemplo de pases con avance >= 15:
|     |   match_id |   index |   possession | event_type_name   | team_name   | player_name                    | pass_recipient_name             |   location_x |   end_location_x |
|----:|-----------:|--------:|-------------:|:------------------|:------------|:-------------------------------|:--------------------------------|-------------:|-----------------:|
|  24 |    3889637 |      25 |            2 | Pass              | América     | Jonathan dos Santos Ramírez    | Sebastián Enzo Cáceres Ramos    |         32.2 |             17   |
|  58 |    3889637 |      59 |            2 | Pass              | América     | Román Martínez                 | Jonathan dos Santos Ramírez     |         97   |             81.4 |
|  93 |    3889637 |      94 |            4 | Pass              | América     | Jonathan dos Santos Ramírez    | Sebastián Enzo Cáceres Ramos    |         38   |             22   |
| 129 |    3889637 |     130 |            5 | Pass              | América     | Néstor Alejandro Araújo Razo   | Óscar Francisco Jiménez Fabela  |         36.7 |             11.6 |
| 168 |    3889637 |     169 |            5 | Pass              | América     | Miguel Arturo Layún Prado      | Richard Rafael Sánchez Guerrero |         62.8 |             37.6 |
| 181 |    3889637 |     182 |            5 | Pass              | América     | Miguel Arturo Layún Prado      | Sebastián Enzo Cáceres Ramos    |         69.4 |             51.3 |
| 221 |    3889637 |     222 |            5 | Pass              | América     | Román Martínez                 | Néstor Alejandro Araújo Razo    |         97.4 |             74.7 |
| 300 |    3889637 |     301 |            7 | Pass              | América     | Román Martínez                 | Leonardo Gabriel Suárez         |        102   |             83.7 |
| 310 |    3889637 |     311 |            8 | Pass              | América     | Leonardo Gabriel Suárez        | Kevin Nahin Álvarez Campos      |        120   |             88.3 |
| 365 |    3889637 |     366 |           10 | Pass              | América     | Diego Alfonso Valdés Contreras | Jonathan dos Santos Ramírez     |         66.9 |             51.3 |

In [88]:
receipts = events[
    events["event_type_name"].astype(str).str.contains(
        "Ball Receipt", case=False, na=False
    )
]

print("\nEventos de recepción:", len(receipts))
print(receipts[cols_sample].head(10).to_markdown())

Eventos de recepción: 116392
|    |   match_id |   index |   possession | event_type_name   | team_name   | player_name                     |   pass_recipient_name |   location_x |   end_location_x |
|---:|-----------:|--------:|-------------:|:------------------|:------------|:--------------------------------|----------------------:|-------------:|-----------------:|
|  5 |    3889637 |       6 |            2 | Ball Receipt*     | América     | Jonathan dos Santos Ramírez     |                   nan |         47.8 |              nan |
|  7 |    3889637 |       8 |            2 | Ball Receipt*     | América     | Richard Rafael Sánchez Guerrero |                   nan |         46.5 |              nan |
|  9 |    3889637 |      10 |            2 | Ball Receipt*     | América     | Kevin Nahin Álvarez Campos      |                   nan |         39.7 |              nan |
| 12 |    3889637 |      13 |            2 | Ball Receipt*     | América     | Sebastián Enzo Cáceres Ramos    |                   nan |         27.6 |              nan |
| 15 |    3889637 |      16 |            2 | Ball Receipt*     | América     | Jonathan dos Santos Ramírez     |                   nan |         37.8 |              nan |
| 18 |    3889637 |      19 |            2 | Ball Receipt*     | América     | Miguel Arturo Layún Prado       |                   nan |         41.3 |              nan |
| 22 |    3889637 |      23 |            2 | Ball Receipt*     | América     | Jonathan dos Santos Ramírez     |                   nan |         33.2 |              nan |
| 25 |    3889637 |      26 |            2 | Ball Receipt*     | América     | Sebastián Enzo Cáceres Ramos    |                   nan |         17   |              nan |
| 28 |    3889637 |      29 |            2 | Ball Receipt*     | América     | Óscar Francisco Jiménez Fabela  |                   nan |          7   |              nan |
| 31 |    3889637 |      32 |            2 | Ball Receipt*     | América     | Néstor Alejandro Araújo Razo    |                   nan |         15   |              nan |

In [89]:
# Orden cronológico de los eventos
ev = events.sort_values(["match_id", "index"]).copy()

In [90]:
# Inspeccionar outcome_name en las recepciones
receipts = ev[ev["event_type_name"] == "Ball Receipt*"]


print("Resultados registrados en Ball Receipt*:")
if "outcome_name" in receipts.columns:
    print(receipts["outcome_name"].value_counts(dropna=False).head(10).to_markdown())

Resultados registrados en Ball Receipt*:
| outcome_name   |   count |
|:---------------|--------:|
| nan            |  105266 |
| Incomplete     |   11126 |

In [91]:
group_cols = ["match_id", "possession"]

for col in ["event_type_name", "team_name", "player_name"]:
    ev[f"next_{col}"] = ev.groupby(group_cols)[col].shift(-1)

ev.head()

,id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,...,america_score,opponent_score,coach,stadium,match_status,match_status_360,result,next_event_type_name,next_team_name,next_player_name
0,ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,...,1,2,André Soares Jardine,Estadio Azteca,available,available,L,Starting XI,América,NaN
4163,ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,...,1,2,André Soares Jardine,Estadio Azteca,available,available,L,Starting XI,América,NaN
4164,ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,...,1,2,André Soares Jardine,Estadio Azteca,available,available,L,Starting XI,América,NaN
4165,ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,...,1,2,André Soares Jardine,Estadio Azteca,available,available,L,Starting XI,América,NaN
4166,ab861d54-b8b8-575b-ad0a-305b4798cede,1,3889637,1,00:00,0,0,35,Starting XI,1,...,1,2,André Soares Jardine,Estadio Azteca,available,available,L,Starting XI,América,NaN

In [92]:
# Comparar pase y evento inmediatamente posterior
pass_events = ev[ev["event_type_name"] == "Pass"].copy()

In [93]:
pass_events["next_is_receipt"] = (
    pass_events["next_event_type_name"] == "Ball Receipt*"
)

In [94]:
pass_events["recipient_matches"] = (
    pass_events["pass_recipient_name"].notna()
    & pass_events["next_is_receipt"]
    & (
        pass_events["pass_recipient_name"]
        == pass_events["next_player_name"]
    )
)

# pass_events["recipient_matches"]

In [95]:
print("\nValidación de todos los pases del equipo:")
print("Total de pases:", len(pass_events))
print("Seguidos inmediatamente por Ball Receipt*:",
      pass_events["next_is_receipt"].sum())
print("Recepción con destinatario coincidente:",
      pass_events["recipient_matches"].sum())

Validación de todos los pases del equipo:
Total de pases: 126618
Seguidos inmediatamente por Ball Receipt*: 103604
Recepción con destinatario coincidente: 103604

In [96]:
# Aplicar el análisis a los pases con avance >= 15
progressive_ids = passes_progression.loc[
    passes_progression["progression_x"] >= 15,
    ["match_id", "index"]
].drop_duplicates()

In [97]:
progressive_check = pass_events.merge(
    progressive_ids.assign(selected_progression=True),
    on=["match_id", "index"],
    how="inner",
    validate="one_to_one"
)

In [98]:
print("\nPases con avance >= 15:")
print("Total:", len(progressive_check))
print("Seguidos por Ball Receipt*:",
      progressive_check["next_is_receipt"].sum())
print("Recepción con destinatario coincidente:",
      progressive_check["recipient_matches"].sum())

Pases con avance >= 15:
Total: 9693
Seguidos por Ball Receipt*: 7353
Recepción con destinatario coincidente: 7353

In [99]:
print(
    progressive_check[
        [
            "match_id", "index", "possession",
            "player_name", "pass_recipient_name",
            "next_event_type_name", "next_player_name",
            "next_is_receipt", "recipient_matches"
        ]
    ].head(15).to_markdown()
)

|    |   match_id |   index |   possession | player_name                    | pass_recipient_name             | next_event_type_name   | next_player_name                | next_is_receipt   | recipient_matches   |
|---:|-----------:|--------:|-------------:|:-------------------------------|:--------------------------------|:-----------------------|:--------------------------------|:------------------|:--------------------|
|  0 |    3889637 |      25 |            2 | Jonathan dos Santos Ramírez    | Sebastián Enzo Cáceres Ramos    | Ball Receipt*          | Sebastián Enzo Cáceres Ramos    | True              | True                |
|  1 |    3889637 |      59 |            2 | Román Martínez                 | Jonathan dos Santos Ramírez     | Pressure               | Diego Chávez Collins            | False             | False               |
|  2 |    3889637 |      94 |            4 | Jonathan dos Santos Ramírez    | Sebastián Enzo Cáceres Ramos    | Ball Receipt*          | Sebastián Enzo Cáceres Ramos    | True              | True                |
|  3 |    3889637 |     130 |            5 | Néstor Alejandro Araújo Razo   | Óscar Francisco Jiménez Fabela  | Ball Receipt*          | Óscar Francisco Jiménez Fabela  | True              | True                |
|  4 |    3889637 |     169 |            5 | Miguel Arturo Layún Prado      | Richard Rafael Sánchez Guerrero | Ball Receipt*          | Richard Rafael Sánchez Guerrero | True              | True                |
|  5 |    3889637 |     182 |            5 | Miguel Arturo Layún Prado      | Sebastián Enzo Cáceres Ramos    | Ball Receipt*          | Sebastián Enzo Cáceres Ramos    | True              | True                |
|  6 |    3889637 |     222 |            5 | Román Martínez                 | Néstor Alejandro Araújo Razo    | Ball Receipt*          | Néstor Alejandro Araújo Razo    | True              | True                |
|  7 |    3889637 |     301 |            7 | Román Martínez                 | Leonardo Gabriel Suárez         | Ball Receipt*          | Leonardo Gabriel Suárez         | True              | True                |
|  8 |    3889637 |     311 |            8 | Leonardo Gabriel Suárez        | Kevin Nahin Álvarez Campos      | Ball Receipt*          | Kevin Nahin Álvarez Campos      | True              | True                |
|  9 |    3889637 |     366 |           10 | Diego Alfonso Valdés Contreras | Jonathan dos Santos Ramírez     | Ball Receipt*          | Jonathan dos Santos Ramírez     | True              | True                |
| 10 |    3889637 |     408 |           14 | Sebastián Saucedo Mondragón    | Aitor García Flores             | Ball Receipt*          | Aitor García Flores             | True              | True                |
| 11 |    3889637 |     594 |           24 | Leonardo Gabriel Suárez        | Sebastián Enzo Cáceres Ramos    | Ball Receipt*          | Sebastián Enzo Cáceres Ramos    | True              | True                |
| 12 |    3889637 |     659 |           27 | Leonardo Gabriel Suárez        | Néstor Alejandro Araújo Razo    | Ball Receipt*          | Néstor Alejandro Araújo Razo    | True              | True                |
| 13 |    3889637 |     675 |           27 | Kevin Nahin Álvarez Campos     | Néstor Alejandro Araújo Razo    | Ball Receipt*          | Néstor Alejandro Araújo Razo    | True              | True                |
| 14 |    3889637 |     724 |           30 | Diego Alfonso Valdés Contreras | Néstor Alejandro Araújo Razo    | Ball Receipt*          | Néstor Alejandro Araújo Razo    | True              | True                |

In [100]:
progressive_check.next_event_type_name.unique()

array(['Ball Receipt*', 'Pressure', nan, 'Substitution', 'Tactical Shift',
       'Duel', 'Clearance', 'Player On', 'Pass', 'Foul Committed',
       'Goal Keeper', 'Ball Recovery', 'Interception', 'Shield', 'Block',
       'Injury Stoppage', 'Referee Ball-Drop', 'Player Off'], dtype=object)

In [101]:
# Ordenar eventos y trabajar con posesiones de América
ev = events.sort_values(["match_id", "index"]).copy()

In [102]:
ev_america_possessions = ev[
    ev["possession_team_id"] == TEAM_ID
].copy()

ev_america_possessions.head()

,id,index,match_id,period,timestamp,minute,second,event_type_id,event_type_name,possession,...,match_week,opponent,venue,america_score,opponent_score,coach,stadium,match_status,match_status_360,result
4,7d53e561-53d8-51db-9e4e-3ca9427cc059,5,3889637,1,00:00:00.044,0,0,30,Pass,2,...,1,Juárez,Home,1,2,André Soares Jardine,Estadio Azteca,available,available,L
5,5630a90f-4dff-5016-951d-1505c2cb1ca5,6,3889637,1,00:00:02.268,0,2,42,Ball Receipt*,2,...,1,Juárez,Home,1,2,André Soares Jardine,Estadio Azteca,available,available,L
6,1344c9dc-12fd-52ed-b80f-ec70d507b891,7,3889637,1,00:00:02.598,0,2,30,Pass,2,...,1,Juárez,Home,1,2,André Soares Jardine,Estadio Azteca,available,available,L
7,fd85acee-75f9-5918-8db0-2c246f5589a7,8,3889637,1,00:00:03.440,0,3,42,Ball Receipt*,2,...,1,Juárez,Home,1,2,André Soares Jardine,Estadio Azteca,available,available,L
8,17d605bc-ed2c-57e4-919d-4a16dc84eec0,9,3889637,1,00:00:04.310,0,4,30,Pass,2,...,1,Juárez,Home,1,2,André Soares Jardine,Estadio Azteca,available,available,L

In [103]:
# Pases seleccionados: avance longitudinal >= 15
selected = passes_progression.loc[
    passes_progression["progression_x"] >= 15,
    ["match_id", "index", "possession", "pass_recipient_name"]
].drop_duplicates(["match_id", "index"]).copy()

In [104]:
selected

        match_id  index  possession              pass_recipient_name
24       3889637     25           2     Sebastián Enzo Cáceres Ramos
58       3889637     59           2      Jonathan dos Santos Ramírez
93       3889637     94           4     Sebastián Enzo Cáceres Ramos
129      3889637    130           5   Óscar Francisco Jiménez Fabela
168      3889637    169           5  Richard Rafael Sánchez Guerrero
...          ...    ...         ...                              ...
501279   4057783   2750         167           Henry Josué Martín Mex
501292   4057783   2763         169       Paul Brian Rodríguez Bravo
501314   4057783   2785         171                              NaN
501326   4057783   2797         174      Miguel Ángel Vázquez García
501329   4057783   2800         174     Néstor Alejandro Araújo Razo

[9693 rows x 4 columns]

In [105]:
# Revisar cada pase hasta el siguiente pase de la misma posesión
event_groups = {
    key: group.reset_index(drop=True)
    for key, group in ev_america_possessions.groupby(
        ["match_id", "possession"], sort=False
    )
}

In [106]:
results = []

for row in selected.itertuples(index=False):
    key = (row.match_id, row.possession)
    group = event_groups.get(key)

    if group is None:
        results.append((False, False, 0))
        continue

    positions = group.index[group["index"] == row.index].tolist()

    if not positions:
        results.append((False, False, 0))
        continue

    pos = positions[0]
    following = group.iloc[pos + 1:]

    # Detenerse antes del siguiente pase
    next_pass_positions = following.index[
        following["event_type_name"] == "Pass"
    ].tolist()

    if next_pass_positions:
        following = following.loc[:next_pass_positions[0] - 1]

    receipt_events = following[
        following["event_type_name"] == "Ball Receipt*"
    ]

    recipient_found = (
        receipt_events["player_name"].eq(
            row.pass_recipient_name
        ).any()
        if pd.notna(row.pass_recipient_name)
        else False
    )

    results.append((
        len(receipt_events) > 0,
        recipient_found,
        len(following)
    ))

In [107]:
len(results)

9693

In [108]:
selected["receipt_before_next_pass"] = [r[0] for r in results]
selected["recipient_found"] = [r[1] for r in results]
selected["intermediate_events"] = [r[2] for r in results]

In [109]:
print("Pases seleccionados:", len(selected))
print(
    "Con recepción antes del siguiente pase:",
    selected["receipt_before_next_pass"].sum()
)
print(
    "Con recepción del destinatario esperado:",
    selected["recipient_found"].sum()
)

print("\nPorcentajes:")
print(
    (selected[
        ["receipt_before_next_pass", "recipient_found"]
    ].mean() * 100).round(2).rename("Porcentaje (%)").to_markdown()
)

Pases seleccionados: 9693
Con recepción antes del siguiente pase: 8604
Con recepción del destinatario esperado: 8604

Porcentajes:
|                          |   Porcentaje (%) |
|:-------------------------|-----------------:|
| receipt_before_next_pass |            88.77 |
| recipient_found          |            88.77 |

In [110]:
print("\nCasos con eventos intermedios:")
print(
    selected.loc[
        selected["intermediate_events"] > 0,
        [
            "match_id", "index", "possession",
            "pass_recipient_name", "receipt_before_next_pass",
            "recipient_found", "intermediate_events"
        ]
    ].head(15).to_markdown()
)

Casos con eventos intermedios:
|     |   match_id |   index |   possession | pass_recipient_name             | receipt_before_next_pass   | recipient_found   |   intermediate_events |
|----:|-----------:|--------:|-------------:|:--------------------------------|:---------------------------|:------------------|----------------------:|
|  24 |    3889637 |      25 |            2 | Sebastián Enzo Cáceres Ramos    | True                       | True              |                     2 |
|  58 |    3889637 |      59 |            2 | Jonathan dos Santos Ramírez     | True                       | True              |                     2 |
|  93 |    3889637 |      94 |            4 | Sebastián Enzo Cáceres Ramos    | True                       | True              |                     2 |
| 129 |    3889637 |     130 |            5 | Óscar Francisco Jiménez Fabela  | True                       | True              |                     1 |
| 168 |    3889637 |     169 |            5 | Richard Rafael Sánchez Guerrero | True                       | True              |                     2 |
| 181 |    3889637 |     182 |            5 | Sebastián Enzo Cáceres Ramos    | True                       | True              |                     1 |
| 221 |    3889637 |     222 |            5 | Néstor Alejandro Araújo Razo    | True                       | True              |                     2 |
| 300 |    3889637 |     301 |            7 | Leonardo Gabriel Suárez         | True                       | True              |                     2 |
| 310 |    3889637 |     311 |            8 | Kevin Nahin Álvarez Campos      | True                       | True              |                     2 |
| 365 |    3889637 |     366 |           10 | Jonathan dos Santos Ramírez     | True                       | True              |                     3 |
| 407 |    3889637 |     408 |           14 | Aitor García Flores             | True                       | True              |                     2 |
| 593 |    3889637 |     594 |           24 | Sebastián Enzo Cáceres Ramos    | True                       | True              |                     1 |
| 658 |    3889637 |     659 |           27 | Néstor Alejandro Araújo Razo    | True                       | True              |                     2 |
| 674 |    3889637 |     675 |           27 | Néstor Alejandro Araújo Razo    | True                       | True              |                     2 |
| 723 |    3889637 |     724 |           30 | Néstor Alejandro Araújo Razo    | True                       | True              |                     2 |

In [111]:
ev = events.sort_values(["match_id", "index"]).copy()
group_cols = ["match_id", "possession"]

# Siguiente evento de la misma posesión
ev["next_event_type"] = ev.groupby(group_cols)["event_type_name"].shift(-1)
ev["next_team"] = ev.groupby(group_cols)["team_name"].shift(-1)
ev["next_controlled"] = ev.groupby(group_cols)[
    "is_controlled_possession"
].shift(-1)

# Recepciones registradas en posesiones de, equipo
receipts = ev[
    (ev["event_type_name"] == "Ball Receipt*")
    & (ev["possession_team_name"] == "América")
].copy()

In [112]:
print("Total de recepciones:", len(receipts))

print("\nControl registrado en la recepción:")
print(
    receipts["is_controlled_possession"]
    .value_counts(dropna=False)
    .to_frame("eventos").to_markdown()
)

Total de recepciones: 64377

Control registrado en la recepción:
| is_controlled_possession   |   eventos |
|:---------------------------|----------:|
| True                       |     47133 |
| nan                        |     10285 |
| False                      |      4907 |
| true                       |       616 |
| midfield_third             |       572 |
| final_third                |       511 |
| defensive_third            |       229 |
| false                      |       124 |

In [113]:
receipts.is_controlled_possession.unique()

array([True, False, nan, 'true', 'false', 'midfield_third',
       'defensive_third', 'final_third'], dtype=object)

In [114]:
print("\nTipo de evento posterior:")
print(
    receipts["next_event_type"]
    .value_counts(dropna=False)
    .head(15)
    .to_frame("eventos").to_markdown()
)

print("\nEquipo que realiza el evento posterior:")
print(
    receipts["next_team"]
    .value_counts(dropna=False)
    .head(10)
    .to_frame("eventos").to_markdown()
)

print("\nControl registrado en el evento posterior:")
print(
    receipts["next_controlled"]
    .value_counts(dropna=False)
    .to_frame("eventos").to_markdown()
)

Tipo de evento posterior:
| next_event_type   |   eventos |
|:------------------|----------:|
| Carries           |     49856 |
| Pass              |      7561 |
| nan               |      3049 |
| Clearance         |       739 |
| Shot              |       548 |
| Block             |       520 |
| Interception      |       427 |
| Pressure          |       385 |
| Miscontrol        |       358 |
| Duel              |       314 |
| Ball Recovery     |       188 |
| Foul Committed    |       162 |
| Injury Stoppage   |        80 |
| Goal Keeper       |        43 |
| Substitution      |        39 |

Equipo que realiza el evento posterior:
| next_team     |   eventos |
|:--------------|----------:|
| América       |     58344 |
| nan           |      3049 |
| Cruz Azul     |       289 |
| Pachuca       |       271 |
| León          |       198 |
| Guadalajara   |       197 |
| Tigres UANL   |       192 |
| Toluca        |       191 |
| Atlas         |       177 |
| Santos Laguna |       176 |

Control registrado en el evento posterior:
| next_controlled   |   eventos |
|:------------------|----------:|
| True              |     43582 |
| nan               |     14761 |
| False             |      3918 |
| true              |       577 |
| midfield_third    |       561 |
| final_third       |       476 |
| defensive_third   |       240 |
| false             |       109 |
| 0.0054130321      |         1 |
| 0.0027381619      |         1 |
| 0.1485832334      |         1 |
| 0.0768486038      |         1 |
| 0.0084494688      |         1 |
| 0.0007041654      |         1 |
| 0.0030083121      |         1 |
| 0.0238522086      |         1 |
| 0.2366929948      |         1 |
| 0.0085523119      |         1 |
| 0.0002067431      |         1 |
| 0.0020427736      |         1 |
| 0.0010719136      |         1 |
| 0.0882825702      |         1 |
| 7.53324e-05       |         1 |
| 0.0062401593      |         1 |
| 0.0092911944      |         1 |
| 0.0005445215      |         1 |
| 0.0001995548      |         1 |
| 0.0209791176      |         1 |
| 0.0329577141      |         1 |
| 0.0046134177      |         1 |
| 8.4541e-06        |         1 |
| 0.0589727312      |         1 |
| 8.52705e-05       |         1 |
| 0.0014830473      |         1 |
| 0.0017478799      |         1 |
| 0.0001163316      |         1 |
| 0.0002664088      |         1 |
| 0.0011243118      |         1 |
| 0.0047332318      |         1 |
| 0.0695776194      |         1 |
| 0.1058434024      |         1 |
| 0.0001956712      |         1 |
| 0.0805866197      |         1 |
| 0.0088357842      |         1 |
| 0.0419679694      |         1 |
| 0.0053716563      |         1 |
| 0.001776827       |         1 |
| 0.0224002153      |         1 |
| 0.0017451613      |         1 |
| 0.0057995096      |         1 |
| 0.0079842051      |         1 |
| 0.036134053       |         1 |
| 0.0158353038      |         1 |
| 0.0110233808      |         1 |
| 0.0206824504      |         1 |
| 0.0071768751      |         1 |
| 0.0007347769      |         1 |
| 0.0045473874      |         1 |
| 0.0018597533      |         1 |
| 0.0005418148      |         1 |
| 0.0024411087      |         1 |
| 0.0383381881      |         1 |
| 0.0008030591      |         1 |
| 0.0156660173      |         1 |
| 0.0010539362      |         1 |
| 0.0017661401      |         1 |
| 0.000479205       |         1 |
| 0.0011937824      |         1 |
| 0.0032887768      |         1 |
| 0.0134541672      |         1 |
| 0.0127570555      |         1 |
| 0.0008705084      |         1 |
| 0.007825979       |         1 |
| 0.0181988161      |         1 |
| 0.0008828431      |         1 |
| 0.0006328153      |         1 |
| 0.0497816615      |         1 |
| 0.0027250513      |         1 |
| 0.0050625363      |         1 |
| 0.0072628227      |         1 |
| 0.002703415       |         1 |
| 0.0012440882      |         1 |
| 0.0008435533      |         1 |
| 0.0327052586      |         1 |
| 0.0077010053      |         1 |
| 0.0031703569      |         1 |
| 0.0031446218      |         1 |
| 0.0134762982      |         1 |
| 0.010873883       |         1 |
| 0.0083855269      |         1 |
| 0.0140283508      |         1 |
| 0.0130107878      |         1 |
| 0.1226246655      |         1 |
| 0.0042399825      |         1 |
| 0.0329051353      |         1 |
| 0.0135756154      |         1 |
| 0.0025907995      |         1 |
| 0.0092800306      |         1 |
| 0.0263656527      |         1 |
| 0.0267814267      |         1 |
| 0.0155252926      |         1 |
| 0.0103664733      |         1 |
| 0.088477686       |         1 |
| 0.0016537131      |         1 |
| 0.0190077741      |         1 |
| 0.0478990637      |         1 |
| 0.0961839855      |         1 |
| 0.0108975777      |         1 |
| 0.0331085026      |         1 |
| 4.341919E-4       |         1 |
| 0.0022699493      |         1 |
| 0.0068772836      |         1 |
| 0.0015879794      |         1 |
| 0.010363251       |         1 |
| 0.1268225759      |         1 |
| 0.0014022293      |         1 |
| 0.0390057564      |         1 |
| 0.0010644135      |         1 |
| 5.913295E-4       |         1 |
| 0.0045910212      |         1 |
| 5.46016E-5        |         1 |
| 0.0603630878      |         1 |
| 0.0010369247      |         1 |
| 0.0012950117      |         1 |
| 0.004046353       |         1 |
| 0.0070502991      |         1 |
| 0.0079585575      |         1 |
| 0.0115355197      |         1 |
| 0.011339305       |         1 |
| 0.002194189       |         1 |
| 0.0220958386      |         1 |
| 0.0101853171      |         1 |
| 0.0693961754      |         1 |
| 0.0045611877      |         1 |
| 0.0706611872      |         1 |
| 0.0211434029      |         1 |
| 0.0015904512      |         1 |
| 0.0546217039      |         1 |
| 0.006467144       |         1 |
| 0.0227873418      |         1 |
| 0.000365556       |         1 |
| 0.0003339409      |         1 |
| 0.0006683663      |         1 |
| 0.0396518558      |         1 |
| 0.005956199       |         1 |
| 0.0010354083      |         1 |
| 0.0201447029      |         1 |
| 0.0786646008      |         1 |
| 0.0009050501      |         1 |
| 0.0267370995      |         1 |
| 0.0011022378      |         1 |
| 0.0125430478      |         1 |
| 0.002255568       |         1 |
| 0.0050337035      |         1 |
| 0.0120314443      |         1 |
| 0.0222414527      |         1 |
| 0.0009315024      |         1 |
| 0.033692468       |         1 |
| 0.0014799717      |         1 |
| 0.0040971735      |         1 |
| 0.0109554734      |         1 |

In [115]:
# Diagnóstico: confirmar qué representa realmente la columna
print("Tipo de dato:")
print(events["is_controlled_possession"].dtype)

print("\nValores más frecuentes:")
print(
    events["is_controlled_possession"]
    .value_counts(dropna=False)
    .head(15)
    .to_frame("conteo").to_markdown()
)

Tipo de dato:
object

Valores más frecuentes:
| is_controlled_possession   |   conteo |
|:---------------------------|---------:|
| True                       |   295052 |
| nan                        |   134633 |
| False                      |    54053 |
| true                       |     4544 |
| midfield_third             |     4067 |
| final_third                |     3872 |
| defensive_third            |     2774 |
| false                      |     1036 |
| 0.0017974227               |       21 |
| 0.0091792364               |       20 |
| 0.0133826835               |       19 |
| 0.0589727312               |       19 |
| 0.005055401                |       18 |
| 0.0017451613               |       18 |
| 0.0103466902               |       17 |

In [116]:
ev = events.sort_values(["match_id", "index"]).copy()

groups = {
    key: group.reset_index(drop=True)
    for key, group in ev.groupby(
        ["match_id", "possession"], sort=False
    )
}

continuity_results = []

for row in selected.itertuples(index=False):
    key = (row.match_id, row.possession)
    group = groups.get(key)

    if group is None:
        continuity_results.append((False, None, None))
        continue

    positions = group.index[group["index"] == row.index].tolist()

    if not positions:
        continuity_results.append((False, None, None))
        continue

    pos = positions[0]
    following = group.iloc[pos + 1:]

    # Buscar recepción del destinatario antes del siguiente pase
    next_pass = following.index[
        following["event_type_name"] == "Pass"
    ].tolist()

    if next_pass:
        following = following.loc[:next_pass[0] - 1]

    receipts = following[
        (following["event_type_name"] == "Ball Receipt*")
        & (following["player_name"] == row.pass_recipient_name)
    ]

    if receipts.empty:
        continuity_results.append((False, None, None))
        continue

    receipt_idx = receipts.index[0]
    receipt_pos = group.index.get_loc(receipt_idx)

    if receipt_pos + 1 >= len(group):
        continuity_results.append((True, None, None))
        continue

    next_action = group.iloc[receipt_pos + 1]

    continuity_results.append((
        True,
        next_action["team_name"],
        next_action["event_type_name"]
    ))

In [117]:
selected["receipt_found"] = [r[0] for r in continuity_results]
selected["team_after_receipt"] = [r[1] for r in continuity_results]
selected["action_after_receipt"] = [r[2] for r in continuity_results]

confirmed = selected[selected["receipt_found"]].copy()

print("\nPases con recepción del destinatario:", len(confirmed))

print("\nEquipo de la acción posterior a la recepción:")
print(
    confirmed["team_after_receipt"]
    .value_counts(dropna=False)
    .to_frame("conteo").to_markdown()
)

print("\nTipo de acción posterior:")
print(
    confirmed["action_after_receipt"]
    .value_counts(dropna=False)
    .head(12)
    .to_frame("conteo").to_markdown()
)

continuity_rate = confirmed["team_after_receipt"].eq("América").mean()

print(
    "\nProporción con siguiente evento atribuido a América:",
    f"{continuity_rate:.2%}"
)

Pases con recepción del destinatario: 8604

Equipo de la acción posterior a la recepción:
| team_after_receipt   |   conteo |
|:---------------------|---------:|
| América              |     7187 |
|                      |      817 |
| Cruz Azul            |       67 |
| Pachuca              |       54 |
| Guadalajara          |       46 |
| Toluca               |       43 |
| Monterrey            |       40 |
| Tigres UANL          |       39 |
| Tijuana              |       37 |
| León                 |       37 |
| Pumas UNAM           |       33 |
| Atlas                |       33 |
| Puebla               |       29 |
| Santos Laguna        |       28 |
| Mazatlán             |       26 |
| Atlético San Luis    |       25 |
| Necaxa               |       24 |
| Querétaro            |       23 |
| Juárez               |       16 |

Tipo de acción posterior:
| action_after_receipt   |   conteo |
|:-----------------------|---------:|
| Carries                |     5891 |
| Pass                   |     1191 |
|                        |      817 |
| Clearance              |      157 |
| Pressure               |       86 |
| Interception           |       85 |
| Miscontrol             |       83 |
| Duel                   |       83 |
| Shot                   |       65 |
| Ball Recovery          |       40 |
| Foul Committed         |       30 |
| Goal Keeper            |       19 |

Proporción con siguiente evento atribuido a América: 83.53%